# Generated by Django 6.0.1 on 2026-01-30 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('curricula', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculum',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curricula', to='core.family'),
        ),
    ]
