# Generated by Django 6.0.1 on 2026-01-31 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curricula', '0002_curriculum_family'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculum',
            name='website_url',
            field=models.URLField(blank=True, default='', help_text="Optional link to the curriculum's website"),
        ),
    ]
