# Generated by Django 6.0.1 on 2026-07-07 23:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curricula', '0003_curriculum_website_url'),
        ('students', '0002_student_family'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='curricula.curriculum')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='CurriculumDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('doc_type', models.CharField(choices=[('instructor_guide', "Instructor's Guide"), ('textbook', 'Textbook'), ('workbook', 'Workbook'), ('tests', 'Tests'), ('other', 'Other')], default='other', max_length=30)),
                ('file', models.FileField(upload_to='curriculum_docs/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='curricula.curriculum')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_curriculum_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['doc_type', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(help_text='Sequence within the chapter (openers first).')),
                ('number', models.PositiveIntegerField(blank=True, help_text='Printed lesson number; blank for openers/reviews.', null=True)),
                ('title', models.CharField(max_length=200)),
                ('lesson_type', models.CharField(choices=[('opener', 'Chapter Opener'), ('lesson', 'Lesson'), ('practice', 'Practice'), ('review', 'Review')], default='lesson', max_length=20)),
                ('objectives', models.TextField(blank=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='curricula.chapter')),
            ],
            options={
                'ordering': ['chapter__number', 'order'],
            },
        ),
        migrations.CreateModel(
            name='CurriculumPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='students.student')),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='curricula.curriculum')),
                ('current_lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='curricula.lesson')),
            ],
        ),
        migrations.AddConstraint(
            model_name='chapter',
            constraint=models.UniqueConstraint(fields=('curriculum', 'number'), name='unique_chapter_number_per_curriculum'),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.UniqueConstraint(fields=('chapter', 'order'), name='unique_lesson_order_per_chapter'),
        ),
        migrations.AddConstraint(
            model_name='curriculumplacement',
            constraint=models.UniqueConstraint(fields=('child', 'curriculum'), name='unique_placement_per_child_curriculum'),
        ),
    ]
