# Generated by Django 6.0.1 on 2026-07-09 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curricula', '0004_chapter_curriculumdocument_lesson_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="e.g., 'Answer Key' or 'Read-aloud on YouTube'.", max_length=200)),
                ('url', models.URLField()),
                ('resource_type', models.CharField(choices=[('answer_key', 'Answer key'), ('guide', 'Guide'), ('video', 'Video'), ('reference', 'Reference'), ('other', 'Link')], default='other', max_length=20)),
                ('teacher_only', models.BooleanField(default=False, help_text='Keep this for the teacher — never show it to a child.')),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='curricula.curriculum')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
