# Generated by Django 6.0.1 on 2026-07-09 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curricula', '0006_enable_pg_trgm'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculum',
            name='is_online',
            field=models.BooleanField(default=False, help_text="This subject is done on an external website (e.g. Beast Academy, DIVE). The child's portal launches out to the website instead of showing in-app lessons."),
        ),
    ]
