# Generated by Django 6.0.1 on 2026-07-30 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curricula', '0008_lessonprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculum',
            name='is_active',
            field=models.BooleanField(default=True, help_text="Inactive curricula are hidden from the Curricula list by default and from every child's portal. Toggle 'Show deactivated' to find them."),
        ),
        migrations.AddField(
            model_name='curriculumplacement',
            name='is_active',
            field=models.BooleanField(default=True, help_text="Inactive placements hide this subject from this child's portal only (siblings can keep the same curriculum)."),
        ),
    ]
