# Generated by Django 6.0.1 on 2026-08-10 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curricula', '0009_curriculum_and_placement_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculumplacement',
            name='weekly_pace',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Project remaining lessons onto the family calendar at this many per week (Mon–Fri). Blank = no due dates for this subject.', null=True),
        ),
    ]
