# Generated by Django 6.0.1 on 2026-08-13 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curricula', '0011_default_mission_pace'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculum',
            name='archived_at',
            field=models.DateTimeField(blank=True, help_text="Set when a course is finished and retired. This is what separates 'not started yet' from 'done' — both are switched off, but only one of them is ever coming back.", null=True),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='is_active',
            field=models.BooleanField(default=True, help_text="Off means the girls can't see it — either it's queued up for later or it's finished. Everything is kept either way."),
        ),
    ]
