# Generated by Django 6.0.1 on 2026-08-21 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curricula', '0012_curriculum_archived_at_alter_curriculum_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculumdocument',
            name='student_file',
            field=models.FileField(blank=True, help_text='Generated: just the student_pages, extracted. Never the source file — that is the teacher edition.', upload_to='booklets/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='curriculumdocument',
            name='student_label',
            field=models.CharField(blank=True, help_text='What the child sees it called, e.g. "This week\'s issue".', max_length=200),
        ),
        migrations.AddField(
            model_name='curriculumdocument',
            name='student_pages',
            field=models.CharField(blank=True, help_text="Pages of the source PDF a child may see, 1-based — e.g. '23-26' or '1-4,9'. Blank means she sees nothing.", max_length=100),
        ),
    ]
