# Generated by Django 6.0.1 on 2026-08-25 20:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_handoff'),
        ('curricula', '0013_booklet_child_copy'),
        ('students', '0004_student_portal_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='A photo, scan, PDF or document of the finished work.', upload_to='lesson_work/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'heic', 'webp', 'pdf', 'doc', 'docx'])])),
                ('caption', models.CharField(blank=True, help_text="Optional — e.g. 'Chapter 4 test' or 'practice set B'.", max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_work', to='students.student')),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_work', to='core.family')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_uploads', to='curricula.lesson')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
