# Generated by Django 6.0.1 on 2026-08-28 03:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0004_student_portal_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor_a', models.PositiveSmallIntegerField()),
                ('factor_b', models.PositiveSmallIntegerField()),
                ('product', models.PositiveSmallIntegerField()),
                ('cluster', models.CharField(choices=[('ones_twos', 'Ones & Twos'), ('fives', 'Fives'), ('tens', 'Tens'), ('squares', 'Squares'), ('threes', 'Threes'), ('fours', 'Fours'), ('nines', 'Nines'), ('sixes', 'Sixes'), ('sevens', 'Sevens'), ('eights', 'Eights')], max_length=16)),
                ('is_hard_core', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['factor_a', 'factor_b'],
                'constraints': [models.UniqueConstraint(fields=('factor_a', 'factor_b'), name='unique_fact_pair')],
            },
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('num_attempted', models.PositiveSmallIntegerField(default=0)),
                ('num_correct', models.PositiveSmallIntegerField(default=0)),
                ('num_fluent', models.PositiveSmallIntegerField(default=0)),
                ('longest_streak', models.PositiveSmallIntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fact_sessions', to='students.student')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('mult', 'Multiplication'), ('div_a', 'Divide by the first factor'), ('div_b', 'Divide by the second factor')], max_length=8)),
                ('answer_given', models.IntegerField(blank=True, null=True)),
                ('is_correct', models.BooleanField()),
                ('response_ms', models.PositiveIntegerField()),
                ('was_fluent', models.BooleanField()),
                ('client_uuid', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='factfluency.fact')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='factfluency.gamesession')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(unique=True)),
                ('slug', models.SlugField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('blurb', models.CharField(blank=True, max_length=200)),
                ('cluster', models.CharField(choices=[('ones_twos', 'Ones & Twos'), ('fives', 'Fives'), ('tens', 'Tens'), ('squares', 'Squares'), ('threes', 'Threes'), ('fours', 'Fours'), ('nines', 'Nines'), ('sixes', 'Sixes'), ('sevens', 'Sevens'), ('eights', 'Eights')], max_length=16)),
                ('mastery_threshold', models.FloatField(default=0.9)),
                ('facts', models.ManyToManyField(related_name='levels', to='factfluency.fact')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='gamesession',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='factfluency.level'),
        ),
        migrations.CreateModel(
            name='PersonalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('best_time', 'Fastest clean round'), ('best_accuracy', 'Best accuracy'), ('longest_streak', 'Longest streak')], max_length=16)),
                ('value', models.FloatField()),
                ('achieved_at', models.DateTimeField(auto_now=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='factfluency.level')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='factfluency.gamesession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fact_records', to='students.student')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('student', 'level', 'record_type'), name='unique_record_per_student_level')],
            },
        ),
        migrations.CreateModel(
            name='StudentFactState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('mult', 'Multiplication'), ('div_a', 'Divide by the first factor'), ('div_b', 'Divide by the second factor')], max_length=8)),
                ('leitner_box', models.PositiveSmallIntegerField(default=1)),
                ('due_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_response_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('consecutive_fluent', models.PositiveSmallIntegerField(default=0)),
                ('is_mastered', models.BooleanField(default=False)),
                ('total_attempts', models.PositiveIntegerField(default=0)),
                ('total_correct', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='factfluency.fact')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fact_states', to='students.student')),
            ],
            options={
                'indexes': [models.Index(fields=['student', 'due_at'], name='factfluency_student_6e1a30_idx')],
                'constraints': [models.UniqueConstraint(fields=('student', 'fact', 'operation'), name='unique_fact_state_per_student')],
            },
        ),
    ]
