# Generated by Django 6.0.1 on 2026-08-28 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factfluency', '0002_seed_levels'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='is_challenge',
            field=models.BooleanField(default=False),
        ),
    ]
