# Generated by Django 6.0.1 on 2026-08-28 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factfluency', '0004_seed_challenge_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfactstate',
            name='last_counted_session',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
