# Generated by Django 6.0.1 on 2026-08-28 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factfluency', '0005_last_counted_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='client_uuid',
            field=models.CharField(max_length=64),
        ),
        migrations.AddConstraint(
            model_name='attempt',
            constraint=models.UniqueConstraint(fields=('session', 'client_uuid'), name='unique_attempt_per_session'),
        ),
    ]
