# Generated by Django 6.0.1 on 2026-07-08 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_family'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='grade_level',
            field=models.CharField(choices=[('PREK', 'Pre-K'), ('K', 'Kindergarten'), ('G01', 'Level 1'), ('G02', 'Level 2'), ('G03', 'Level 3'), ('G04', 'Level 4'), ('G05', 'Level 5'), ('G06', 'Level 6'), ('G07', 'Level 7'), ('G08', 'Level 8'), ('G09', 'Level 9'), ('G10', 'Level 10'), ('G11', 'Level 11'), ('G12', 'Level 12')], help_text="The child's year of school (their Level).", max_length=4, verbose_name='level'),
        ),
    ]
