# Generated by Django 6.0.1 on 2026-07-08 15:42

import students.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_grade_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='portal_key',
            field=models.CharField(default=students.models._new_portal_key, editable=False, help_text="Rotate to revoke this child's existing portal link.", max_length=32),
        ),
    ]
