# Generated by Django 6.0.1 on 2026-01-31 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='resent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
