# Generated by Django 6.0.1 on 2026-07-08 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_invitation_resent_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymembership',
            name='role',
            field=models.CharField(choices=[('parent', 'Parent'), ('guardian', 'Guardian'), ('grandparent', 'Grandparent'), ('teacher', 'Teacher'), ('admin', 'Admin')], max_length=20),
        ),
    ]
