# Generated by Django 6.0.1 on 2026-08-21 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_familymembership_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymembership',
            name='role',
            field=models.CharField(choices=[('parent', 'Parent — full access'), ('teacher', 'Teacher or guardian — view only'), ('admin', 'Admin')], max_length=20),
        ),
    ]
