# Generated by Django 6.0.1 on 2026-08-21 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_retire_guardian_and_grandparent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Handoff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('covers_since', models.DateTimeField()),
                ('covers_until', models.DateTimeField()),
                ('note', models.TextField(blank=True)),
                ('body', models.TextField(blank=True, help_text='The message as it was sent, kept verbatim.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent')], default='draft', max_length=10)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('sent_to', models.CharField(blank=True, help_text='Where it actually went, recorded at send time.', max_length=400)),
                ('copied_at', models.DateTimeField(blank=True, help_text='When it was copied for texting. Copying is not sending, and the record should not claim otherwise.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handoffs_sent', to=settings.AUTH_USER_MODEL)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handoffs', to='core.family')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HandoffRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, help_text='Only for your own reference when texting — the app never sends to it.', max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handoff_recipients', to='core.family')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
