# Generated by Django 6.0.1 on 2026-07-08 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_alter_familymembership_role'),
        ('students', '0004_student_portal_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="e.g. 'Guitar', 'Drums', 'Coding'", max_length=200)),
                ('provider', models.CharField(blank=True, help_text="e.g. 'School of Rock', 'CodaKid'", max_length=120)),
                ('url', models.URLField(help_text="The program's login/home page.")),
                ('emoji', models.CharField(default='🎯', max_length=8)),
                ('cadence', models.CharField(choices=[('none', 'No reminder'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='none', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_logged_at', models.DateField(blank=True, null=True)),
                ('snoozed_until', models.DateField(blank=True, null=True)),
                ('is_muted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='core.family')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_activities', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(blank=True, help_text='Leave blank for a whole-family activity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='students.student')),
            ],
            options={
                'verbose_name_plural': 'external activities',
                'ordering': ['provider', 'title'],
            },
        ),
    ]
