"""
Django settings for homeschool_hub project.

Generated by 'django-admin startproject' using Django 5.0.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env_path = BASE_DIR / ".env"

# Load environment variables from .env file
load_dotenv(env_path)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# ---------------------------------------------------------------------------
# Environment Variable Helpers
# ---------------------------------------------------------------------------


def _env_bool(name: str, default: bool = False) -> bool:
    """
    Parse boolean from environment variable string.
    Accepts: "1", "true", "yes", "on" (case-insensitive) as True.
    Returns default if variable is not set.
    """
    val = os.getenv(name)
    if val is None:
        return default
    return val.strip().lower() in ("1", "true", "yes", "on")


def _env_list(name: str, default: str = "") -> list:
    """
    Parse comma-separated list from environment variable.
    Strips whitespace from each item and removes empty strings.
    Example: "a.com, b.com" -> ["a.com", "b.com"]
    """
    val = os.getenv(name, default)
    if not val:
        return []
    return [item.strip() for item in val.split(",") if item.strip()]


# ---------------------------------------------------------------------------
# Core Settings
# ---------------------------------------------------------------------------

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY", "unsafe-secret-for-dev-only")

# DEBUG: Default True for local dev (when env var not set), explicitly set False in production
DEBUG = _env_bool("DEBUG", default=True)

# ALLOWED_HOSTS: Comma-separated list of hostnames
# Local dev default: localhost only. Production: set to exact hostname(s).
# Example: ALLOWED_HOSTS="myapp.herokuapp.com,www.mydomain.com"
_default_hosts = "127.0.0.1,localhost" if DEBUG else ""
ALLOWED_HOSTS = _env_list("ALLOWED_HOSTS", default=_default_hosts)

# Application definition

INSTALLED_APPS = [
    "accounts",  # Our custom accounts app
    "core",  # Family & organization domain models
    "students",  # Child profile management
    "curricula",  # Curriculum management
    "assignments",  # Assignment tracking
    "dashboard",  # Parent progress dashboard
    "storages",  # django-storages for R2/S3
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "crispy_forms",
    "crispy_bootstrap5",
]

# Crispy Forms configuration
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# Set the custom user model for our app. It must be declared after INSTALLED_APPS.
AUTH_USER_MODEL = "accounts.CustomUser"

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "homeschool_hub.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "homeschool_hub.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# Database configuration from environment variable
DATABASES = {"default": dj_database_url.parse(os.getenv("DATABASE_URL"), conn_max_age=600)}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [BASE_DIR / "static"]

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTHENTICATION_BACKENDS = [
    "accounts.backends.EmailOrUsernameModelBackend",
    "django.contrib.auth.backends.ModelBackend",
]

EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
DEFAULT_FROM_EMAIL = "no-reply@homeschool.local"

LOGIN_URL = "accounts:login"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"

INVITE_MAX_AGE_DAYS = 7

# For dev only; set these True only in prod:
CSRF_COOKIE_SECURE = False
SESSION_COOKIE_SECURE = False
SECURE_SSL_REDIRECT = False

# ---------------------------------------------------------------------------
# Storage Configuration (Static + Media)
# ---------------------------------------------------------------------------

# Toggle for R2 media storage (set USE_R2=true in production)
USE_R2 = _env_bool("USE_R2", default=False)

# Static files: Always use WhiteNoise (not R2)
STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Media files: R2 in production, local filesystem in development
if USE_R2:
    # Cloudflare R2 (S3-compatible) storage for media
    STORAGES["default"] = {
        "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
        "OPTIONS": {
            "access_key": os.getenv("R2_ACCESS_KEY_ID"),
            "secret_key": os.getenv("R2_SECRET_ACCESS_KEY"),
            "bucket_name": os.getenv("R2_BUCKET_NAME", "steadfast-scholars-media"),
            "endpoint_url": os.getenv("R2_ENDPOINT_URL"),
            "region_name": os.getenv("R2_REGION", "auto"),
            "default_acl": None,  # R2 doesn't support ACLs
            "querystring_auth": True,  # Use signed URLs for private files
            "file_overwrite": False,
        },
    }
    MEDIA_URL = ""  # URLs come from signed S3 URLs
else:
    # Local filesystem storage for development
    STORAGES["default"] = {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    }
    MEDIA_ROOT = BASE_DIR / "media"
    MEDIA_URL = "/media/"