"""
Django settings for homeschool_hub project.

Generated by 'django-admin startproject' using Django 5.0.14; project now runs on Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
import sys
from dotenv import load_dotenv
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env_path = BASE_DIR / ".env"

# Load environment variables from .env file
load_dotenv(env_path)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# ---------------------------------------------------------------------------
# Environment Variable Helpers
# ---------------------------------------------------------------------------


def _env_bool(name: str, default: bool = False) -> bool:
    """
    Parse boolean from environment variable string.
    Accepts: "1", "true", "yes", "on" (case-insensitive) as True.
    Returns default if variable is not set.
    """
    val = os.getenv(name)
    if val is None:
        return default
    return val.strip().lower() in ("1", "true", "yes", "on")


def _env_list(name: str, default: str = "") -> list:
    """
    Parse comma-separated list from environment variable.
    Strips whitespace from each item and removes empty strings.
    Example: "a.com, b.com" -> ["a.com", "b.com"]
    """
    val = os.getenv(name, default)
    if not val:
        return []
    return [item.strip() for item in val.split(",") if item.strip()]


def _env_int(name: str, default: int) -> int:
    """
    Parse integer from environment variable.
    Returns default if variable is not set or cannot be parsed.
    """
    val = os.getenv(name)
    if val is None:
        return default
    try:
        return int(val)
    except ValueError:
        return default


def _env_float(name: str, default: float) -> float:
    """
    Parse float from environment variable.
    Returns default if variable is not set or cannot be parsed.
    """
    val = os.getenv(name)
    if val is None:
        return default
    try:
        return float(val)
    except ValueError:
        return default


# ---------------------------------------------------------------------------
# Core Settings
# ---------------------------------------------------------------------------

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY", "unsafe-secret-for-dev-only")

# Fail CLOSED. Prod sets DEBUG=false explicitly, but any NEW environment that
# forgets it (review app, restored dyno, rebuilt account) would otherwise serve
# full tracebacks — settings, local variables and query contents — to anyone
# who triggers an error. Local dev opts in via .env.
DEBUG = _env_bool("DEBUG", default=False)

# ALLOWED_HOSTS: Comma-separated list of hostnames
# Local dev default: localhost only. Production: set to exact hostname(s).
# Example: ALLOWED_HOSTS="myapp.herokuapp.com,www.mydomain.com"
_default_hosts = "127.0.0.1,localhost" if DEBUG else ""
ALLOWED_HOSTS = _env_list("ALLOWED_HOSTS", default=_default_hosts)

# Application definition

INSTALLED_APPS = [
    "accounts",  # Our custom accounts app
    "core",  # Family & organization domain models
    "students",  # Child profile management
    "curricula",  # Curriculum management
    "assignments",  # Assignment tracking
    "dashboard",  # Parent progress dashboard
    "worklog",  # Work log: completed-work records
    "tutor",  # AI tutor layer (mastery grader)
    "portal",  # Tokenless student portal (kids see only their own work)
    "activities",  # External activities (School of Rock, CodaKid) + check-in nudge
    "inbox",  # Parent action inbox (aggregates items needing the parent)
    "lingua",  # Spanish acquisition module (extractable; see lingua/SPEC.md)
    "storages",  # django-storages for R2/S3
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",  # required by allauth
    "crispy_forms",
    "crispy_bootstrap5",
    # Social auth (additive — the existing email/username + password login stays).
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
]

# Crispy Forms configuration
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# Set the custom user model for our app. It must be declared after INSTALLED_APPS.
AUTH_USER_MODEL = "accounts.CustomUser"

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    # CSP is OFF site-wide (SECURE_CSP unset) — lingua views opt in per-response
    # via @lingua_csp, so legacy pages are untouched (D-13).
    "django.middleware.csp.ContentSecurityPolicyMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "allauth.account.middleware.AccountMiddleware",  # allauth
    "accounts.middleware.TimezoneMiddleware",  # per-user timezone
]

ROOT_URLCONF = "homeschool_hub.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "django.template.context_processors.csp",  # {{ csp_nonce }} for lingua templates
                "core.context_processors.family_context",
                "core.context_processors.onboarding_hints",
            ],
        },
    },
]

WSGI_APPLICATION = "homeschool_hub.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Database configuration from DATABASE_URL, falling back to local SQLite when unset.
DATABASES = {
    "default": dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Speed up the test suite: use a fast (insecure) password hasher when running
# `manage.py test`. Django hashes a password on nearly every user-creating test,
# and the default PBKDF2 hasher dominates runtime. This is auto-detected from
# argv, so no separate settings module or test runner flag is needed.
# Match the SUBCOMMAND, not any argument: `"test" in sys.argv` also fires for
# `manage.py createsuperuser --username test`, which then writes an MD5 password
# hash the web dyno cannot verify — that account can never log in, with nothing
# to explain why. It now also decides a security default (SECURE_SSL_REDIRECT).
#
# Deliberately NOT keyed off PYTEST_CURRENT_TEST: pytest sets that per-test, long
# after settings import, so it would be dead here — while still being live in
# every other process, where one env var of that name would silently turn off the
# HTTPS redirect and make every password an unsalted MD5.
TESTING = len(sys.argv) > 1 and sys.argv[1] == "test"
if TESTING:
    PASSWORD_HASHERS = ["django.contrib.auth.hashers.MD5PasswordHasher"]
    # Grade inline (no daemon thread) under the test runner: a background grade
    # thread races the test's own transaction on SQLite ("table is locked") and
    # muddies output. Tests that exercise grading mock the AI client anyway.
    GRADE_IN_BACKGROUND = False
    # Never reach the real grader from the suite even if the env carries a key
    # (Heroku config, a developer's .env): a test that mocks is_configured but
    # not grade_work would otherwise make a live billed API call.
    ANTHROPIC_API_KEY = ""


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "America/Los_Angeles"  # the family's home timezone (Sacramento)

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [BASE_DIR / "static"]

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTHENTICATION_BACKENDS = [
    "accounts.backends.EmailOrUsernameModelBackend",
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",  # social login (django-allauth)
]

# --- Social auth (django-allauth) -------------------------------------------
# ADDITIVE: the existing email/username + password login is unchanged; allauth
# only adds "Sign in with Google". Google credentials come from env vars, so the
# button appears only once they're set (create a Google OAuth app, then set
# GOOGLE_OAUTH_CLIENT_ID / GOOGLE_OAUTH_SECRET on Heroku).
SITE_ID = 1
# allauth is used for SOCIAL login ONLY — the app keeps its own /accounts/ register,
# email-verification and login flows. A custom adapter closes allauth's own local
# email/password signup so it can't mint active, unverified accounts. We do NOT
# auto-link a social login to an existing account by email: that path (allauth's
# email-authentication) wipes the local password. Existing users connect Google
# explicitly from Settings, which links without disturbing their password.
ACCOUNT_ADAPTER = "accounts.adapters.NoLocalSignupAdapter"
SOCIALACCOUNT_ADAPTER = "accounts.adapters.SocialSignupAdapter"  # social signup open + safe email link
ACCOUNT_EMAIL_VERIFICATION = "none"      # the app runs its own verification flow
SOCIALACCOUNT_LOGIN_ON_GET = True        # one-click provider button (no interstitial)

SOCIALACCOUNT_PROVIDERS = {}
_google_client_id = os.getenv("GOOGLE_OAUTH_CLIENT_ID", "")
if _google_client_id:
    SOCIALACCOUNT_PROVIDERS["google"] = {
        "APP": {
            "client_id": _google_client_id,
            "secret": os.getenv("GOOGLE_OAUTH_SECRET", ""),
            "key": "",
        },
        "SCOPE": ["profile", "email"],
        "AUTH_PARAMS": {"access_type": "online"},
    }

# Email: real SMTP (e.g. Amazon SES) when EMAIL_HOST is configured, else the
# console backend for local dev. Set EMAIL_HOST / EMAIL_HOST_USER /
# EMAIL_HOST_PASSWORD / DEFAULT_FROM_EMAIL in Heroku config to enable delivery
# (invites + email verification depend on this). The test runner overrides this
# with the in-memory backend automatically.
EMAIL_HOST = os.getenv("EMAIL_HOST", "")
if EMAIL_HOST:
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
    # Never inherit the global socket default (which can block forever):
    # a wedged SES connection would hang a dyno worker on register/invite.
    EMAIL_TIMEOUT = 10
    EMAIL_PORT = _env_int("EMAIL_PORT", 587)
    EMAIL_USE_TLS = _env_bool("EMAIL_USE_TLS", True)
    EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
    EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
else:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "no-reply@homeschool.local")

# Absolute base URL for links in emails sent OUTSIDE a request (e.g. the action-
# inbox submission notifier runs in a background grading thread with no request).
# Set to the prod origin on Heroku; falls back to a relative link when unset.
SITE_BASE_URL = os.getenv("SITE_BASE_URL", "")

LOGIN_URL = "accounts:login"
# Route through post_login so first-time users see the welcome page and
# read-only reviewers land on Progress (a safe ?next= still takes precedence).
LOGIN_REDIRECT_URL = "accounts:post_login"
LOGOUT_REDIRECT_URL = "/"

INVITE_MAX_AGE_DAYS = 7

# ---------------------------------------------------------------------------
# AI tutor (Anthropic) — server-side only. The grader stays disabled until a
# key is set; add ANTHROPIC_API_KEY in Heroku config to enable it.
# ---------------------------------------------------------------------------
ANTHROPIC_API_KEY = os.getenv("ANTHROPIC_API_KEY", "")
TUTOR_MODEL = os.getenv("TUTOR_MODEL", "claude-opus-4-8")

# Monthly AI hard-stop ceiling in USD for the tutor path (HH-145) — grading, the
# writing coach, and the writing-box helpers. Lingua has had one since LGA-29;
# tutor is the HIGHER-volume side (it fires on ordinary use, not on an operator
# authoring content) and had no backstop at all, so a retry storm or a stuck
# daemon would have shown up first as a bill.
#
# The two ceilings are separate on purpose: lingua must stay extractable (D-03),
# so its ledger travels with it. They are not additive — set each to the share of
# the account you want that side to be able to spend.
TUTOR_MONTHLY_COST_CEILING_USD = _env_float("TUTOR_MONTHLY_COST_CEILING_USD", 25.0)

# USD per MILLION tokens, (input, output), per model. Tutor uses two tiers — a big
# model for grading and coaching, a small one for word help and spellcheck — and
# they differ by more than 10x, so cost has to be priced per model at the moment
# of the call, not derived from a token total afterwards.
#
# These are ESTIMATES, not a bill. They set where the ceiling trips and what the
# admin's spend column reads, so check them against the current price list when a
# model changes — pricing that is wrong by 3x turns a $25 ceiling into an $8 one.
# Override any of them via TUTOR_AI_PRICES in code, or raise the ceiling.
TUTOR_AI_PRICES = {
    "claude-opus-4-8": (5.0, 25.0),
    "claude-opus-5": (5.0, 25.0),
    "claude-sonnet-5": (3.0, 15.0),
    "claude-haiku-4-5": (1.0, 5.0),
}
# Fallback for a model not in the table. Deliberately the most expensive tier:
# an unrecognised model must over-estimate and stop early, never under-count and
# sail past the ceiling.
TUTOR_AI_PRICE_FALLBACK = (15.0, 75.0)

# ---------------------------------------------------------------------------
# Lingua (Spanish acquisition module) — namespaced config (D-06). Extractable
# module: no FK to host models; learner carried as host_student_id (D-03).
# ---------------------------------------------------------------------------
LINGUA = {
    "DEFAULT_LANGUAGE": "es",
    "DEFAULT_VARIANT": "es-MX",
    # Monthly AI hard-stop ceiling in USD (D-52/57, LGA-29). Estimated from token
    # usage × the per-million-token prices below (Opus-tier defaults; override via env
    # if the model/price changes). Story generation is operator content-authoring, so
    # this is a single monthly ceiling, not per-child.
    "MONTHLY_COST_CEILING_USD": _env_int("LINGUA_MONTHLY_COST_CEILING_USD", 25),
    "AI_PRICE_INPUT_PER_MTOK": _env_float("LINGUA_AI_PRICE_INPUT_PER_MTOK", 5.0),
    "AI_PRICE_OUTPUT_PER_MTOK": _env_float("LINGUA_AI_PRICE_OUTPUT_PER_MTOK", 25.0),
    # Audit-trail retention in days (~18 months); enforced by `purge_stale` (D-56).
    "AUDIT_RETENTION_DAYS": _env_int("LINGUA_AUDIT_RETENTION_DAYS", 548),
    # An OUTBOUND link for the adult's AI conversation practice (LGA-103). A plain
    # href and nothing else: no conversation code lives in this codebase, so there
    # is nothing for a child to reach even if every other gate failed, and D-52/D-54
    # (no child data to AI, AI disclosure) never attach because the app is not the
    # one running it. Adults only — the research is unambiguous that generative
    # voice tutors are inappropriate for these children, and every such product's
    # own terms exclude them anyway.
    "ADULT_CONVERSATION_URL": os.getenv(
        "LINGUA_ADULT_CONVERSATION_URL", "https://languatalk.com/"),
    # TTS provider order (SPIKE-01: Polly primary, edge-tts fallback — D-17/D-18).
    "TTS_PROVIDER": os.getenv("LINGUA_TTS_PROVIDER", "polly"),
    # Polly synthesis defaults (es-MX neural). Authoring-time only (tts_build);
    # region falls back to ambient AWS config when unset (D-17).
    "TTS_VOICE": os.getenv("LINGUA_TTS_VOICE", "Mia"),
    "TTS_ENGINE": os.getenv("LINGUA_TTS_ENGINE", "neural"),
    "TTS_REGION": os.getenv("LINGUA_TTS_REGION") or None,
    # Illustrated storybook pictures (LGA-71). One image per 1–2 sentences, fixed
    # aspect site-wide. Priced per image and folded into MONTHLY_COST_CEILING_USD so
    # image spend shares the one hard-stop. Generation uses the Replicate seam
    # (settings.MANGA_IMAGE_MODEL); the token must be set wherever img_build runs.
    "ILLUSTRATION_ASPECT": os.getenv("LINGUA_ILLUSTRATION_ASPECT", "4:3"),
    "ILLUSTRATION_MAX_BEATS": _env_int("LINGUA_ILLUSTRATION_MAX_BEATS", 8),
    "IMAGE_PRICE_PER_IMAGE_USD": _env_float("LINGUA_IMAGE_PRICE_PER_IMAGE_USD", 0.04),
    # Image model id used in the content hash (so a model change re-bakes). LINGUA-
    # namespaced for extractability; defaults to the SAME value the host adapter's
    # Replicate seam uses (MANGA_IMAGE_MODEL), so the hashed model == the model
    # actually invoked. Keep them in sync if you override either.
    "IMAGE_MODEL": os.getenv("LINGUA_IMAGE_MODEL")
    or os.getenv("MANGA_IMAGE_MODEL", "google/nano-banana-2"),
    # Reader voice picker (LGA-70): the ordered set of narration voices offered on the
    # read-along page. All Amazon Polly *neural* voices — each emits word-boundary
    # marks, so the word-by-word highlighting works identically for every one (edge-tts
    # only emits sentence marks and would break sync, so it is NOT used here). ``id`` is
    # the Polly VoiceId; ``label`` is the (Spanish) name the child sees. The FIRST entry
    # is the default and MUST match TTS_VOICE. Bake a voice with ``tts_build --voice <id>``.
    "TTS_VOICES": [
        {"id": "Mia", "label": "Mía", "engine": "neural"},      # es-MX, female
        {"id": "Andres", "label": "Andrés", "engine": "neural"},  # es-MX, male
        {"id": "Lupe", "label": "Lupe", "engine": "neural"},     # es-US, female
    ],
    # Host-provided AIClient adapter (D-04). The ONLY lingua-side reference to the
    # host adapter; swapping this swaps the provider with zero lingua changes.
    "AI_CLIENT": os.getenv(
        "LINGUA_AI_CLIENT", "homeschool_hub.adapters.lingua_ai.TutorAIClient"
    ),
    # Host-provided ImageClient adapter (D-04) — the ONLY lingua-side reference to the
    # host image seam; swapping this swaps the image provider with zero lingua changes.
    "IMAGE_CLIENT": os.getenv(
        "LINGUA_IMAGE_CLIENT", "homeschool_hub.adapters.lingua_image.TutorImageClient"
    ),
    # Host WorkLogSink adapter (D-04, LGA-76): mirrors a finished Spanish book into the
    # host Work Log so it lands in the charter report. Set to "" to disable mirroring.
    "WORKLOG_SINK": os.getenv(
        "LINGUA_WORKLOG_SINK", "homeschool_hub.adapters.lingua_worklog.HostWorkLogSink"
    ),
    # The work-log subject mirrored books are filed under. One definition, read by the
    # adapter, the Work Log's subject filter, and lingua's legacy redirect — so nobody
    # has to import anybody to agree on the string (HH-143).
    "WORKLOG_SUBJECT": os.getenv("LINGUA_WORKLOG_SUBJECT", "Spanish reading"),
    # Host URL name the legacy reading-log link redirects to. Named here rather than
    # hard-coded in lingua so extracting the module degrades gracefully instead of
    # raising NoReverseMatch on a route that left with the host.
    "WORKLOG_LIST_URL_NAME": os.getenv(
        "LINGUA_WORKLOG_LIST_URL_NAME", "worklog:worklog_list"
    ),
}

# ---------------------------------------------------------------------------
# Manga art generation (Replicate) — server-side only, disabled until a token
# is set. MANGA_IMAGE_MODEL is any Replicate slug; nano-banana-2 holds several
# characters consistent across panels via reference images. MANGA_REFERENCE_KEY
# is the model's input field name for reference images (varies by model).
# ---------------------------------------------------------------------------
REPLICATE_API_TOKEN = os.getenv("REPLICATE_API_TOKEN", "")
MANGA_IMAGE_MODEL = os.getenv("MANGA_IMAGE_MODEL", "google/nano-banana-2")
MANGA_REFERENCE_KEY = os.getenv("MANGA_REFERENCE_KEY", "image_input")

# ---------------------------------------------------------------------------
# Security Settings (env-driven, safe defaults)
# ---------------------------------------------------------------------------
# These default to strict/secure values. DEBUG now fails closed, so an
# environment that says nothing gets the production posture; a developer opts
# down to the permissive localhost values with DEBUG=true in their .env.
#
# Heroku deployment: Set these env vars in Heroku config:
#   DEBUG=false
#   SECURE_SSL_REDIRECT=true
#   SESSION_COOKIE_SECURE=true
#   CSRF_COOKIE_SECURE=true
#   CSRF_TRUSTED_ORIGINS=https://steadfastscholars.com,https://www.steadfastscholars.com
#   SECURE_HSTS_SECONDS=31536000
#   SECURE_HSTS_INCLUDE_SUBDOMAINS=true
#   SECURE_HSTS_PRELOAD=true
# ---------------------------------------------------------------------------

# SSL/HTTPS redirect (default: False in dev, True in prod)
# TESTING is carved out because now that DEBUG fails closed, the suite would
# otherwise inherit the production default: the test client speaks plain HTTP, so
# SecurityMiddleware would 301 every request and no view test would reach its view.
SECURE_SSL_REDIRECT = _env_bool("SECURE_SSL_REDIRECT", default=not (DEBUG or TESTING))

# When SSL redirect is enabled, trust Heroku's X-Forwarded-Proto header
# This is required for Heroku's reverse proxy / load balancer
if SECURE_SSL_REDIRECT:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Secure cookies (default: False in dev, True in prod)
SESSION_COOKIE_SECURE = _env_bool("SESSION_COOKIE_SECURE", default=not DEBUG)
CSRF_COOKIE_SECURE = _env_bool("CSRF_COOKIE_SECURE", default=not DEBUG)

# CSRF trusted origins (required in prod for cross-origin form posts)
# Example: CSRF_TRUSTED_ORIGINS=https://steadfastscholars.com,https://www.steadfastscholars.com
CSRF_TRUSTED_ORIGINS = _env_list("CSRF_TRUSTED_ORIGINS")

# HTTP Strict Transport Security (HSTS)
# Default: 0 in dev (disabled), 31536000 (1 year) in prod when explicitly set
# IMPORTANT: Only enable HSTS after confirming HTTPS works correctly
_default_hsts_seconds = 0 if DEBUG else _env_int("SECURE_HSTS_SECONDS", 0)
SECURE_HSTS_SECONDS = _env_int("SECURE_HSTS_SECONDS", _default_hsts_seconds)
SECURE_HSTS_INCLUDE_SUBDOMAINS = _env_bool("SECURE_HSTS_INCLUDE_SUBDOMAINS", default=not DEBUG)
SECURE_HSTS_PRELOAD = _env_bool("SECURE_HSTS_PRELOAD", default=not DEBUG)

# Content Security Headers
# X-Content-Type-Options: nosniff (prevent MIME sniffing attacks)
SECURE_CONTENT_TYPE_NOSNIFF = _env_bool("SECURE_CONTENT_TYPE_NOSNIFF", default=True)

# X-Frame-Options (prevent clickjacking)
X_FRAME_OPTIONS = os.getenv("X_FRAME_OPTIONS", "DENY")

# Referrer-Policy (control referrer header leakage)
SECURE_REFERRER_POLICY = os.getenv("SECURE_REFERRER_POLICY", "same-origin")

# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------
# Log to stderr so Heroku's logplex captures app output. Level is driven by
# DJANGO_LOG_LEVEL (default INFO). disable_existing_loggers=False keeps Django's
# built-in loggers working alongside this config.
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "stream": sys.stderr,
        },
    },
    "root": {
        "handlers": ["console"],
        "level": os.getenv("DJANGO_LOG_LEVEL", "INFO"),
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": os.getenv("DJANGO_LOG_LEVEL", "INFO"),
            "propagate": False,
        },
    },
}

# ---------------------------------------------------------------------------
# Storage Configuration (Static + Media)
# ---------------------------------------------------------------------------

# Toggle for R2 media storage (set USE_R2=true in production)
USE_R2 = _env_bool("USE_R2", default=False)

# Static files: Always use WhiteNoise (not R2)
STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Media files: R2 in production, local filesystem in development
if USE_R2:
    # Cloudflare R2 (S3-compatible) storage for media
    STORAGES["default"] = {
        "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
        "OPTIONS": {
            "access_key": os.getenv("R2_ACCESS_KEY_ID"),
            "secret_key": os.getenv("R2_SECRET_ACCESS_KEY"),
            "bucket_name": os.getenv("R2_BUCKET_NAME", "steadfast-scholars-media"),
            "endpoint_url": os.getenv("R2_ENDPOINT_URL"),
            "region_name": os.getenv("R2_REGION", "auto"),
            "default_acl": None,  # R2 doesn't support ACLs
            "querystring_auth": True,  # Use signed URLs for private files
            "file_overwrite": False,
        },
    }
    MEDIA_URL = ""  # URLs come from signed S3 URLs
    # Public, immutably-cached read-along assets (lingua, LGA-36 / D-16 / N-03).
    # A SEPARATE public path: querystring_auth OFF so URLs are stable + public (not
    # the default's ~1h signed URLs, wrong for reread/offline), served with an
    # immutable long cache. Private media (uploads) stays on the signed-URL
    # "default" backend above. Requires a public bucket reachable at R2_PUBLIC_DOMAIN
    # (Cloudflare r2.dev or a custom domain); without it R2 can't serve unsigned.
    # CacheControl comes from lingua.storage (single source of truth — no drift).
    from lingua.storage import IMMUTABLE_CACHE_CONTROL

    STORAGES["lingua_readalong"] = {
        "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
        "OPTIONS": {
            "access_key": os.getenv("R2_ACCESS_KEY_ID"),
            "secret_key": os.getenv("R2_SECRET_ACCESS_KEY"),
            "bucket_name": os.getenv("R2_PUBLIC_BUCKET_NAME",
                                     os.getenv("R2_BUCKET_NAME", "steadfast-scholars-media")),
            "endpoint_url": os.getenv("R2_ENDPOINT_URL"),
            "region_name": os.getenv("R2_REGION", "auto"),
            "custom_domain": os.getenv("R2_PUBLIC_DOMAIN"),  # public host -> unsigned URLs
            "default_acl": None,
            "querystring_auth": False,       # stable public URLs, not signed
            "file_overwrite": True,          # content-addressed keys: same key == same bytes
            "object_parameters": {"CacheControl": IMMUTABLE_CACHE_CONTROL},
        },
    }
    # PRIVATE child read-aloud recordings (LGA-73). CRITICAL: this MUST be a bucket
    # with NO public r2.dev / custom domain — the default+public buckets share
    # R2_BUCKET_NAME, and r2.dev exposes that whole bucket by key, so a recording
    # placed there would be world-readable unsigned despite the signed URL. So the
    # recordings store is a SEPARATE bucket (R2_PRIVATE_RECORDINGS_BUCKET) and the
    # feature stays OFF until that bucket is configured (storage.recordings_enabled()).
    _rec_bucket = os.getenv("R2_PRIVATE_RECORDINGS_BUCKET")
    if _rec_bucket:
        STORAGES["lingua_recordings"] = {
            "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
            "OPTIONS": {
                "access_key": os.getenv("R2_ACCESS_KEY_ID"),
                "secret_key": os.getenv("R2_SECRET_ACCESS_KEY"),
                "bucket_name": _rec_bucket,   # a bucket with r2.dev / public access DISABLED
                "endpoint_url": os.getenv("R2_ENDPOINT_URL"),
                "region_name": os.getenv("R2_REGION", "auto"),
                "default_acl": None,
                "querystring_auth": True,     # signed, expiring URLs only
                "file_overwrite": False,
            },
        }
else:
    # Local filesystem storage for development
    STORAGES["default"] = {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    }
    # Read-along assets: same local filesystem in dev (the "lingua/readalong/<hash>"
    # key prefix keeps them separated); the public/immutable behavior is an R2-only
    # concern. Defined so storages["lingua_readalong"] always resolves.
    STORAGES["lingua_readalong"] = {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    }
    # Private recordings: local filesystem in dev (no public exposure), so the feature
    # is available for local testing without a private R2 bucket.
    STORAGES["lingua_recordings"] = {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    }
    MEDIA_ROOT = BASE_DIR / "media"
    MEDIA_URL = "/media/"