# Generated by Django 6.0.1 on 2026-08-13 19:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0004_student_portal_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpellingWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(help_text='Week 1..36', unique=True)),
                ('unit', models.CharField(help_text="e.g. 'Foundation Repair'", max_length=100)),
                ('pattern', models.CharField(help_text="e.g. 'ai / ay'", max_length=120)),
                ('rule', models.TextField(help_text='The rule, in words a third grader can read.')),
                ('sort_buckets', models.JSONField(blank=True, default=list, help_text="Column headings for the word sort, e.g. ['ai (middle)', 'ay (end)'].")),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='SpellingPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_week', models.PositiveIntegerField(default=1)),
                ('started_on', models.DateField(default=django.utils.timezone.localdate)),
                ('is_active', models.BooleanField(default=True, help_text='Off hides spelling from her portal entirely.')),
                ('repeat_flagged_on', models.DateField(blank=True, help_text='Set when a week was repeated because too much was still in box 1.', null=True)),
                ('child', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='spelling_placement', to='students.student')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spelling_placements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SpellingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('learn', 'Learn the pattern'), ('sort', 'Word sort'), ('quiz', 'Hear-and-type quiz'), ('dictation', 'Sentence dictation')], max_length=20)),
                ('on_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('asked', models.PositiveIntegerField(default=0)),
                ('right', models.PositiveIntegerField(default=0)),
                ('missed_words', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spelling_sessions', to='students.student')),
                ('week', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='spelling.spellingweek')),
            ],
            options={
                'ordering': ['-on_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SpellingWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=40)),
                ('sentence', models.CharField(help_text='Dictation sentence. Uses only patterns taught by this week.', max_length=200)),
                ('is_heart', models.BooleanField(default=False)),
                ('tricky_part', models.CharField(blank=True, help_text='For heart words: which bit breaks the rule, e.g. "ai says /e/".', max_length=120)),
                ('sort_bucket', models.PositiveSmallIntegerField(default=0, help_text="Index into the week's sort_buckets — which column this word belongs under in the word sort. Heart words ignore it.")),
                ('order', models.PositiveIntegerField(default=0)),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='spelling.spellingweek')),
            ],
            options={
                'ordering': ['week__number', 'is_heart', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SpellingCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box', models.PositiveSmallIntegerField(default=1)),
                ('due', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('correct', models.PositiveIntegerField(default=0)),
                ('misses', models.PositiveIntegerField(default=0)),
                ('last_missed_on', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spelling_cards', to='students.student')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='spelling.spellingword')),
            ],
            options={
                'ordering': ['due', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='spellingword',
            constraint=models.UniqueConstraint(fields=('week', 'word'), name='unique_word_per_week'),
        ),
        migrations.AddConstraint(
            model_name='spellingcard',
            constraint=models.UniqueConstraint(fields=('child', 'word'), name='unique_card_per_child_word'),
        ),
    ]
