# Generated by Django 6.0.1 on 2026-08-13 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spelling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spellingword',
            name='audio_url',
            field=models.URLField(blank=True, help_text="Baked pronunciation of the word (spelling_audio). Blank falls back to the browser's own voice.", max_length=500),
        ),
        migrations.AddField(
            model_name='spellingword',
            name='audio_voice',
            field=models.CharField(blank=True, help_text='Which Polly voice was baked, so a voice change is visible.', max_length=40),
        ),
        migrations.AddField(
            model_name='spellingword',
            name='sentence_audio_url',
            field=models.URLField(blank=True, help_text='Baked reading of the dictation sentence.', max_length=500),
        ),
    ]
