"""Essentials in Writing - Grade 3 exercise content, transcribed from the
family's purchased workbook for private use. Generated from the source PDF;
sentence-editing exercises become mouse-drawing markup questions."""

LESSON_TITLES = {
    1: 'Introduction to Writing',
    2: 'Complete Subjects',
    3: 'Simple Subjects',
    4: 'Complete Predicates',
    5: 'Simple Predicates',
    6: 'Complete and Incomplete Sentences',
    7: 'Types of Sentences and Punctuation Marks',
    8: 'Common and Proper Nouns',
    9: 'Singular and Plural Nouns',
    10: 'Pronouns and Antecedents',
    11: 'Singular Possessive Nouns',
    12: 'Plural Possessive Nouns',
    13: 'More Plural Possessive Nouns (irregular plurals)',
    14: 'Adjectives',
    15: 'Action Verbs',
    16: 'Present, Past, and Future Tense Action Verbs',
    17: 'Irregular Action Verbs',
    18: 'Linking Verbs',
    19: 'Present, Past, and Future Tense Linking Verbs',
    20: 'Adverbs That Modify Verbs',
    21: 'Pronoun/Antecedent Agreement',
    22: 'Subject/Verb Agreement',
    23: 'Contractions',
    24: "Don't/Doesn't Problem",
    25: 'Adjectives in Action',
    26: 'Action Verbs in Action',
    27: 'Adverbs in Action',
    28: 'Writing Items in a Series',
    29: 'Simple and Compound Sentences',
    30: 'Incomplete Sentences (fragments)',
    31: 'Run-On Sentences',
    32: 'The Writing Process (overview)',
    33: 'The Writing Process – Brainstorm',
    34: 'The Writing Process – Organize',
    35: 'The Writing Process – Draft',
    36: 'The Writing Process – Revise',
    37: 'The Writing Process – Final Draft',
    38: 'Parts of a Paragraph (indent, opening sentence, body sentences, closing sentence)',
    39: 'Staying on Topic',
    40: 'Paragraph Practice – Brainstorm & Organize',
    41: 'Paragraph Practice – Draft',
    42: 'Paragraph Practice – Revise',
    43: 'Paragraph Practice – Final Draft',
    44: 'Expository Paragraph (intro & Brainstorm)',
    45: 'Expository Paragraph – Organize',
    46: 'Expository Paragraph – Draft',
    47: 'Expository Paragraph – Revise',
    48: 'Expository Paragraph – Final Draft',
    49: 'Expository Personal Letter (intro & Brainstorm)',
    50: 'Expository Personal Letter – Organize',
    51: 'Expository Personal Letter – Draft',
    52: 'Expository Personal Letter – Revise',
    53: 'Expository Personal Letter – Final Draft',
    54: 'Persuasive Paragraph (intro & Brainstorm)',
    55: 'Persuasive Paragraph – Organize',
    56: 'Persuasive Paragraph – Draft',
    57: 'Persuasive Paragraph – Revise',
    58: 'Persuasive Paragraph – Final Draft',
    59: 'Persuasive Personal Letter (intro & Brainstorm)',
    60: 'Persuasive Personal Letter – Organize',
    61: 'Persuasive Personal Letter – Draft',
    62: 'Persuasive Personal Letter – Revise',
    63: 'Persuasive Personal Letter – Final Draft',
    64: 'Descriptive Paragraph (intro & Brainstorm)',
    65: 'Descriptive Paragraph – Organize',
    66: 'Descriptive Paragraph – Draft',
    67: 'Descriptive Paragraph – Revise',
    68: 'Descriptive Paragraph – Final Draft',
    69: 'Imaginative Narrative – Chronological Order and Transitions',
    70: 'Imaginative Narrative – Brainstorm & Organize',
    71: 'Imaginative Narrative – Draft',
    72: 'Imaginative Narrative – Revise',
    73: 'Imaginative Narrative – Final Draft',
    74: 'Research Project – Process (overview)',
    75: 'Research Project – Brainstorm',
    76: 'Research Project – Gather Information',
    77: 'Research Project – Organize (Topics #1-#4)',
    78: 'Research Project – Draft (Topics #1-#4)',
    79: 'Research Project – Revise',
    80: 'Research Project – Final Draft',
    81: 'Research Project – Visual Presentation',
    82: 'Research Project – Writing a Bibliography',
}

# {lesson_number: [ {instructions, kind, assessment, items:[...]} ]}
EXERCISES = {
    1: [
        {
            'instructions': 'Read the prompt below and write about it. Pretend that you have just received a pen pal from a city far away. The pen pal wants to know what you are like. Describe two activities that you like to do.',
            'kind': 'paragraph-writing',
            'assessment': False,
            'items': [
                'Pretend that you have just received a pen pal from a city far away. The pen pal wants to know what you are like. Describe two activities that you like to do.',
            ],
        },
    ],
    2: [
        {
            'instructions': 'Underline the complete subject of each sentence.',
            'kind': 'sentence-editing',
            'assessment': False,
            'items': [
                'Jackie went to second grade.',
                'The little girl wanted a new friend.',
                'A boy with a blue hat sat next to her at lunch.',
                'His name was Ben.',
                'The children played together during recess.',
                'Their parents picked them up after school.',
                'The new friends waved goodbye to each other.',
            ],
        },
        {
            'instructions': 'Complete the sentences with a subject.',
            'kind': 'fill-blank',
            'assessment': False,
            'items': [
                '____________________ sat on the top shelf.',
                '____________________ swam across the lake.',
                '____________________ drank a lot of water after the race.',
                '____________________ watched two raccoons cross the road.',
            ],
        },
        {
            'instructions': 'Underline the complete subject of each sentence in the paragraph.',
            'kind': 'sentence-editing',
            'assessment': False,
            'items': [
                'A big storm blew through a small town. Strong winds destroyed windows and walls! Old buildings fell all over the city! The people in the town were sad after the storm. Then, many men with tools came. The men fixed the broken windows and walls. They built new buildings. The small town thanked the men for their help!',
            ],
        },
        {
            'instructions': 'Complete the paragraph by adding subjects where they are missing.',
            'kind': 'fill-blank',
            'assessment': False,
            'items': [
                '__________________ liked to ride his bike. ____________________ is blue with silver wheels. One day, _____________________ met a new girl in his town. _________________________________ said her name was Ella. ________________ also liked to ride her bike. _________________________ was her favorite place to ride. ________________________ rode to that place together on their bikes. __________________________ became good friends.',
            ],
        },
    ],
    3: [
        {
            'instructions': 'Underline each simple subject.',
            'kind': 'sentence-editing',
            'assessment': False,
            'items': [
                'Jackie went to second grade.',
                'The little girl wanted a new friend.',
                'A boy with a blue hat sat next to her at lunch.',
                'His name was Ben.',
                'The children played together during recess.',
                'Their parents picked them up after school.',
                'The new friends waved goodbye to each other.',
            ],
        },
        {
            'instructions': 'Complete each sentence with a simple subject.',
            'kind': 'fill-blank',
            'assessment': False,
            'items': [
                'The old _________________________ barked all day.',
                'A small _________________________ fell from the tree.',
                '_________________________ is my sister.',
                '_________________________ saw a frog at the pond.',
            ],
        },
        {
            'instructions': 'Underline each simple subject in the paragraph below.',
            'kind': 'sentence-editing',
            'assessment': False,
            'items': [
                'A big storm blew through a small town. Strong winds destroyed windows and walls! Old buildings fell all over the city! The people in the town were sad after the storm. Then, many men with tools came. The men fixed the broken windows and walls. They built new buildings. The small town thanked the men for their help!',
            ],
        },
        {
            'instructions': 'Complete the paragraph by adding simple subjects where they are missing.',
            'kind': 'fill-blank',
            'assessment': False,
            'items': [
                '_____________________________________ likes to cook. His favorite _____________________________ to make is pasta with sauce. His kind, old _____________________________ gave him the recipe. ________________ made the meal for his family. His ___________________________________ loved the meal. _________________________ is a great cook.',
            ],
        },
        {
            'instructions': 'Write sentences according to the instructions below. Circle the simple subject and underline the complete subject of each sentence.',
            'kind': 'short-answer',
            'assessment': False,
            'items': [
                'Write a sentence about a dog.',
                'Write a sentence about rain.',
                'Write a sentence about a car.',
                'Write a sentence about tennis.',
            ],
        },
    ],
    4: [
        {
            'instructions': 'Underline the complete predicate of each sentence.',
            'kind': 'sentence-editing',
            'assessment': False,
            'items': [
                'Jackie went to second grade.',
                'The little girl wanted a new friend.',
                'A boy with a blue hat sat next to her at lunch.',
                'His name was Ben.',
                'The children played together during recess.',
                'Their parents picked them up after school.',
                'The new friends waved goodbye to each other.',
            ],
        },
        {
            'instructions': 'Complete each sentence with a predicate.',
            'kind': 'fill-blank',
            'assessment': False,
            'items': [
                'A big, black raincloud _________________________.',
                'Mrs. Turner _________________________.',
                'The best store in town _________________________.',
                'Several small dogs _________________________.',
            ],
        },
        {
            'instructions': 'Underline the complete predicate of each sentence in the paragraph.',
            'kind': 'sentence-editing',
            'assessment': False,
            'items': [
                'A big storm blew through a small town. Strong winds destroyed windows and walls! Old buildings fell all over the city! The people in the town were sad after the storm. Then, many men with tools came. The men fixed the broken windows and walls. They built new buildings. The small town thanked the men for their help!',
            ],
        },
        {
            'instructions': 'Complete the paragraph by adding predicates where they are missing.',
            'kind': 'fill-blank',
            'assessment': False,
            'items': [
                'The Erikson family _____________________________________. Their three children ____________________________________________. The big sister ______________________________________________________. The middle child ___________________________________________________. Lastly, the little brother _________________________________. The family ______________________________________________________________.',
            ],
        },
    ],
    5: [
        {
            'instructions': 'Underline each simple predicate.',
            'kind': 'sentence-editing',
            'assessment': False,
            'items': [
                'Jackie went to second grade.',
                'The little girl wanted a new friend.',
                'A boy with a blue hat sat next to her at lunch.',
                'His name was Ben.',
                'The children played together during recess.',
                'Their parents picked them up after school.',
                'The new friends waved goodbye to each other.',
            ],
        },
        {
            'instructions': 'Complete each sentence with a simple predicate.',
            'kind': 'fill-blank',
            'assessment': False,
            'items': [
                'The tall stack of books ___________________________ with a loud bang.',
                'Theresa ___________________________ the security monitor for thieves.',
                'Piles of clean laundry ________________________ the sofa and the chair.',
                'The small green lizard ______________________ for bugs and other food.',
            ],
        },
        {
            'instructions': 'Underline each simple predicate in the paragraph below.',
            'kind': 'sentence-editing',
            'assessment': False,
            'items': [
                'A big storm blew through a small town. Strong winds destroyed windows and walls! Old buildings fell all over the city! The people in the town were sad after the storm. Then, many men with tools came. The men fixed the broken windows and walls. They built new buildings. The small town thanked the men for their help!',
            ],
        },
        {
            'instructions': 'Complete the paragraph by adding simple predicates where they are missing.',
            'kind': 'fill-blank',
            'assessment': False,
            'items': [
                'My dad is a math teacher. He ____________________________ a class full of students. They ___________________________________ he is a good teacher. My dad ____________________________________ their homework every night. My dad _____________________________________ teaching.',
            ],
        },
        {
            'instructions': 'Write sentences according to the instructions below. Circle the simple predicate and underline the complete predicate of each sentence.',
            'kind': 'short-answer',
            'assessment': True,
            'items': [
                'Write a sentence about the sun.',
                'Write a sentence about a desk.',
                'Write a sentence about a rat.',
                'Write a sentence about a path.',
            ],
        },
    ],
    6: [
        {
            'instructions': 'Underline the complete sentences and circle the incomplete sentences below.',
            'kind': 'sentence-editing',
            'assessment': False,
            'items': [
                'Ron built a table.',
                'The wolf howled at the moon.',
                'Traveling to South Dakota.',
                'Frog and Toad are best friends.',
                'Unpacked the Christmas lights.',
                'The boys with green shoes.',
                'French fries are delicious.',
                'Six hours on the computer.',
                'Eating waffles for breakfast.',
                'No chocolate for dogs.',
            ],
        },
        {
            'instructions': 'Correct the incomplete sentences on the lines provided. Add either a subject or a predicate.',
            'kind': 'short-answer',
            'assessment': False,
            'items': [
                'A giant black dog!',
                'Played video games all day.',
                'A heavy snowstorm.',
                'Watched a movie with his friends.',
                'Jogs every morning.',
            ],
        },
        {
            'instructions': 'Underline the incomplete sentence in the paragraph below. [Then] Correct the incomplete sentence on the line below.',
            'kind': 'sentence-editing',
            'assessment': False,
            'items': [
                'Mel has a pet rat. The rat has white fur. It is so small! Rests in a bed. It is a good rat!',
            ],
        },
        {
            'instructions': 'Underline the complete sentences and circle the incomplete sentences below.',
            'kind': 'sentence-editing',
            'assessment': False,
            'items': [
                'Went to town.',
                'We played all morning.',
                'The cats scratched the post.',
                'Walks the dog.',
                'My mom sang a song at bedtime.',
                'Cass swings back and forth.',
                'The rain fell.',
                'Jon drank the milk.',
                'Sat under the willow tree.',
                'Told a joke.',
            ],
        },
        {
            'instructions': 'Correct the incomplete sentences on the lines provided. Add either a subject or a predicate.',
            'kind': 'short-answer',
            'assessment': False,
            'items': [
                'Melted in the sun.',
                'Sent a letter.',
                'My sister.',
                'The kind doctor.',
                'Fell off the swing.',
            ],
        },
        {
            'instructions': 'Underline the incomplete sentence in the paragraph below. [Then] Correct the incomplete sentence on the line below.',
            'kind': 'sentence-editing',
            'assessment': False,
            'items': [
                'Seth is a vet. He helps sick pets. Gives shots. Seth even helps snakes! Seth is a good vet.',
            ],
        },
    ],
    7: [
        {
            'instructions': 'Match the correct punctuation mark to the type of sentence it belongs with.',
            'kind': 'multiple-choice',
            'assessment': False,
            'items': [
                '______ Declarative',
                '______ Interrogative',
                '______ Exclamatory',
                '______ Imperative',
                'A. Question Mark (?)',
                'B. Period (.) OR Exclamation Point (!)',
                'C. Period (.)',
                'D. Exclamation Point (!)',
            ],
        },
        {
            'instructions': 'Write whether each sentence is declarative, interrogative, exclamatory, or imperative.',
            'kind': 'short-answer',
            'assessment': False,
            'items': [
                'Where is Mom?',
                'Go home right now!',
                'This cake is the best!',
                'Spot is my dog.',
                'Drink the water.',
                'Jen is tall.',
                'How are you doing today?',
                'I am so happy!',
            ],
        },
        {
            'instructions': 'The sentences have mistakes in capitalization and punctuation. Rewrite the sentences correctly.',
            'kind': 'sentence-editing',
            'assessment': False,
            'items': [
                'is this your hat',
                'come back home',
                'the boys swing at the park',
                'cal built a tall fort yesterday',
                'this is so fun',
                'go to bed',
            ],
        },
        {
            'instructions': 'Write sentences according to the instructions below.',
            'kind': 'paragraph-writing',
            'assessment': True,
            'items': [
                'Write an imperative sentence about a dog.',
                'Write an exclamatory sentence about a bug.',
                'Write an interrogative sentence about a jacket.',
                'Write a declarative sentence about the weather.',
            ],
        },
    ],
    8: [
        {
            'instructions': 'Underline each common noun.',
            'kind': 'sentence-editing',
            'assessment': False,
            'items': [
                'water bottle',
                'Jana',
                'Paris',
                'fence',
                'Emmett',
                'Mrs. Robinson',
                'San Francisco',
                'kindness',
                'tulips',
                'Arizona',
                'spaghetti',
                'Spot',
                'Nobel Prize',
                'backpack',
                'mice',
            ],
        },
        {
            'instructions': 'Circle each proper noun.',
            'kind': 'sentence-editing',
            'assessment': False,
            'items': [
                'Bob Dylan is from the United States.',
                'He was born in a city called Duluth.',
                'Bob wrote many songs.',
                'He went to New York to sing his songs.',
                'He won the Medal of Freedom for his songs.',
                'Bob Dylan also won the Nobel Prize.',
            ],
        },
        {
            'instructions': 'Fill in the blanks with common nouns.',
            'kind': 'fill-blank',
            'assessment': False,
            'items': [
                'The _______________________________________ went home. (Person)',
                'The _________________________________ rolled down the hill. (Thing)',
                'The dog went to the _____________________________________. (Place)',
                'The _____________________________________ hits the drums. (Person)',
            ],
        },
        {
            'instructions': 'Fill in the blanks with proper nouns.',
            'kind': 'fill-blank',
            'assessment': False,
            'items': [
                'We went to ___________________________________________. (Place)',
                'I have a dog named _____________________________________. (Thing)',
                '__________________________________________ went to class. (Person)',
                '____________________________________________ is a big city. (Place)',
            ],
        },
        {
            'instructions': 'Underline each common noun and circle each proper noun.',
            'kind': 'sentence-editing',
            'assessment': False,
            'items': [
                'Glen walked his dog in France.',
                'Kat and Ted played all day.',
                'Fuzz is the best cat!',
                'Is this map from Canada?',
                'Seth plays soccer.',
                'Ben called his mom from Texas.',
            ],
        },
        {
            'instructions': 'Underline each common noun and circle each proper noun.',
            'kind': 'sentence-editing',
            'assessment': False,
            'items': [
                'Beth has a friend named Kim. Kim has long hair. Kim comes from a town in Alaska. Beth has never been to Alaska. Beth is from Maine. Beth writes her friend letters from Maine. Beth would love to visit Kim in Alaska!',
            ],
        },
        {
            'instructions': 'Rewrite the paragraph below and replace the underlined common nouns with proper nouns that refer to specific people, places, things, or ideas.',
            'kind': 'paragraph-writing',
            'assessment': False,
            'items': [
                'A boy moved to a city. A girl, his sister, liked the city, but the boy wished his family had never moved from another town. One day, the boy saw a store with a "Help Wanted" sign in the window. He went inside and talked to a woman, the owner. She gave the boy a job, and he felt better about being in the city. (Underlined common nouns to replace: boy, city, girl, city, boy, town, boy, store, woman, boy, city.)',
            ],
        },
        {
            'instructions': 'Write sentences according to the instructions below. Use a proper noun in each sentence and underline it.',
            'kind': 'paragraph-writing',
            'assessment': False,
            'items': [
                'Write a sentence about where you are from.',
                'Write a sentence about your best friend.',
                'Write a sentence about a sibling.',
                'Write a sentence about a pet.',
            ],
        },
    ],
    9: [
        {
            'instructions': 'Underline the singular nouns and circle the plural nouns below.',
            'kind': 'sentence-editing',
            'assessment': False,
            'items': [
                'Kelly jumped over the lines.',
                'The woman sang songs.',
                'The books fell from the shelf.',
                'Jim writes with the pen.',
                'The cats sleep on the steps.',
                'Can the girls swim in the lake?',
                'Jenna plays the drums.',
                'Birds make the best pets!',
                'Cass takes care of the horses.',
                'The cups are full.',
            ],
        },
        {
            'instructions': 'Fill in the blank with the plural of the indicated noun.',
            'kind': 'fill-blank',
            'assessment': False,
            'items': [
                'The ______________________________________ sit on the fence. (bird)',
                'Hal made blue clay _______________________________________. (cup)',
                'My cat is stuck in the ___________________________________! (branch)',
                'A dad got gifts for his _____________________________________. (girl)',
                'The _________________________________________ ring bells. (church)',
                'My ____________________________________________ are cold! (hand)',
            ],
        },
        {
            'instructions': 'Write the plural form of each noun in the boxes below.',
            'kind': 'fill-blank',
            'assessment': False,
            'items': [
                'forest -> ______',
                'boss -> ______',
                'six -> ______',
                'photo -> ______',
                'river -> ______',
                'person -> ______',
                'coat -> ______',
                'dish -> ______',
                'trench -> ______',
                'table -> ______',
            ],
        },
        {
            'instructions': 'Underline the singular nouns and circle the plural nouns in the paragraph below.',
            'kind': 'sentence-editing',
            'assessment': False,
            'items': [
                'Emilio has two birds. The birds were presents from his parents. One bird is Chipper. The other bird is Airplane. Chipper has bright feathers, and Airplane has a long beak. Emilio feeds his birds in little bowls. The birds drink water from bottles. Emilio takes care of Chipper and Airplane and loves his birds very much.',
            ],
        },
        {
            'instructions': 'Write the plural form of each noun in the boxes below.',
            'kind': 'fill-blank',
            'assessment': False,
            'items': [
                'arm -> ______',
                'wish -> ______',
                'actor -> ______',
                'class -> ______',
                'stream -> ______',
                'flower -> ______',
                'woman -> ______',
                'beach -> ______',
                'kitten -> ______',
                'block -> ______',
            ],
        },
        {
            'instructions': 'A singular noun refers to one person, place, thing, or idea. A plural noun refers to more than one person, place, thing, or idea. The paragraph below contains errors in plural spellings of nouns. Rewrite the paragraph below, spelling each of the plural nouns correctly.',
            'kind': 'paragraph-writing',
            'assessment': False,
            'items': [
                'I play with many kides in my town. We play gamess like jump rope and tag. Beth is the best tagger! She once tagged two girles at the same time! We also draw boxs on the sidewalk and play hopscotch. After playing, we like to rest on the benchs at the park. Playing with friendes is fun!',
            ],
        },
    ],
    10: [
        {
            'instructions': 'A pronoun is a word that can be used in place of a noun. The word that the pronoun replaces is called an antecedent. Model example: "Tyrone made a cake." → "He made a cake." Underline the pronouns. (Reference List of Pronouns provided: I, me, my, you, your, he, they, them, their, our, we, us, him, his, she, her, it, its.)',
            'kind': 'sentence-editing',
            'assessment': False,
            'items': [
                'Jim sang a song. It was so pretty!',
                'Kelly jumped on the bed. She was happy.',
                'Harry had a scarf. Les gave it to him.',
                'Jess tells us about her bunny. We think it is cute!',
                'Liv spilled the tea on me. I was upset.',
            ],
        },
        {
            'instructions': 'Circle the antecedents. (Reference List of Pronouns provided: I, me, my, you, your, he, they, them, their, our, we, us, him, his, she, her, it, its.)',
            'kind': 'sentence-editing',
            'assessment': False,
            'items': [
                'Ken drove home. He parked the car.',
                'Elle came to the party. She wore a red dress.',
                'The dog jumped on my lap. It fell asleep.',
                'Jen and Ness play the drums. They are so talented!',
                'Al and I went to the store. We got bread.',
            ],
        },
        {
            'instructions': 'A pronoun is a word that can be used in place of a noun. The word that the pronoun replaces is called an antecedent. Model example: "Jess played the drums." → "She played the drums." Rewrite the sentences and replace the underlined nouns with the correct pronouns. (Reference List of Pronouns provided: I, me, my, you, your, he, they, them, their, our, we, us, him, his, she, her, it, its.)',
            'kind': 'sentence-editing',
            'assessment': False,
            'items': [
                "Gal's best friend is Gal's sister.",
                "Hal worked on Hal's project all night.",
                'Mrs. Tally told Jessica that Jessica was pretty.',
                "Dev and Caleb saved Dev and Caleb's money.",
                'Bri and I want Lindsey to join Bri and me.',
                'I have a book, and I took the book to the park.',
            ],
        },
        {
            'instructions': 'A pronoun is a word that can be used in place of a noun. The word that the pronoun replaces is called an antecedent. Model example: "Cal and I sang for our family." → "We sang for them." Underline the pronouns in the paragraph below. (Reference List of Pronouns provided: I, me, my, you, your, he, they, them, their, our, we, us, him, his, she, her, it, its.)',
            'kind': 'sentence-editing',
            'assessment': False,
            'items': [
                'Callie and John are siblings. They are my friends, and they both play the piano. Callie likes to play rag music. She plays so fast! John likes to play songs by Brahms. His music is pretty. Callie and John play songs for us. We love to hear them play!',
            ],
        },
        {
            'instructions': 'Circle the antecedents in the paragraph below. (Reference List of Pronouns provided: I, me, my, you, your, he, they, them, their, our, we, us, him, his, she, her, it, its.)',
            'kind': 'sentence-editing',
            'assessment': False,
            'items': [
                'Micah has two little bunnies. They are named Wes and Mollie, and they are his pets. Wes has a pink nose. He wiggles it. Mollie has a fuzzy white tail. She is so cute! They live in a small hutch. It keeps Wes and Mollie safe. Micah loves his pet bunnies so much!',
            ],
        },
        {
            'instructions': 'A pronoun is a word that can be used in place of a noun. The word that the pronoun replaces is called an antecedent. Model example: "Elle held the cat." → "She held it." Read the paragraph below. Rewrite the paragraph, replacing the underlined nouns with the correct pronouns.',
            'kind': 'sentence-editing',
            'assessment': False,
            'items': [
                'Beth has a bell. Grandma gave the bell to Beth. The bell is gold. Beth rings the bell every afternoon. Beth loves the bell.',
            ],
        },
        {
            'instructions': 'A pronoun is a word that can be used in place of a noun. The word that the pronoun replaces is called an antecedent. Read the paragraph below. Which is missing? (choices: pronouns / antecedents) Read the paragraph again below. Which is missing? (choices: pronouns / antecedents)',
            'kind': 'multiple-choice',
            'assessment': False,
            'items': [
                'Paragraph A (Which is missing? pronouns / antecedents): "Easton and Jay played basketball together. Easton and Jay practiced every day together with the team, and Easton and Jay also practiced alone. Easton and Jay wanted to do Easton and Jay\'s very best. Easton and Jay\'s coach noticed Easton and Jay\'s hard work. Easton and Jay\'s coach made Easton and Jay starters for the big game. Easton and Jay were so excited! Easton and Jay knew Easton and Jay\'s extra practice had paid off."',
                'Paragraph B (Which is missing? pronouns / antecedents): "They played basketball together. They practiced every day together with the team, and they also practiced alone. They wanted to do their very best. Their coach noticed their hard work. Their coach made them starters for the big game. They were so excited! They knew their extra practice had paid off."',
            ],
        },
        {
            'instructions': 'A pronoun is a word that can be used in place of a noun. The word that the pronoun replaces is called an antecedent. Rewrite the paragraph from the previous page, using both antecedents and pronouns correctly.',
            'kind': 'paragraph-writing',
            'assessment': False,
            'items': [
                "(Source paragraph is the Easton and Jay basketball paragraph from workbook p.39; student rewrites it mixing antecedents and pronouns so neither is missing — e.g., beginning with the noun antecedent 'Easton and Jay' then switching to the pronoun 'They' in following sentences.)",
            ],
        },
    ],
    11: [
        {
            'instructions': 'A possessive noun shows ownership or relationship between two nouns. To make a singular noun show possession, add \'s to the end. Model example: "The bike of the boy......" → "The boy\'s bike ......" Use possessive nouns to shorten the phrases.',
            'kind': 'short-answer',
            'assessment': False,
            'items': [
                'the box of the crayon',
                'the price of the toy',
                'the wheel of the truck',
                'the page of the book',
                'the collar of the dress',
                'the bed of the cat',
                'the light of the lamp',
                'the shape of the cloud',
                'the hair of the woman',
                'the slobber of the dog',
            ],
        },
        {
            'instructions': 'A possessive noun shows ownership or relationship between two nouns. To make a singular noun show possession, add \'s to the end. Model example: "I rode the skateboard. The skateboard belonged to my friend." → "I rode my friend\'s skateboard." Combine the sentences using a singular possessive noun.',
            'kind': 'short-answer',
            'assessment': False,
            'items': [
                'The fridge broke. The fridge belonged to my family.',
                'The game crashed. The game belonged to the computer.',
                'The book was finished. The book belonged to the author.',
                'The fur was black. The fur belonged to the panther.',
                'The garden was colorful. The garden belonged to the man.',
                'Liam wanted to go to the dance. The dance belonged to the school.',
                'The cloud blocked the sun. The cloud belonged to the sky.',
            ],
        },
    ],
    12: [
        {
            'instructions': 'A possessive noun shows ownership or relationship between two nouns. To make a plural noun that ends in -s possessive, add only an apostrophe ( \' ) to the end. Model example: "The animals of the farmers......" → "The farmers\' animals ......" Use possessive nouns to shorten the phrases.',
            'kind': 'short-answer',
            'assessment': False,
            'items': [
                'the homes of the families',
                'the hisses of the cats',
                'the colors of the leaves',
                'the pictures of the books',
                'the meeting of the leaders',
                'the secret of the caves',
                'the speed of the horses',
                'the boats of the rivers',
                'the smell of the clothes',
                'the shape of the numbers',
            ],
        },
        {
            'instructions': 'A possessive noun shows ownership or relationship between two nouns. To make a plural noun that ends in -s possessive, add only an apostrophe ( \' ) to the end. Model example: "The tires were flat. The tires belong to the trucks." → "The trucks\' tires were flat." Combine the sentences using a plural possessive noun.',
            'kind': 'short-answer',
            'assessment': False,
            'items': [
                'The powers were amazing. The powers belonged to the heroes.',
                'The light twinkled in the sky. The light belonged to the stars.',
                'The bread smelled delicious. The bread belonged to the bakers.',
                'The cubs searched for blueberries. The cubs belonged to the bears.',
                'The fish leaped out of the water. The fish belonged to the rivers.',
                'The voices drifted through the air. The voices belonged to the singers.',
                'The leaves dropped to the ground. The leaves belonged to the trees.',
            ],
        },
    ],
    13: [
        {
            'instructions': 'A possessive noun shows ownership or relationship between two nouns. To make a plural noun that does not end in -s possessive, add \'s to the end. Model example: "The toys of the children......" → "The children\'s toys ......" Use possessive nouns to shorten these phrases.',
            'kind': 'short-answer',
            'assessment': False,
            'items': [
                'the beaks of the geese',
                'the antlers of the deer',
                'the carts of the oxen',
                'the jobs of the women',
                'the edges of the teeth',
                'the homes of the moose',
                'the legs of the shrimp',
                'the ears of the sheep',
                'the whiskers of the mice',
                'the shouts of the people',
            ],
        },
        {
            'instructions': 'A possessive noun shows ownership or relationship between two nouns. To make a plural noun that does not end in -s possessive, add \'s to the end. Model example: "The edges were sharp. The edges belonged to the teeth." → "The teeth\'s edges were sharp." Combine the sentences using a plural possessive noun.',
            'kind': 'short-answer',
            'assessment': False,
            'items': [
                'The sirens were loud. The sirens belonged to the policemen.',
                'The tank was dirty. The tank belonged to the fish.',
                'The meadow was sunny. The meadow belonged to the deer.',
                'The concert was popular. The concert belonged to the women.',
                'The feathers were everywhere. The feathers belonged to the geese.',
                'The wool was soft. The wool belonged to the sheep.',
                'The pets ran loose. The pets belonged to the children.',
            ],
        },
    ],
    14: [
        {
            'instructions': 'An adjective changes or describes a noun in a sentence. Adjectives are tools authors use to help readers see, smell, taste, hear, feel, and experience what is described. Model example: "The spicy chips burned my mouth!" Underline the adjectives in the sentences. (Side note printed on page: "Adjectives add greater detail to nouns and help the reader see a better picture in their mind.")',
            'kind': 'sentence-editing',
            'assessment': False,
            'items': [
                'The quick runner won the race!',
                'The noisy dogs barked during the night.',
                'My dad carved the giant turkey.',
                'Heavy rain pelted us as we ran for cover.',
                'Flowery dresses filled the window.',
                'We looked up at the fluffy clouds.',
                'Sleepy students struggled to keep their eyes open.',
                'Yellow tulips waved in the gentle wind.',
                'Bright lamps covered the room in light.',
                'The red fox slept in the tall grass.',
                'Huge waves crashed in the blue sea!',
                'Soft snow fell from the sky.',
            ],
        },
        {
            'instructions': 'An adjective changes or describes a noun in a sentence. Adjectives are tools authors use to help readers see, smell, taste, hear, feel, and experience what is described. Model example: "My grandma made a cake that tastes amazing!" Complete each sentence with an adjective. NOTE: Avoid writing verbs on the lines. Incorrect: The children are playing. Correct: The children are upset.',
            'kind': 'fill-blank',
            'assessment': False,
            'items': [
                'The roads are _________.',
                'My friends are _________.',
                '_________ berries grow on the bushes in the forest.',
                'The schoolhouse is _________.',
                'The _________ building is the library.',
                'I am _________.',
                'The concert played _________ music.',
                'You are _________.',
                'A(n) _________ dog suddenly blocked our path.',
                'My mother is a(n) _________ person.',
            ],
        },
        {
            'instructions': 'Underline the adjectives in the paragraph below.',
            'kind': 'sentence-editing',
            'assessment': False,
            'items': [
                "Emily has a little bird. The little bird is yellow. It sings pretty songs, and it says funny things. Emily lets the bird fly around her big bedroom. It sleeps in a tiny, purple cage. The little bird is Emily's favorite pet.",
            ],
        },
        {
            'instructions': 'Underline the adjectives in the paragraph below.',
            'kind': 'sentence-editing',
            'assessment': False,
            'items': [
                'Seth loves to build. He makes strong wooden tables and tall desks. Seth built a new shelf for a friend named Jennifer. She said it was a wonderful gift! Seth is a great builder.',
            ],
        },
        {
            'instructions': 'Rewrite the paragraph below. Add at least one adjective to each sentence.',
            'kind': 'paragraph-writing',
            'assessment': False,
            'items': [
                'I ate my lunch at a table. I saw a girl across the room. She wore a hat and boots. The girl was eating a sandwich by herself. Finally, I left my table and crossed the room to her. I asked her if she wanted to sit at my table. The girl said yes. Now, we are friends.',
            ],
        },
    ],
    15: [
        {
            'instructions': 'Circle each action verb.',
            'kind': 'sentence-editing',
            'assessment': False,
            'items': [
                'A rat lived in Paris.',
                'He loved the food in the city.',
                'He dreamed of kitchens and restaurants.',
                'His father disliked this dream.',
                'Chefs worked in kitchens, not rats.',
                'A human chef helped the rat.',
                'The rat inspired the human.',
                'Together, they cooked amazing food.',
                'The human chef also found love!',
                'The rat and human made a good team.',
            ],
        },
        {
            'instructions': 'Circle the action verb in each row of words.',
            'kind': 'sentence-editing',
            'assessment': False,
            'items': [
                'leash walk fur path',
                'desk marker scribble workbook',
                'knife glass chew placemat',
                'phone purse number call',
                'watch game glasses hat',
                'music keys play cord',
            ],
        },
        {
            'instructions': 'Complete each sentence with an action verb.',
            'kind': 'fill-blank',
            'assessment': False,
            'items': [
                'Cats and dogs ______ from their food bowls.',
                'The group of students ______ into the bus.',
                'Dark, thick clouds ______ the sun.',
                'The children ______ doorbells on Halloween.',
                'Lila ______ toward the finish line.',
                'The doctor ______ down the hall toward the patient.',
                'Sarah and Caleb ______ water after playing outside.',
                'My dad ______ five fish yesterday.',
                'Chefs ______ desserts of all kinds at the restaurant.',
            ],
        },
        {
            'instructions': 'Circle each action verb in the paragraph below.',
            'kind': 'sentence-editing',
            'assessment': False,
            'items': [
                'Salem plays on a soccer team. He practices after class every day. He and his friend Zak kick the ball back and forth. Salem scores goals at the games. Zak scores goals too! Everyone cheers in the stands. Their team lifts them in the air. The team won the soccer match!',
            ],
        },
        {
            'instructions': 'Complete the paragraph with action verbs.',
            'kind': 'fill-blank',
            'assessment': False,
            'items': [
                'Jen and Max ______ at a coffee shop. Jen was ______ a book when Max came up and ______ to her. Max ______ Jen on a date. Years later, Jen and Max ______ each other. They ______ in a little house by the sea.',
            ],
        },
        {
            'instructions': 'Write sentences according to the instructions below. Underline the action verb in each sentence.',
            'kind': 'short-answer',
            'assessment': False,
            'items': [
                'Write a sentence about what a tiger does.',
                'Write a sentence about what a fireman does.',
                'Write a sentence about what a bird does.',
                'Write a sentence about what a doctor does.',
            ],
        },
    ],
    16: [
        {
            'instructions': 'Write whether the underlined verbs are in the present tense, the past tense, or the future tense.',
            'kind': 'multiple-choice',
            'assessment': False,
            'items': [
                'Cass peeled the orange slowly. (underlined verb: peeled) — Present OR Past OR Future?',
                'The panda sleeps all night. (underlined verb: sleeps) — Present OR Past OR Future?',
                'We will go to the store tomorrow. (underlined verb: will go) — Present OR Past OR Future?',
                'Sam often talks loudly. (underlined verb: talks) — Present OR Past OR Future?',
                'The bulky cow chews the grass. (underlined verb: chews) — Present OR Past OR Future?',
                'Mom will send the letter. (underlined verb: will send) — Present OR Past OR Future?',
                'The writer typed on the computer. (underlined verb: typed) — Present OR Past OR Future?',
                'My sister cries after the movie. (underlined verb: cries) — Present OR Past OR Future?',
                'I will try my best at the game! (underlined verb: will try) — Present OR Past OR Future?',
                'The puppy sniffed my shoes. (underlined verb: sniffed) — Present OR Past OR Future?',
            ],
        },
        {
            'instructions': 'Rewrite the sentences and change the present tense action verbs to the tense indicated.',
            'kind': 'short-answer',
            'assessment': False,
            'items': [
                'The poodle barks at the man. (Past:)',
                'Water spills from the glass. (Future:)',
                'Mia plays the piano. (Past:)',
                'Trees sway in the wind. (Future:)',
                'The picture frame shatters. (Past:)',
                'The boy talks to his teacher. (Future:)',
            ],
        },
        {
            'instructions': 'Write whether the underlined verbs are in the present tense, the past tense, or the future tense.',
            'kind': 'multiple-choice',
            'assessment': False,
            'items': [
                'The fox will dig a den. (underlined verb: will dig) — Present OR Past OR Future?',
                'She tended the sheep. (underlined verb: tended) — Present OR Past OR Future?',
                'Bees buzz in the garden. (underlined verb: buzz) — Present OR Past OR Future?',
                'The boy strummed the instrument. (underlined verb: strummed) — Present OR Past OR Future?',
                'Tad marches to the beat. (underlined verb: marches) — Present OR Past OR Future?',
                'Mark will give a gift to his mom. (underlined verb: will give) — Present OR Past OR Future?',
                'Kites soar in the sky. (underlined verb: soar) — Present OR Past OR Future?',
                'My sister will like the movie. (underlined verb: will like) — Present OR Past OR Future?',
                'The toy spins around like a top. (underlined verb: spins) — Present OR Past OR Future?',
                'The waitress dropped the tray. (underlined verb: dropped) — Present OR Past OR Future?',
            ],
        },
        {
            'instructions': 'Rewrite the sentences and change the present tense action verbs to the tense indicated.',
            'kind': 'short-answer',
            'assessment': False,
            'items': [
                'Sam steams a cup of milk. (Past:)',
                'The sandcastle crumbles. (Future:)',
                'A snail moves slowly. (Past:)',
                'Wolves howl at the moon. (Future:)',
                'Ezra tosses the ball to Jerry. (Past:)',
                'I make a cake for the party. (Future:)',
            ],
        },
    ],
    17: [
        {
            'instructions': 'Rewrite the sentences and change the present tense verbs to past tense verbs.',
            'kind': 'short-answer',
            'assessment': False,
            'items': [
                'The rat runs into the box.',
                'Lilies grow in the summer.',
                'The swimmer drinks water from a bottle.',
                'The lioness eats antelope for dinner.',
                'Mrs. Zusak teaches piano lessons.',
                'My older sister reads so many books!',
                'In the autumn, leaves fall to the ground.',
                'Dad says I have to clean the car.',
            ],
        },
        {
            'instructions': 'Write sentences according to the instructions below. Underline the action verb in each sentence. You can use regular or irregular action verbs',
            'kind': 'short-answer',
            'assessment': False,
            'items': [
                'Write a sentence about a horse. Use a present tense verb.',
                'Write a sentence about your dad. Use a past tense verb.',
                'Write a sentence about two dogs. Use a future tense verb.',
                'Write a sentence about a tree. Use a past tense verb.',
                'Write a sentence about yourself. Use a future tense verb.',
            ],
        },
    ],
    18: [
        {
            'instructions': 'Underline each linking verb.',
            'kind': 'sentence-editing',
            'assessment': False,
            'items': [
                'I am tired today.',
                'Jax and Luna were sad because of the rain.',
                'The fox was red and white.',
                'Andrea is a great singer!',
                'We were excited for the play.',
                'Hamsters are small rodents.',
                'Is this your house?',
            ],
        },
        {
            'instructions': 'Circle each linking verb. Cross out words that are not linking verbs.',
            'kind': 'sentence-editing',
            'assessment': False,
            'items': [
                'is',
                'live',
                'hold',
                'begin',
                'were',
                'turn',
                'run',
                'are',
                'have',
                'drink',
                'look',
                'ate',
                'sail',
                'beg',
                'am',
                'show',
                'was',
                'make',
            ],
        },
        {
            'instructions': 'Complete each sentence with a linking verb.',
            'kind': 'fill-blank',
            'assessment': False,
            'items': [
                'My puppy ______ so tiny!',
                'Kendra and Sam ______ best friends.',
                'I ______ tired after a long day.',
                'Mom said she ______ alone yesterday.',
                'You ______ so funny at the talent show!',
                'The art at the museum ______ beautiful.',
                'I ______ tall as a child.',
                'Lex and Tris ______ happy I was home.',
                '______ this your hat?',
                'I ______ so excited for my trip!',
            ],
        },
        {
            'instructions': 'Underline each linking verb in the paragraph below.',
            'kind': 'sentence-editing',
            'assessment': False,
            'items': [
                'My mom is a vet. She helps dogs and cats when they are sick. She was in school for a very long time. My family and I were so happy for her when she finished! Now, she has her own clinic. We are all so proud of her!',
            ],
        },
        {
            'instructions': 'Complete each sentence with a linking verb in the paragraph below.',
            'kind': 'fill-blank',
            'assessment': False,
            'items': [
                'Johnny ______ my older brother. He ______ tall and slim. His eyes ______ brown, and his hair ______ blonde. Johnny ______ also a great swimmer! He and I ______ best friends. I ______ so happy he ______ my brother.',
            ],
        },
    ],
    19: [
        {
            'instructions': "Write whether the underlined verbs are in the present tense, the past tense, or the future tense. (The linking verb in each sentence is underlined; student writes 'present tense', 'past tense', or 'future tense' on the line.)",
            'kind': 'short-answer',
            'assessment': False,
            'items': [
                'I am sorry for being late.',
                'Cass was upset with me.',
                'This year will be great!',
                'June is shorter than Kelly.',
                'I will be a scientist one day',
                'You are so funny!',
                'I was too excited to sleep.',
                'The ducks are swimming.',
                'Dan and Phil will be at my party!',
                'They were at the play.',
            ],
        },
        {
            'instructions': 'Rewrite the sentences and change the present tense linking verbs to the tense indicated.',
            'kind': 'short-answer',
            'assessment': False,
            'items': [
                'His hair is brown. (Past)',
                'All the songs are pretty. (Future)',
                'I am too cold to go outside. (Past)',
                'The color of the frosting is blue. (Future)',
                'Cars are big and fast. (Past)',
                'I am kind and friendly. (Future)',
            ],
        },
    ],
    20: [
        {
            'instructions': 'Underline each adverb in the sentences.',
            'kind': 'sentence-editing',
            'assessment': False,
            'items': [
                'The fox quickly runs to his den.',
                'My uncle snores loudly.',
                'Sal clumsily dropped the dishes.',
                'The door slammed suddenly.',
                'Susan and Todd happily made grilled cheese sandwiches.',
                'Snow softly drifts to the ground.',
                'The girl calmly reads all afternoon.',
                'The sun brightly shines on the grass.',
                'Waves crashed powerfully in the sea.',
                'The puppy lazily lies in the sun all afternoon.',
            ],
        },
        {
            'instructions': 'Complete each sentence using one of the adverbs listed. [Provided word bank: well, boldly, perfectly, carefully, quietly, weakly, easily, rarely, loudly, softly, poorly, politely]',
            'kind': 'fill-blank',
            'assessment': False,
            'items': [
                'Darnell ________ asked for a napkin.',
                'Emmy ________ counted her allowance.',
                'My mom and I cheered ________ during the concert.',
                'The general ________ led his army into battle.',
                'Speaking in public does not come ________ to me.',
                "Kira's mom ________ buys junk food.",
                'Enrique spelled all the words ________.',
                'The robbers crept into the mansion ________.',
                "Our family's dog ________ snored as she slept.",
            ],
        },
        {
            'instructions': 'Underline each adverb in the sentences.',
            'kind': 'sentence-editing',
            'assessment': False,
            'items': [
                'Deanne quickly answered the question.',
                'The baby slowly crawled up the steps.',
                'Cars suddenly rolled into sight.',
                'The vacuum steadily cleaned the carpets.',
                'Students read their books closely.',
                'I know a girl who plays the tuba well.',
                'The pride of lions quietly followed their prey.',
                'My family frantically cleaned the house.',
            ],
        },
        {
            'instructions': 'Underline each adverb in the paragraph.',
            'kind': 'sentence-editing',
            'assessment': False,
            'items': [
                'The day of the big test had finally arrived. Students sat down at their desks, nervously watching the teacher as she handed out booklets. The students had waited for this day anxiously, and now, it was here. Would they pass or fail? Hopefully, they would pass!',
            ],
        },
        {
            'instructions': 'Complete each sentence with your own adverb.',
            'kind': 'fill-blank',
            'assessment': False,
            'items': [
                'The stray cats ________ hissed at the group of rats.',
                'Kaden and his dog walked ________ around the block.',
                'Teachers ________ prepared for their meeting.',
                'Amira ________ counted her money.',
                'A tornado ________ destroyed a farmhouse.',
            ],
        },
        {
            'instructions': 'Complete the paragraph with your own adverbs.',
            'kind': 'fill-blank',
            'assessment': False,
            'items': [
                'I went to the park. The sun shone ________. Then, a boy jumped off the swing ________. He ________ walked over to me. He asked if I wanted to be his friend! I said yes! Now we ________ play at the park every day.',
            ],
        },
    ],
    21: [
        {
            'instructions': 'Choose the pronoun that agrees with the underlined antecedent. (Two pronoun options are given in parentheses in each sentence; the antecedent is underlined - student marks the correct pronoun.)',
            'kind': 'sentence-editing',
            'assessment': False,
            'items': [
                'The library closes (his / its) doors at 8:00.',
                'Flowers drop (their / its) petals.',
                'Amos sweeps (his / her) kitchen.',
                'The bright sun shines (their / its) rays.',
                'Georgia gathers (his / her) books.',
                'The superheroes grabbed (their / his) shields.',
                'The crew members swung (his / their) wrecking ball.',
                'Kittens snuggled in (its / their) basket.',
                "After Jared's piano recital, (she / he) hugged (her / his) grandparents.",
                'The brothers played (his / their) guitars like experts.',
            ],
        },
        {
            'instructions': 'Complete the sentences with pronouns. Use pronouns that agree with (or match) the underlined antecedents. [Provided List of Pronouns: I, me, my, you, your, he, they, them, their, our, we, us, him, his, she, her, it, its]',
            'kind': 'fill-blank',
            'assessment': False,
            'items': [
                'Michael snuggled under the covers and listened to his mother. ________ told Michael a story.',
                'I met two firemen at the store today. ________ names were Jose and Nicholas.',
                'Donald saw several ducks at the park. Donald broke off parts of his sandwich and fed the bits to ________.',
                'My sister and I saved twenty dollars. Then, my sister and I spent ________ money on a new game.',
                'I love my Uncle Jerry. ________ rides a motorcycle!',
                'Mom and Dad gave Emma a new book for Christmas. Emma read ________ right away!',
            ],
        },
        {
            'instructions': "Choose the pronoun that agrees with the underlined antecedent. (Helper tip printed: 'Try reading each sentence out loud. Which pronoun sounds the best?')",
            'kind': 'sentence-editing',
            'assessment': False,
            'items': [
                'The bee flapped (its / their) wings.',
                'The men lifted (their / its) hats.',
                'Gemma gave (his / her) mom a hug.',
                'Curt and Max washed (their / his) dog.',
                'My dad dropped (his / her) shovel.',
                'Jim and Less sent (their / his) sister a letter.',
                'The door came off (his / its) hinges.',
                'The girls saw (her / their) friends at the park.',
                'Tess gave her mom and dad (her / their) money back.',
                'Dennis raised (his / him) hand.',
            ],
        },
        {
            'instructions': 'Complete the sentences with pronouns. Use pronouns that agree with (or match) the underlined antecedents. [Provided List of Pronouns: I, me, my, you, your, he, they, them, their, our, we, us, him, his, she, her, it, its]',
            'kind': 'fill-blank',
            'assessment': False,
            'items': [
                'The little boy called ________ mother.',
                'I went to a music concert and went backstage to meet the band members. I got to shake ________ hands!',
                'Cass tripped on the sidewalk and dropped his books! Now all ________ covers are scratched!',
                'My sister was crying, so I gave ________ a tissue.',
                'Fred, George, and Ginny are my cousins. ________ are a wild bunch!',
                "I have two neighbors, Andy and Sid. Andy is ________ friend, but Sid doesn't like ________.",
            ],
        },
    ],
    22: [
        {
            'instructions': 'Circle the verb that agrees with the subject.',
            'kind': 'sentence-editing',
            'assessment': False,
            'items': [
                'Marie (attends / attend) college in Warsaw.',
                'She (studies / study) physics and chemistry.',
                'Marie and her sister (moves / move) to Paris.',
                'Then, Marie (meets / meet ) Pierre Curie, who was also a scientist.',
                'They (marries / marry) each other because they (is / are) in love.',
            ],
        },
        {
            'instructions': 'Circle the subject that agrees with the verb.',
            'kind': 'sentence-editing',
            'assessment': False,
            'items': [
                'The (sun / suns) shines on the grassy field.',
                '(Flower / Flowers) wave in the wind.',
                'Spotted (cow / cows) quietly graze.',
                'The (farmer / farmers) looks out over his land.',
                '(He / They) loves the land because (it / they) is good.',
            ],
        },
        {
            'instructions': 'Fill in the blanks with verbs from the word bank. Remember to match singular subjects with singular verbs and plural subjects with plural verbs! [Provided word bank - Singular | Plural: barks | bark; is | are; blows | blow; digs | dig; calms | calm; gives | give; blooms | bloom]',
            'kind': 'fill-blank',
            'assessment': False,
            'items': [
                'Dogs ________ at night.',
                'The fox ________ a hole.',
                'The boys ________ sorry.',
                'Roses ________ in the spring.',
                'Wind ________ the trees.',
                'Jess and Sam ________ me gifts.',
                'Music ________ the infant.',
            ],
        },
        {
            'instructions': 'Circle the verb that agrees with the subject.',
            'kind': 'sentence-editing',
            'assessment': False,
            'items': [
                'The girls (rolls / roll) down the hill.',
                'Susan (stops / stop) halfway down the slope.',
                'The bushes (is / are) in her way and (blocks / block) her!',
                'However, Callie (reaches / reach) the very bottom of the hill.',
                'Susan (runs / run) the rest of the way, and Callie (waits / wait) for her.',
            ],
        },
        {
            'instructions': 'Circle the subject that agrees with the verb.',
            'kind': 'sentence-editing',
            'assessment': False,
            'items': [
                'The (panda / pandas) rests against a stone.',
                '(Raindrop / Raindrops) fall to the ground.',
                'The (bird / birds) sing loudly in the trees.',
                'The (forest / forests) is a peaceful place.',
                '(A photographer / Photographers) captures the scene in a photo.',
            ],
        },
        {
            'instructions': 'Rewrite the sentences so that the verbs agree with their subjects.',
            'kind': 'sentence-editing',
            'assessment': True,
            'items': [
                'The children runs at recess.',
                'Mel and Sara swims in the summer.',
                'Tanner build a house.',
                'The dishes falls from the shelf.',
                'Bells rings on Christmas day.',
                'My mom trim the rose bush.',
            ],
        },
    ],
    23: [
        {
            'instructions': 'Underline the contractions in the sentences below. Write the two words that are being combined on the blanks.',
            'kind': 'sentence-editing',
            'assessment': False,
            'items': [
                "She'll sing all night.",
                "Let's go home.",
                "Cats don't like to get wet.",
                "You're a good singer.",
                "They'd leave if they could.",
            ],
        },
        {
            'instructions': "Rewrite the sentences and combine the two underlined words into a contraction. (Underlined words per sentence: 1. 'are not' 2. 'Who is' 3. 'I have')",
            'kind': 'sentence-editing',
            'assessment': False,
            'items': [
                'Kim and Jon are not siblings.',
                'Who is at the door?',
                'I have never been so happy!',
            ],
        },
        {
            'instructions': 'Write sentences according to the instructions below. Include a contraction in each sentence and underline it.',
            'kind': 'short-answer',
            'assessment': False,
            'items': [
                'Write a sentence about one of your friends.',
                'Write a sentence about a rabbit.',
                'Write a sentence about yourself.',
                'Write a sentence about a song.',
            ],
        },
    ],
    24: [
        {
            'instructions': "Write don't or doesn't to complete the sentence.",
            'kind': 'fill-blank',
            'assessment': False,
            'items': [
                'The new movie ____ come out until next week.',
                'My friend ____ know if it will do well in theaters.',
                'Critics say that they ____ like the movie.',
                'They ____ think the story is good.',
                'The story ____ make sense to the audience.',
                'The producer ____ know if the movie will make money.',
                "The actors ____ know if they'll be hired again.",
                'The writers ____ know if the sequel will be made.',
                'When the movie comes out, it ____ do well at all.',
                'I guess people ____ want to see another movie about robots.',
            ],
        },
        {
            'instructions': "For each sentence, split the contraction don't or doesn't into two words in the boxes. If the sentence has the correct contraction, write CORRECT on the line. If the sentence has the wrong contraction, rewrite the sentence on the lines provided so that the verbs agree with the nouns.",
            'kind': 'sentence-editing',
            'assessment': False,
            'items': [
                "Mom and Dad doesn't like to go into town.",
                "They don't like the traffic.",
                "They doesn't like how noisy it is.",
                "Mom really don't like shopping online.",
                "They doesn't want to go to town.",
            ],
        },
        {
            'instructions': "Write sentences according to the instructions below. Use don't or doesn't in each sentence.",
            'kind': 'short-answer',
            'assessment': True,
            'items': [
                'Write a sentence about what owls do not do.',
                'Write a sentence about what a spinning top does not do.',
                'Write a sentence about what a bear does not do.',
                'Write a sentence about what a car does not do.',
            ],
        },
    ],
    25: [
        {
            'instructions': "Complete each sentence with a descriptive adjective. (Sidebar tip: 'Choose adjectives wisely. Use a thesaurus to replace overused and vague adjectives!')",
            'kind': 'fill-blank',
            'assessment': False,
            'items': [
                '____ buffalo stampeded across the plain.',
                'Donovan tried to tame his ____ hair.',
                '____ dancers leapt and twirled on the stage.',
                'Make sure you pick the ____ flowers for Mom.',
                'The joke I heard from Darius was ____!',
                "Cherilyn's ____ dog is causing a lot of trouble.",
                '____ brownies waited for us on the counter.',
                "Jerrica was ____, so she didn't want to visit the park.",
                'I threw the ____ bag of trash into the dumpster.',
            ],
        },
        {
            'instructions': 'Circle the adjective that is more descriptive and interesting.',
            'kind': 'multiple-choice',
            'assessment': False,
            'items': [
                'The kitchen table is (old / ancient).',
                'The (joyful / happy) students laughed.',
                'Blake pets the (nice / fuzzy) kitten.',
                'The television was (blaring / loud).',
                'The (small / scrawny) tree waved in the wind.',
                'Kurt baked (tasty / delicious) cakes.',
                'The (pretty / colorful) butterfly landed on a flower.',
                'After my uncle cleaned his motorcycle, it looked (clean / shiny).',
                'The board game was (difficult / hard) to play.',
                'Sandra straightens her (frizzy / messy) hair.',
            ],
        },
        {
            'instructions': 'The sentences below contain no adjectives. Make them more descriptive and interesting by rewriting them and adding descriptive adjectives. Some sentences may need more than one.',
            'kind': 'sentence-editing',
            'assessment': False,
            'items': [
                'Kelly bought a house.',
                'The house needed work.',
                'The walls were a color.',
                'Spiders hung from the lamps.',
                'Kelly painted the walls a color.',
                'She spent a week cleaning the house.',
                'She loves her home.',
            ],
        },
        {
            'instructions': 'Read the paragraph below. The paragraph will be more interesting with more descriptive adjectives! Rewrite the paragraph above and change the underlined adjectives to be more descriptive and interesting! (Text extraction does not preserve which words are underlined; the adjectives to change are: small, nice, funny, small, short, happy, long.)',
            'kind': 'paragraph-writing',
            'assessment': False,
            'items': [
                'Olivia owns a small pug. He has nice fur and a funny tail. Olivia takes the small pug on a walk. The pug has to move his short legs quickly to keep up! Liv gives the happy pug water after the long walk.',
            ],
        },
    ],
    26: [
        {
            'instructions': 'Complete each sentence with a descriptive action verb.',
            'kind': 'fill-blank',
            'assessment': False,
            'items': [
                'The waiter ____ coffee with cream.',
                'Hot water ____ on the stovetop.',
                'Jesse ____ for his missing hat.',
                'A cowboy ____ the wild stallion.',
                'Tristan ____ the ball into the goal.',
                'The giant oak ____ with a mighty thump.',
                'Ani ____ a paper for class.',
                'Kristen ____ the coin into the fountain.',
                'Giant dragons ____ fire at the intruders.',
                'Our neighbors ____ loud music all night long.',
                'Playing an instrument ____ lots of practice.',
            ],
        },
        {
            'instructions': "Circle the action verb that is more descriptive and interesting. (Sidebar note: 'Descriptive action verbs show the reader what is happening in the sentence.')",
            'kind': 'multiple-choice',
            'assessment': False,
            'items': [
                'The spy (snuck / moved) through the dark hallway.',
                'Peyton (put / shot) the arrow into the bullseye.',
                'The white flag (is / flapped) in the wind.',
                'Misha (stared / looked) at the lion.',
                'The mother bear (protected / stood by) her cubs.',
                'Otters (are / paddle) in the river.',
                'The angry neighbor (knocked / pounded) on the door.',
                'I accidentally (took / ripped) a page from the book!',
                "Sam's dog (barked / snarled) at the intruder.",
                'Abigail (chose / got) a chocolate cake for her party.',
            ],
        },
        {
            'instructions': "The sentences below contain no action verbs. Rewrite them by adding descriptive action verbs where indicated. (The '____' marks the spot where the verb belongs.)",
            'kind': 'fill-blank',
            'assessment': False,
            'items': [
                'Char ____ her birthday.',
                'Her family ____ her out to dinner.',
                'The waitress ____ them at a big booth.',
                'They all ____ the menu.',
                'The restaurant ____ so much amazing food!',
                'Char finally ____ a burger and fries.',
                'Suddenly, all the wait staff ____ out.',
                'They ____ "Happy Birthday" to Char!',
            ],
        },
        {
            'instructions': 'Read the paragraph below. The paragraph will be more interesting with more descriptive action verbs! Rewrite the paragraph above and change the underlined action verbs to be more descriptive and interesting! (Text extraction does not preserve which words are underlined; the verbs to change are: was, came, sat, went, went, looked, sat.)',
            'kind': 'paragraph-writing',
            'assessment': False,
            'items': [
                'An orange cat was in a tree. Then, a white cat came by. She sat on the ground. The orange cat went out of the tree. He went to the white cat. She looked at him. Then, they sat together as friends.',
            ],
        },
    ],
}
