# Generated by Django 6.0.1 on 2026-07-08 00:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curricula', '0004_chapter_curriculumdocument_lesson_and_more'),
        ('worklog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MasteryAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rubric', models.TextField(help_text='The criteria the work is judged against.')),
                ('answers', models.TextField(help_text="The child's work / answers that were assessed.")),
                ('ai_level', models.CharField(blank=True, choices=[('no_evidence', 'No evidence'), ('beginning', 'Beginning'), ('developing', 'Developing'), ('proficient', 'Proficient'), ('mastered', 'Mastered')], max_length=20)),
                ('ai_summary', models.TextField(blank=True)),
                ('ai_criteria', models.JSONField(blank=True, default=list)),
                ('ai_encouragement', models.TextField(blank=True)),
                ('parent_override_level', models.CharField(blank=True, choices=[('no_evidence', 'No evidence'), ('beginning', 'Beginning'), ('developing', 'Developing'), ('proficient', 'Proficient'), ('mastered', 'Mastered')], max_length=20)),
                ('final_level', models.CharField(blank=True, choices=[('no_evidence', 'No evidence'), ('beginning', 'Beginning'), ('developing', 'Developing'), ('proficient', 'Proficient'), ('mastered', 'Mastered')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('finalized', 'Finalized')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mastery_assessments', to=settings.AUTH_USER_MODEL)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to='curricula.lesson')),
                ('work_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='worklog.worklogentry')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
