# Generated by Django 6.0.1 on 2026-07-08 00:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_invitation_resent_at'),
        ('curricula', '0004_chapter_curriculumdocument_lesson_and_more'),
        ('students', '0002_student_family'),
        ('tutor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('skill_type', models.CharField(choices=[('manga', 'Manga'), ('comic', 'Comic'), ('flashcards', 'Flashcards'), ('drill', 'Drill')], default='manga', max_length=20)),
                ('student_content', models.TextField(help_text='What the child sees (e.g. a comic script).')),
                ('parent_content', models.TextField(blank=True, help_text='Teaching guide for the parent.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved')], default='draft', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='students.student')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_materials', to=settings.AUTH_USER_MODEL)),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='core.family')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='curricula.lesson')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
