# Generated by Django 6.0.1 on 2026-07-08 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0002_material'),
    ]

    operations = [
        migrations.CreateModel(
            name='MangaPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(help_text='Reading order within the page.')),
                ('image', models.FileField(blank=True, upload_to='manga/%Y/%m/')),
                ('image_path', models.CharField(blank=True, help_text="Path under static/ for committed panel art (e.g. 'manga/number-besties/p1.png').", max_length=300)),
                ('alt', models.CharField(blank=True, help_text='Accessible description of the art.', max_length=300)),
                ('span', models.CharField(choices=[('normal', 'Normal'), ('wide', 'Wide (2 columns)'), ('tall', 'Tall (2 rows)'), ('full', 'Full width')], default='normal', max_length=10)),
                ('caption', models.CharField(blank=True, help_text='Narrator caption box.', max_length=400)),
                ('bubbles', models.JSONField(blank=True, default=list, help_text='List of {speaker, text, kind, x, y} overlays (x/y are 0-100 percentages).')),
                ('prompt', models.TextField(blank=True, help_text='The image-gen prompt used to draw this panel.')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panels', to='tutor.material')),
            ],
            options={
                'ordering': ['order'],
                'constraints': [models.UniqueConstraint(fields=('material', 'order'), name='unique_panel_order_per_material')],
            },
        ),
    ]
