# Generated by Django 6.0.1 on 2026-07-08 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0003_mangapanel'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='student_intro',
            field=models.TextField(blank=True, help_text='A short, grade-level explanation for the child of what this lesson is about — shown with the manga.'),
        ),
        migrations.AlterField(
            model_name='material',
            name='parent_content',
            field=models.TextField(blank=True, help_text='Teaching guide (Markdown) for the parent.'),
        ),
    ]
