# Generated by Django 6.0.1 on 2026-07-08 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_familymembership_role'),
        ('curricula', '0004_chapter_curriculumdocument_lesson_and_more'),
        ('students', '0003_alter_student_grade_level'),
        ('tutor', '0004_material_student_intro_alter_material_parent_content'),
        ('worklog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('intro', models.TextField(blank=True, help_text='Kid-facing instructions shown above the questions.')),
                ('reading', models.CharField(blank=True, help_text="What to read first, e.g. 'Chapters 3–4'.", max_length=200)),
                ('rubric', models.TextField(blank=True, help_text='Markdown rubric used when assessing responses.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(blank=True, help_text='Optional: pin this set to one child; blank = any child placed in the curriculum.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_sets', to='students.student')),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_sets', to='core.family')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_sets', to='curricula.lesson')),
            ],
            options={
                'ordering': ['lesson__chapter__number', 'lesson__order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('category', models.CharField(choices=[('comprehension', 'Comprehension'), ('context', 'Context'), ('conflict', 'Conflict'), ('plot', 'Plot'), ('setting', 'Setting'), ('character', 'Character'), ('theme', 'Theme'), ('style', 'Style'), ('application', 'Application'), ('vocabulary', 'Vocabulary')], default='comprehension', max_length=20)),
                ('prompt', models.TextField()),
                ('hint', models.TextField(blank=True, help_text='A gentle scaffold shown to the child on demand.')),
                ('question_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='tutor.questionset')),
            ],
            options={
                'ordering': ['order'],
                'constraints': [models.UniqueConstraint(fields=('question_set', 'order'), name='unique_question_order_per_set')],
            },
        ),
        migrations.CreateModel(
            name='ResponseSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted')], default='draft', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_sheets', to='students.student')),
                ('question_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='tutor.questionset')),
                ('work_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='response_sheets', to='worklog.worklogentry')),
            ],
            options={
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('question_set', 'child'), name='unique_response_sheet_per_child_set')],
            },
        ),
    ]
