# Generated by Django 6.0.1 on 2026-07-08 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0005_questionset_question_responsesheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='passage',
            field=models.TextField(blank=True, help_text='For markup questions: the sentence/text the child draws on.'),
        ),
        migrations.AddField(
            model_name='question',
            name='response_type',
            field=models.CharField(choices=[('text', 'Typed answer'), ('markup', 'Mark up the sentence (draw)')], default='text', max_length=10),
        ),
    ]
