# Generated by Django 6.0.1 on 2026-07-08 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0006_question_passage_question_response_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionset',
            name='mode',
            field=models.CharField(choices=[('student', 'Student form (child fills out)'), ('discussion', 'Teacher-led discussion (oral; not submitted)')], default='student', help_text="Student forms appear in the child's portal; discussion sets appear only in the parent/teacher discussion guide.", max_length=12),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('comprehension', 'Comprehension'), ('context', 'Context'), ('conflict', 'Conflict'), ('plot', 'Plot'), ('setting', 'Setting'), ('character', 'Character'), ('theme', 'Theme'), ('style', 'Style'), ('application', 'Application'), ('vocabulary', 'Vocabulary'), ('grammar', 'Grammar'), ('editing', 'Editing'), ('writing', 'Writing')], default='comprehension', max_length=20),
        ),
    ]
