# Generated by Django 6.0.1 on 2026-07-08 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0007_questionset_mode_alter_question_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionset',
            name='answer_key',
            field=models.TextField(blank=True, help_text='Reference answers (Markdown) the AI grader checks against; never shown to the student.'),
        ),
    ]
