# Generated by Django 6.0.1 on 2026-07-09 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0011_alter_question_response_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='masteryassessment',
            name='ai_kid_highlights',
            field=models.JSONField(blank=True, default=list, help_text='Short child-facing bullets shown on the portal feedback page.'),
        ),
    ]
