# Generated by Django 6.0.1 on 2026-07-09 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0012_masteryassessment_ai_kid_highlights'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsesheet',
            name='draft_feedback',
            field=models.JSONField(blank=True, default=dict, help_text='Writing-coach feedback per question id: {qid: {praise, suggestions, at}}.'),
        ),
    ]
