# Generated by Django 6.0.1 on 2026-07-14 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0013_responsesheet_draft_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='masteryassessment',
            name='ai_parent_pointers',
            field=models.JSONField(blank=True, default=list, help_text='Parent/teacher-facing coaching pointers (how to help with the concept) shown on the review page — never shown to the child.'),
        ),
    ]
