# Generated by Django 6.0.1 on 2026-07-15 01:41

from django.db import migrations, models


def preserve_existing_as_float(apps, schema_editor):
    """Keep already-shipped mangas rendering as they do today.

    Every existing panelled material was drawn with balloons floating over the
    art, so pin those to 'float'. New materials use the safe 'band' default;
    the Chi lesson is flipped to 'band' by its own seed command after this runs.
    """
    Material = apps.get_model("tutor", "Material")
    Material.objects.filter(panels__isnull=False).distinct().update(
        manga_text_layout="float"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0014_masteryassessment_ai_parent_pointers'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='manga_text_layout',
            field=models.CharField(choices=[('band', 'Reserved dialogue band (text below the art)'), ('float', 'Floating balloons (text over the art)')], default='band', help_text='How manga dialogue renders: in a reserved band under each panel (never covers the art) or as balloons floating over the art (only use when the art reserves empty space for them).', max_length=10),
        ),
        migrations.RunPython(preserve_existing_as_float, migrations.RunPython.noop),
    ]
