# Generated by Django 6.0.1 on 2026-08-01 14:52

from django.conf import settings
from django.db import migrations, models


def keep_one(rows):
    """Pick the single assessment that survives out of several for one work entry.

    A FINALIZED one wins outright: that's the level a parent actually stamped, and
    it's what the charter report counts — losing it silently rewrites a child's
    record. Among equals, the newest. Sorts its own input so the rule can't be
    quietly broken by changing the caller's query ordering.
    """
    return sorted(
        rows,
        key=lambda r: (r.status == "finalized", r.created_at, r.pk),
        reverse=True,
    )[0]


def doomed_pks(rows):
    """The assessments to delete so that at most one survives per work entry.

    Split out from the migration body so the part that actually destroys data can
    be tested: once the constraint stands there is no way to build a duplicate
    through the ORM to feed an end-to-end test.
    """
    by_entry = {}
    for a in rows:
        by_entry.setdefault(a.work_entry_id, []).append(a)
    doomed = []
    for group in by_entry.values():
        if len(group) < 2:
            continue
        keep = keep_one(group)
        doomed += [r.pk for r in group if r.pk != keep.pk]
    return doomed


def drop_duplicate_assessments(apps, schema_editor):
    """Dedupe before the constraint lands, or the migration aborts the release.

    Prod already had a work entry with THREE assessments — the exact defect the
    constraint exists to prevent — so AddConstraint would fail and take the deploy
    with it.
    """
    Assessment = apps.get_model("tutor", "MasteryAssessment")
    rows = list(
        # final_level is included because the log line below reads it; leaving it
        # deferred would fire one extra query per doomed row.
        Assessment.objects.only(
            "pk", "work_entry_id", "status", "created_at", "final_level"
        )
    )
    doomed = set(doomed_pks(rows))
    if not doomed:
        return
    # This runs once, unattended, against irreplaceable data, and a FINALIZED row
    # is a level a parent stamped. RunPython cannot bring them back, so put what
    # they were in the release log — that is the only record anyone will have.
    # "will delete", not "deleted": this prints inside the migration's transaction,
    # so a failure in AddConstraint below rolls the delete back after the fact.
    # The surviving pk is logged alongside so the log can be read on its own.
    keepers = {r.work_entry_id: r.pk for r in rows if r.pk not in doomed}
    for r in rows:
        if r.pk in doomed:
            print(
                f"HH-144 will delete duplicate assessment pk={r.pk} "
                f"work_entry={r.work_entry_id} status={r.status} "
                f"final_level={r.final_level!r} created={r.created_at.isoformat()} "
                f"(keeping pk={keepers.get(r.work_entry_id)})"
            )
    Assessment.objects.filter(pk__in=doomed).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('curricula', '0009_curriculum_and_placement_is_active'),
        ('tutor', '0017_alter_question_response_type'),
        ('worklog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(drop_duplicate_assessments, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='masteryassessment',
            constraint=models.UniqueConstraint(fields=('work_entry',), name='unique_assessment_per_work_entry'),
        ),
    ]
