# Generated by Django 6.0.1 on 2026-08-01 14:52

from django.conf import settings
from django.db import migrations, models


def keep_one(rows):
    """Pick the single assessment that survives out of several for one work entry.

    A FINALIZED one wins outright: that's the level a parent actually stamped, and
    it's what the charter report counts — losing it silently rewrites a child's
    record. Among equals, the newest. Sorts its own input so the rule can't be
    quietly broken by changing the caller's query ordering.
    """
    return sorted(
        rows,
        key=lambda r: (r.status == "finalized", r.created_at, r.pk),
        reverse=True,
    )[0]


def drop_duplicate_assessments(apps, schema_editor):
    """Dedupe before the constraint lands, or the migration aborts the release.

    Prod already had a work entry with THREE assessments — the exact defect the
    constraint exists to prevent — so AddConstraint would fail and take the deploy
    with it.
    """
    Assessment = apps.get_model("tutor", "MasteryAssessment")
    by_entry = {}
    for a in Assessment.objects.all():
        by_entry.setdefault(a.work_entry_id, []).append(a)
    doomed = []
    for rows in by_entry.values():
        if len(rows) < 2:
            continue
        keep = keep_one(rows)
        doomed += [r.pk for r in rows if r.pk != keep.pk]
    if doomed:
        Assessment.objects.filter(pk__in=doomed).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('curricula', '0009_curriculum_and_placement_is_active'),
        ('tutor', '0017_alter_question_response_type'),
        ('worklog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(drop_duplicate_assessments, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='masteryassessment',
            constraint=models.UniqueConstraint(fields=('work_entry',), name='unique_assessment_per_work_entry'),
        ),
    ]
