# Generated by Django 6.0.1 on 2026-08-01 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0018_one_assessment_per_work_entry'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiSpend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(help_text='Calendar month, "YYYY-MM".', max_length=7, unique=True)),
                ('input_tokens', models.PositiveBigIntegerField(default=0)),
                ('output_tokens', models.PositiveBigIntegerField(default=0)),
                ('calls', models.PositiveIntegerField(default=0)),
                ('micro_usd', models.PositiveBigIntegerField(default=0, help_text='Accumulated estimated cost in millionths of a USD.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-period'],
            },
        ),
    ]
