# Generated by Django 6.0.1 on 2026-08-03 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0019_aispend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='skill_type',
            field=models.CharField(choices=[('manga', 'Manga'), ('comic', 'Comic'), ('flashcards', 'Flashcards'), ('drill', 'Drill'), ('lesson', 'Illustrated lesson')], default='manga', max_length=20),
        ),
        migrations.CreateModel(
            name='LessonBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('kind', models.CharField(choices=[('masthead', 'Masthead'), ('purpose', 'Why this exists'), ('idea', 'Idea'), ('say', 'Say it like this'), ('steps', 'The recipe'), ('worked_example', 'Worked example'), ('stepper', 'Step-through example'), ('translation', 'Translation'), ('errors', 'Error patterns'), ('table', 'Table'), ('math', 'Equation'), ('reveal', 'Predict then check'), ('tool', 'Interactive tool'), ('recap', 'Recap')], max_length=20)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='tutor.material')),
            ],
            options={
                'ordering': ['order'],
                'constraints': [models.UniqueConstraint(fields=('material', 'order'), name='unique_lesson_block_order')],
            },
        ),
    ]
