# Generated by Django 6.0.1 on 2026-08-14 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0020_alter_material_skill_type_lessonblock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='response_type',
            field=models.CharField(choices=[('text', 'Typed answer'), ('markup', 'Mark up the sentence (draw)'), ('characters', 'A box per character'), ('matching', 'Match words to numbered definitions'), ('fill_blank', 'Fill in the blank from a word bank'), ('cloze', 'Fill in the blanks with your own words'), ('paragraph', 'Paragraph: rough draft (sections) → final draft'), ('write_markup', 'Write a sentence, then mark it up (draw)'), ('handwriting', 'Handwriting: write it by hand on ruled lines')], default='text', max_length=20),
        ),
    ]
