# Generated by Django 6.0.1 on 2026-08-19 15:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0022_self_eval_response_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='responsesheet',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='responsesheet',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_response_sheets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='responsesheet',
            name='attachment',
            field=models.FileField(blank=True, help_text='A photo, scan, PDF or document of the finished work.', upload_to='projects/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'heic', 'webp', 'pdf', 'doc', 'docx'])]),
        ),
        migrations.AddField(
            model_name='responsesheet',
            name='attachment_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='responsesheet',
            name='completion_mode',
            field=models.CharField(choices=[('on_screen', 'Answered on screen'), ('on_paper', 'Done on paper, uploaded')], default='on_screen', max_length=20),
        ),
    ]
