# Generated by Django 6.0.1 on 2026-08-20 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0024_choice_response_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='response_type',
            field=models.CharField(choices=[('text', 'Typed answer'), ('markup', 'Mark up the sentence (draw)'), ('characters', 'A box per character'), ('matching', 'Match words to numbered definitions'), ('fill_blank', 'Fill in the blank from a word bank'), ('cloze', 'Fill in the blanks with your own words'), ('paragraph', 'Paragraph: rough draft (sections) → final draft'), ('write_markup', 'Write a sentence, then mark it up (draw)'), ('handwriting', 'Handwriting: write it by hand on ruled lines'), ('self_eval', 'Self-evaluation: rate each component, and note why'), ('choice', 'Multiple choice: pick one, or pick several'), ('order', 'Put the steps in order')], default='text', max_length=20),
        ),
    ]
