# Generated by Django 6.0.1 on 2026-08-20 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0025_order_response_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonblock',
            name='kind',
            field=models.CharField(choices=[('masthead', 'Masthead'), ('purpose', 'Why this exists'), ('idea', 'Idea'), ('say', 'Say it like this'), ('steps', 'The recipe'), ('worked_example', 'Worked example'), ('stepper', 'Step-through example'), ('translation', 'Translation'), ('errors', 'Error patterns'), ('table', 'Table'), ('math', 'Equation'), ('reveal', 'Predict then check'), ('tool', 'Interactive tool'), ('recap', 'Recap'), ('pages', 'Source pages')], max_length=20),
        ),
    ]
