# Generated by Django 6.0.1 on 2026-08-26 16:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0027_drawing_response_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='response_type',
            field=models.CharField(choices=[('text', 'Typed answer'), ('markup', 'Mark up the sentence (draw)'), ('characters', 'A box per character'), ('matching', 'Match words to numbered definitions'), ('fill_blank', 'Fill in the blank from a word bank'), ('cloze', 'Fill in the blanks with your own words'), ('paragraph', 'Paragraph: rough draft (sections) → final draft'), ('write_markup', 'Write a sentence, then mark it up (draw)'), ('handwriting', 'Handwriting: write it by hand on ruled lines'), ('self_eval', 'Self-evaluation: rate each component, and note why'), ('choice', 'Multiple choice: pick one, or pick several'), ('order', 'Put the steps in order'), ('drawing', 'Draw it: the picture IS the answer'), ('photo', 'Make it: photograph what you made')], default='text', max_length=20),
        ),
        migrations.CreateModel(
            name='AnswerPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='answer_photos/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'heic', 'webp'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_photos', to='tutor.question')),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='tutor.responsesheet')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
