# Generated by Django 6.0.1 on 2026-07-24 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Learner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_student_id', models.IntegerField(db_index=True, help_text='students.Student.pk on the host. Deliberately not an FK (D-03).', unique=True)),
                ('language', models.CharField(default='es', max_length=8)),
                ('variant', models.CharField(default='es-MX', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['host_student_id'],
            },
        ),
        migrations.CreateModel(
            name='LearnerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_profile', models.CharField(choices=[('KIDS_EARLY', 'Kids — early (6-9)'), ('KIDS_OLDER', 'Kids — older (10-13)'), ('TEEN', 'Teen (14-17)'), ('ADULT', 'Adult (18+)')], max_length=16)),
                ('support_level', models.CharField(choices=[('PARENT_MEDIATED', 'Parent-mediated'), ('GUIDED', 'Guided'), ('INDEPENDENT', 'Independent')], max_length=16)),
                ('content_ceiling', models.CharField(choices=[('L1', 'L1'), ('L2', 'L2'), ('L3', 'L3'), ('L4', 'L4'), ('L5', 'L5'), ('L6', 'L6'), ('L7', 'L7'), ('L8', 'L8')], max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('learner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='lingua.learner')),
            ],
        ),
    ]
