# Generated by Django 6.0.1 on 2026-07-24 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lingua', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor_type', models.CharField(choices=[('parent', 'Parent'), ('child', 'Child'), ('system', 'System'), ('ai', 'AI')], default='system', max_length=8)),
                ('actor_id', models.IntegerField(blank=True, help_text='Host user id or Student id — never a name.', null=True)),
                ('action', models.CharField(max_length=40)),
                ('target_type', models.CharField(blank=True, max_length=40)),
                ('target_id', models.IntegerField(blank=True, null=True)),
                ('summary', models.CharField(blank=True, help_text='Short human line — no child free-text.', max_length=200)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-ts'],
                'indexes': [models.Index(fields=['action', 'ts'], name='lingua_audi_action_5160b0_idx')],
            },
        ),
    ]
