# Generated by Django 6.0.1 on 2026-07-24 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lingua', '0002_auditevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('age_band', models.CharField(choices=[('KIDS_EARLY', 'Kids — early (6-9)'), ('KIDS_OLDER', 'Kids — older (10-13)'), ('TEEN', 'Teen (14-17)'), ('ADULT', 'Adult (18+)')], max_length=16)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['age_band', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default='es', max_length=8)),
                ('variant', models.CharField(default='es-MX', max_length=16)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('level', models.CharField(choices=[('L1', 'L1'), ('L2', 'L2'), ('L3', 'L3'), ('L4', 'L4'), ('L5', 'L5'), ('L6', 'L6'), ('L7', 'L7'), ('L8', 'L8')], max_length=4)),
                ('source', models.CharField(choices=[('generated', 'AI-generated'), ('public_domain', 'Public domain')], default='generated', max_length=16)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=16)),
                ('critic_passed', models.BooleanField(blank=True, null=True)),
                ('critic_flags', models.JSONField(blank=True, default=list)),
                ('approved_by', models.IntegerField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('theme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stories', to='lingua.theme')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'level'], name='lingua_stor_status_3b476c_idx')],
            },
        ),
    ]
