# Generated by Django 6.0.1 on 2026-07-24 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lingua', '0003_theme_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='flagged_words',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='story',
            name='out_of_band_pct',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='story',
            name='suggested_level',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
