# Generated by Django 6.0.1 on 2026-07-24 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lingua', '0004_story_flagged_words_story_out_of_band_pct_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='polly', max_length=16)),
                ('voice', models.CharField(max_length=32)),
                ('engine', models.CharField(default='neural', max_length=16)),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('audio_key', models.CharField(help_text='R2 object key for the mp3.', max_length=200)),
                ('timings', models.JSONField(blank=True, default=dict, help_text='Flat read-along timing JSON (D-21).')),
                ('duration_ms', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audios', to='lingua.story')),
            ],
            options={
                'ordering': ['story_id', 'voice'],
                'constraints': [models.UniqueConstraint(fields=('story', 'voice', 'engine', 'provider'), name='uniq_story_voice_engine_provider')],
            },
        ),
    ]
