# Generated by Django 6.0.1 on 2026-07-24 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lingua', '0005_storyaudio'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnownWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='known_words', to='lingua.learner')),
            ],
            options={
                'ordering': ['word'],
                'constraints': [models.UniqueConstraint(fields=('learner', 'word'), name='uniq_learner_word')],
            },
        ),
        migrations.CreateModel(
            name='ReadingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('words', models.IntegerField(default=0)),
                ('seconds', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_sessions', to='lingua.learner')),
                ('story', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='lingua.story')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['learner', 'created_at'], name='lingua_read_learner_e4ea1b_idx')],
            },
        ),
    ]
