# Generated by Django 6.0.1 on 2026-07-25 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lingua', '0006_knownword_readingsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='MilestoneAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('words', 'Words read'), ('known', 'Words known')], max_length=8)),
                ('threshold', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='lingua.learner')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('learner', 'kind', 'threshold'), name='uniq_learner_kind_threshold')],
            },
        ),
    ]
