# Generated by Django 6.0.1 on 2026-07-25 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lingua', '0007_milestoneaward'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComprehensionCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('picture_match', 'Picture match'), ('retell', 'Retell'), ('short_answer', 'Short answer')], max_length=16)),
                ('result', models.CharField(choices=[('pending', 'Awaiting review'), ('beginning', 'Beginning'), ('developing', 'Developing'), ('proficient', 'Proficient'), ('strong', 'Strong')], default='pending', max_length=12)),
                ('reviewed_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comprehension_checks', to='lingua.learner')),
                ('story', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='lingua.story')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['learner', 'created_at'], name='lingua_comp_learner_81d21e_idx')],
            },
        ),
    ]
