# Generated by Django 6.0.1 on 2026-07-25 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lingua', '0008_comprehensioncheck'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnerprofile',
            name='last_nudge_reading_count',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
