# Generated by Django 6.0.1 on 2026-07-25 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lingua', '0009_learnerprofile_last_nudge_reading_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhonicsRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.CharField(max_length=12, unique=True)),
                ('title', models.CharField(max_length=80)),
                ('tip', models.CharField(max_length=240)),
                ('example', models.CharField(help_text='Practice words for decoding.', max_length=120)),
                ('order', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'pattern'],
            },
        ),
        migrations.AlterField(
            model_name='comprehensioncheck',
            name='kind',
            field=models.CharField(choices=[('picture_match', 'Picture match'), ('retell', 'Retell'), ('short_answer', 'Short answer'), ('self_check', 'Self check')], max_length=16),
        ),
    ]
