# Generated by Django 6.0.1 on 2026-07-25 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lingua', '0011_aiusage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_kind', models.CharField(choices=[('vocab', 'Vocabulary'), ('question', 'Question')], default='vocab', max_length=16)),
                ('target_ref', models.CharField(help_text='Generic target id (e.g. a normalized word) — no FK (D-30).', max_length=128)),
                ('scheduler', models.CharField(choices=[('leitner', 'Leitner'), ('fsrs', 'FSRS')], default='leitner', max_length=8)),
                ('scheduler_state', models.JSONField(blank=True, default=dict)),
                ('due', models.DateTimeField(db_index=True)),
                ('paused_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_items', to='lingua.learner')),
            ],
            options={
                'ordering': ['due', 'id'],
                'indexes': [models.Index(fields=['learner', 'due'], name='lingua_revi_learner_d8680f_idx')],
                'constraints': [models.UniqueConstraint(fields=('learner', 'target_kind', 'target_ref'), name='uniq_review_item_per_target')],
            },
        ),
    ]
