# Generated by Django 6.0.1 on 2026-07-25 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lingua', '0012_reviewitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnerprofile',
            name='paused_until',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='learnerprofile',
            name='reviews_served_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='learnerprofile',
            name='reviews_served_on',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
