# Generated by Django 6.0.1 on 2026-07-25 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lingua', '0012_reviewitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnerprofile',
            name='paused_until',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
