# Generated by Django 6.0.1 on 2026-07-25 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lingua', '0013_learnerprofile_paused_until_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListeningResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('provider', models.CharField(blank=True, help_text="e.g. 'Dreaming Spanish'.", max_length=120)),
                ('url', models.URLField(help_text='Curated YouTube video/playlist/channel URL.')),
                ('age_band', models.CharField(choices=[('KIDS_EARLY', 'Kids — early (6-9)'), ('KIDS_OLDER', 'Kids — older (10-13)'), ('TEEN', 'Teen (14-17)'), ('ADULT', 'Adult (18+)')], max_length=16)),
                ('level', models.CharField(choices=[('L1', 'L1'), ('L2', 'L2'), ('L3', 'L3'), ('L4', 'L4'), ('L5', 'L5'), ('L6', 'L6'), ('L7', 'L7'), ('L8', 'L8')], max_length=4)),
                ('visual_support', models.BooleanField(default=True, help_text='Strong pictures/gestures/animation aid comprehension.')),
                ('minutes', models.PositiveIntegerField(default=5, help_text='Rough length, for the check-in default.')),
                ('transcript', models.TextField(blank=True, help_text='Optional transcript reveal (LGA-57).')),
                ('order', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['age_band', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ListeningSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutes', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listening_sessions', to='lingua.learner')),
                ('resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='lingua.listeningresource')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['learner', 'created_at'], name='lingua_list_learner_cb9a68_idx')],
            },
        ),
    ]
