# Generated by Django 6.0.1 on 2026-07-26 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lingua', '0014_listeningresource_listeningsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiusage',
            name='images',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='story',
            name='art_contract',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='StoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beat_index', models.IntegerField(help_text='0-based index of the 1–2 sentence beat.')),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('image_key', models.CharField(help_text='R2 object key for the image.', max_length=200)),
                ('model', models.CharField(blank=True, help_text='Image model id (disclosure).', max_length=64)),
                ('prompt', models.TextField(blank=True, help_text='Exact prompt sent (disclosure/repro).')),
                ('alt_text', models.CharField(blank=True, help_text='The sentences it depicts.', max_length=300)),
                ('width', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='lingua.story')),
            ],
            options={
                'ordering': ['story_id', 'beat_index'],
                'constraints': [models.UniqueConstraint(fields=('story', 'beat_index', 'model'), name='uniq_story_beat_model')],
            },
        ),
    ]
