# Generated by Django 6.0.1 on 2026-07-27 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lingua', '0015_aiusage_images_story_art_contract_storyimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_key', models.CharField(help_text='PRIVATE media key (signed URL).', max_length=200)),
                ('content_type', models.CharField(blank=True, max_length=64)),
                ('seconds', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='lingua.learner')),
                ('story', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='lingua.story')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['learner', 'created_at'], name='lingua_stor_learner_570b19_idx')],
            },
        ),
    ]
