# Generated by Django 6.0.1 on 2026-07-28 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lingua', '0016_storyrecording'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(blank=True, max_length=200)),
                ('country', models.CharField(blank=True, help_text='Author/origin, e.g. México, España.', max_length=64)),
                ('grade', models.CharField(choices=[('PK', 'Pre-K'), ('K', 'Kindergarten'), ('1', '1st grade'), ('2', '2nd grade'), ('3', '3rd grade'), ('4', '4th grade'), ('5', '5th grade'), ('6', '6th grade'), ('7', '7th grade'), ('8', '8th grade')], max_length=2)),
                ('note', models.CharField(blank=True, help_text="One line: theme + why it's good.", max_length=300)),
                ('language', models.CharField(default='es', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['grade', 'title'],
                'indexes': [models.Index(fields=['grade'], name='lingua_libr_grade_3c0d4b_idx')],
                'constraints': [models.UniqueConstraint(fields=('title', 'author', 'grade'), name='uniq_book_title_author_grade')],
            },
        ),
        migrations.CreateModel(
            name='BookLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Snapshot / custom title.', max_length=200)),
                ('author', models.CharField(blank=True, max_length=200)),
                ('read_on', models.DateField()),
                ('enjoyed', models.CharField(blank=True, choices=[('loved', '¡Me encantó!'), ('ok', 'Estuvo bien'), ('meh', 'Más o menos')], max_length=8)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('logged_by', models.CharField(choices=[('kid', 'Kid'), ('parent', 'Parent')], default='kid', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_logs', to='lingua.learner')),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='lingua.librarybook')),
            ],
            options={
                'ordering': ['-read_on', '-created_at'],
                'indexes': [models.Index(fields=['learner', 'read_on'], name='lingua_book_learner_bf02dd_idx')],
            },
        ),
    ]
