# Generated by Django 6.0.1 on 2026-07-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lingua', '0017_librarybook_booklogentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='librarybook',
            name='is_translation',
            field=models.BooleanField(default=False, help_text='True if translated INTO Spanish (vs originally Spanish).'),
        ),
        migrations.AddField(
            model_name='librarybook',
            name='isbn',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='librarybook',
            name='level_label',
            field=models.CharField(blank=True, help_text="For non-native tracks, e.g. 'Level 1 · present tense', 'A1'.", max_length=40),
        ),
        migrations.AddField(
            model_name='librarybook',
            name='track',
            field=models.CharField(choices=[('native', 'Native grade-level'), ('ci', 'For learners (CI/TPRS)'), ('adult', 'Adult track'), ('free', 'Free / public domain')], default='native', max_length=8),
        ),
        migrations.AddField(
            model_name='librarybook',
            name='url',
            field=models.URLField(blank=True, help_text='Free/public-domain full text, when available.'),
        ),
        migrations.AlterField(
            model_name='librarybook',
            name='grade',
            field=models.CharField(blank=True, choices=[('PK', 'Pre-K'), ('K', 'Kindergarten'), ('1', '1st grade'), ('2', '2nd grade'), ('3', '3rd grade'), ('4', '4th grade'), ('5', '5th grade'), ('6', '6th grade'), ('7', '7th grade'), ('8', '8th grade')], help_text='Native-track grade; blank for CI/adult/free books.', max_length=2),
        ),
    ]
