# Generated by Django 6.0.1 on 2026-07-28 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lingua', '0018_librarybook_is_translation_librarybook_isbn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booklogentry',
            name='host_worklog_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
