# Generated by Django 6.0.1 on 2026-07-28 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lingua', '0019_booklogentry_host_worklog_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='librarybook',
            name='tense',
            field=models.CharField(blank=True, help_text='CI novellas: which verb tense(s) the book uses — the real leveling axis.', max_length=40),
        ),
        migrations.AlterField(
            model_name='librarybook',
            name='level_label',
            field=models.CharField(blank=True, help_text="CI level ('Level 1', 'Novice-low') or adult stage ('Etapa 1 · A1–B1').", max_length=40),
        ),
    ]
