# Generated by Django 6.0.1 on 2026-07-28 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lingua', '0020_librarybook_tense_alter_librarybook_level_label'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='librarybook',
            name='uniq_book_title_author_grade',
        ),
        migrations.AddConstraint(
            model_name='librarybook',
            constraint=models.UniqueConstraint(fields=('title', 'author', 'grade', 'track'), name='uniq_book_title_author_grade_track'),
        ),
    ]
