# Generated by Django 6.0.1 on 2026-07-29 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lingua', '0021_remove_librarybook_uniq_book_title_author_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarybook',
            name='track',
            field=models.CharField(choices=[('native', 'By grade'), ('ci', 'For learners'), ('adult', 'Adult track'), ('free', 'Free online')], default='native', max_length=8),
        ),
    ]
