# Generated by Django 6.0.1 on 2026-07-29 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lingua', '0022_alter_librarybook_track'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlphabetTile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(help_text='Displayed glyph, e.g. ñ or ll.', max_length=4, unique=True)),
                ('spoken', models.CharField(help_text="What to synthesize, e.g. 'eñe' or 'elle'.", max_length=40)),
                ('example', models.CharField(blank=True, help_text='Optional example word.', max_length=40)),
                ('kind', models.CharField(choices=[('letter', 'Letter'), ('digraph', 'Digraph')], default='letter', max_length=8)),
                ('order', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'symbol'],
            },
        ),
        migrations.CreateModel(
            name='TutorPacket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('source', models.CharField(blank=True, help_text="e.g. 'italki · Juan Cárdenas'.", max_length=120)),
                ('body', models.TextField(blank=True, help_text='Practice phrases, one per line. Shown on the packet page and Escuchar.')),
                ('file', models.FileField(blank=True, help_text='Optional teacher handout (DOCX/PDF).', null=True, upload_to='lingua/tutor/%Y/%m/')),
                ('host_student_id', models.IntegerField(blank=True, db_index=True, help_text='students.Student.pk when packet is for one child; blank = all learners.', null=True)),
                ('order', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AudioClip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=240)),
                ('provider', models.CharField(default='polly', max_length=16)),
                ('voice', models.CharField(max_length=32)),
                ('engine', models.CharField(default='neural', max_length=16)),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('audio_key', models.CharField(help_text='R2 object key for the mp3.', max_length=200)),
                ('duration_ms', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['text'],
                'constraints': [models.UniqueConstraint(fields=('text', 'voice', 'engine', 'provider'), name='uniq_clip_text_voice_engine_provider')],
            },
        ),
    ]
