# Generated by Django 6.0.1 on 2026-07-30 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lingua', '0023_tutorpacket_audioclip_alphabettile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pathway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('title', models.CharField(max_length=120)),
                ('age_band', models.CharField(choices=[('KIDS_EARLY', 'Kids — early (6-9)'), ('KIDS_OLDER', 'Kids — older (10-13)'), ('TEEN', 'Teen (14-17)'), ('ADULT', 'Adult (18+)')], max_length=16)),
                ('order', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'pathways',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PathwayStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=160)),
                ('kind', models.CharField(choices=[('story', 'Story'), ('story_level', 'Story level'), ('phonics', 'Phonics'), ('listen', 'Listen'), ('tutor_packet', 'Tutor packet'), ('review', 'Review'), ('link', 'Link')], max_length=16)),
                ('target_ref', models.CharField(blank=True, help_text='Opaque target (story pk, L1, packet pk, URL name, …).', max_length=128)),
                ('pass_rule', models.JSONField(blank=True, default=dict, help_text='Optional completion hints, e.g. {"min_stories": 1}.')),
                ('optional', models.BooleanField(default=False, help_text='Optional steps never block unlock of later required steps.')),
                ('pathway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='lingua.pathway')),
            ],
            options={
                'ordering': ['order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('pathway', 'order'), name='uniq_pathway_step_order')],
            },
        ),
    ]
