# Generated by Django 6.0.1 on 2026-07-30 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lingua', '0024_pathway_pathwaystep'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_kind', models.CharField(help_text='Matches PathwayStep.kind.', max_length=16)),
                ('target_ref', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_visits', to='lingua.learner')),
            ],
            options={
                'indexes': [models.Index(fields=['learner', 'station_kind'], name='lingua_stat_learner_fa6cf5_idx')],
                'constraints': [models.UniqueConstraint(fields=('learner', 'station_kind', 'target_ref'), name='uniq_station_visit')],
            },
        ),
    ]
