# Generated by Django 6.0.1 on 2026-07-30 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lingua', '0025_stationvisit'),
    ]

    operations = [
        migrations.CreateModel(
            name='PathwayCheckmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pathway_checkmarks', to='lingua.learner')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkmarks', to='lingua.pathwaystep')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('learner', 'step'), name='uniq_pathway_checkmark')],
            },
        ),
    ]
