# Generated by Django 6.0.1 on 2026-07-31 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lingua', '0026_pathwaycheckmark'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassroomPhrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='The Spanish phrase.', max_length=120, unique=True)),
                ('english', models.CharField(help_text='What it means, for the parent.', max_length=160)),
                ('category', models.CharField(choices=[('opening', 'Starting the session'), ('asking', 'Asking about the book'), ('praise', 'Encouraging'), ('redirect', 'Nudging back on track'), ('closing', 'Finishing up')], default='asking', max_length=16)),
                ('note', models.CharField(blank=True, help_text='Optional coaching note — when to reach for this one.', max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
