# Generated by Django 6.0.1 on 2026-07-31 23:35

import django.utils.timezone
from django.db import migrations, models
from django.utils import timezone


def backfill_on_date(apps, schema_editor):
    """Date existing ticks from when they were actually made, not from deploy day.

    The field default stamps every pre-existing row with the migration date, which
    would invent a streak nobody earned and collapse several days of history onto
    one. Small table, so a plain loop is fine.
    """
    Checkmark = apps.get_model("lingua", "PathwayCheckmark")
    for pk, created in Checkmark.objects.values_list("pk", "created_at"):
        if created:
            Checkmark.objects.filter(pk=pk).update(on_date=timezone.localtime(created).date())


class Migration(migrations.Migration):

    dependencies = [
        ('lingua', '0027_classroom_phrase'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pathwaycheckmark',
            name='uniq_pathway_checkmark',
        ),
        migrations.AddField(
            model_name='pathwaycheckmark',
            name='on_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.localdate, help_text='Local date this stop was ticked (the Camino resets daily).'),
        ),
        migrations.RunPython(backfill_on_date, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='pathwaycheckmark',
            index=models.Index(fields=['learner', 'on_date'], name='lingua_path_learner_bd0287_idx'),
        ),
        migrations.AddConstraint(
            model_name='pathwaycheckmark',
            constraint=models.UniqueConstraint(fields=('learner', 'step', 'on_date'), name='uniq_pathway_checkmark_day'),
        ),
    ]
