# Generated by Django 6.0.1 on 2026-08-01 00:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lingua', '0028_daily_camino_checkmark'),
    ]

    operations = [
        migrations.CreateModel(
            name='WritingError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('orthographic', 'Spelling — b/v, c/s/z, g/j, ll/y, h muda, r/rr, qu/c/k, x'), ('accent', 'Accents — missing or misplaced tilde, diacrítica, hiato'), ('agreement', 'Agreement — gender, number, article/noun/adjective'), ('verb', 'Verbs — tense, mood, person, ser/estar'), ('syntax', "Sentence shape — word order, adjective place, personal 'a', por/para"), ('lexical', 'Wrong word — including false cognates'), ('interference', 'English creeping in — calques, code-switching'), ('mechanics', 'Mechanics — ¿¡, capitals, dialogue raya, punctuation')], db_index=True, max_length=16)),
                ('source', models.CharField(choices=[('dictado', 'Dictado'), ('copia', 'Copia'), ('freewrite', 'Free write'), ('journal', 'Journal'), ('other', 'Other')], default='dictado', max_length=16)),
                ('wrote', models.CharField(blank=True, help_text='What she actually wrote (optional).', max_length=120)),
                ('expected', models.CharField(blank=True, help_text='What it should have been (optional).', max_length=120)),
                ('on_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writing_errors', to='lingua.learner')),
            ],
            options={
                'ordering': ['-on_date', '-id'],
                'indexes': [models.Index(fields=['learner', 'on_date'], name='lingua_writ_learner_11cbb4_idx')],
            },
        ),
    ]
