# Generated by Django 6.0.1 on 2026-08-01 00:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lingua', '0029_writing_error'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeWrite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutes', models.PositiveIntegerField(default=5)),
                ('words', models.PositiveIntegerField(default=0)),
                ('text', models.TextField(blank=True, help_text='Optional — blank when she wrote on paper.')),
                ('prompt', models.CharField(blank=True, max_length=200)),
                ('on_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='free_writes', to='lingua.learner')),
            ],
            options={
                'ordering': ['-on_date', '-id'],
                'indexes': [models.Index(fields=['learner', 'on_date'], name='lingua_free_learner_78bab4_idx')],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.CharField(blank=True, max_length=200)),
                ('entry', models.TextField(help_text='What she wrote.')),
                ('reply', models.TextField(blank=True, help_text="The parent's reply — to the MEANING.")),
                ('on_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='lingua.learner')),
            ],
            options={
                'ordering': ['-on_date', '-id'],
                'indexes': [models.Index(fields=['learner', 'on_date'], name='lingua_jour_learner_751e1a_idx')],
            },
        ),
    ]
