# Generated by Django 6.0.1 on 2026-08-01 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lingua', '0030_kaylin_writing_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonicsrule',
            name='age_band',
            field=models.CharField(blank=True, choices=[('KIDS_EARLY', 'Kids — early (6-9)'), ('KIDS_OLDER', 'Kids — older (10-13)'), ('TEEN', 'Teen (14-17)'), ('ADULT', 'Adult (18+)')], help_text="Blank = every band. The accent rules are for the older band only; without this they land on the youngest child's sounds page.", max_length=16),
        ),
    ]
