# Generated by Django 6.0.1 on 2026-08-01 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lingua', '0031_phonics_age_band'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='stationvisit',
            name='lingua_stat_learner_fa6cf5_idx',
        ),
        migrations.RemoveConstraint(
            model_name='stationvisit',
            name='uniq_station_visit',
        ),
        migrations.DeleteModel(
            name='StationVisit',
        ),
    ]
