# Generated by Django 6.0.1 on 2026-08-05 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lingua', '0033_listening_rotation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='learner',
            options={'ordering': ['host_student_id', 'host_user_id', 'id']},
        ),
        migrations.AddField(
            model_name='learner',
            name='host_user_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='auth user pk for an ADULT learner. Deliberately not an FK (D-03).', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='learner',
            name='host_student_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='students.Student.pk on the host. Deliberately not an FK (D-03).', null=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name='learner',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('host_student_id__isnull', False), ('host_user_id__isnull', True)), models.Q(('host_student_id__isnull', True), ('host_user_id__isnull', False)), _connector='OR'), name='learner_has_exactly_one_host_ref'),
        ),
    ]
