# Generated by Django 6.0.1 on 2026-08-05 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lingua', '0034_adult_learner'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelPhrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='The Spanish phrase (es-MX).', max_length=120)),
                ('english', models.CharField(help_text='What it means.', max_length=160)),
                ('category', models.CharField(choices=[('airport', 'Llegada — airport, taxi, checking in'), ('hotel', 'El hotel — the room, the front desk'), ('restaurant', 'Comer — ordering, paying'), ('directions', 'Encontrar el camino — directions, transport'), ('shopping', 'Comprar — shops, markets, prices'), ('pharmacy', 'La farmacia — feeling unwell'), ('emergency', 'Emergencias — help, lost, hurt'), ('smalltalk', 'Conversar — greetings and being a guest')], default='smalltalk', max_length=16)),
                ('note', models.CharField(blank=True, help_text='Optional note — when to use it, or what you will hear back.', max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('text', 'category'), name='travelphrase_unique_text_per_category')],
            },
        ),
    ]
