# Generated by Django 5.0.14 on 2025-09-09 04:28

import accounts.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[
                ("objects", accounts.managers.CustomerUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                db_index=True, max_length=254, unique=True, verbose_name="email address"
            ),
        ),
    ]
