# Generated by Django 6.0.1 on 2026-07-09 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_customuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onboarding_goal', models.CharField(blank=True, choices=[('charter', 'Homeschooling under a charter or state program — records & reports matter'), ('simple', 'Just tracking our days, simply'), ('review', 'I was invited to help or review a family')], max_length=20)),
                ('has_seen_welcome', models.BooleanField(default=False)),
                ('setup_dismissed', models.BooleanField(default=False)),
                ('dismissed_hints', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
