# Generated by Django 6.0.1 on 2026-07-16 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_settings_and_inbox_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='landing',
            field=models.CharField(blank=True, choices=[('', 'Smart default (based on your role)'), ('home', 'Hub'), ('dashboard', 'Progress'), ('inbox', 'Action inbox')], help_text='Where to go right after you log in.', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='timezone',
            field=models.CharField(blank=True, choices=[('', 'Site default'), ('America/New_York', 'Eastern (New York)'), ('America/Chicago', 'Central (Chicago)'), ('America/Denver', 'Mountain (Denver)'), ('America/Phoenix', 'Arizona (Phoenix)'), ('America/Los_Angeles', 'Pacific (Los Angeles)'), ('America/Anchorage', 'Alaska (Anchorage)'), ('Pacific/Honolulu', 'Hawaii (Honolulu)')], help_text='Show dates and times in this timezone.', max_length=64),
        ),
    ]
