"""The five essays of The Essay, Volume 2 — the guide's own pages.

GENERATED by scripts/gen_essay_lessons.py from the page transcriptions;
edit that, or the guide, rather than this file. The front matter, the
blueprint and both grading forms live in tutor/essay.py, and the EVEN week
of every lesson is built from them — it is the same five pages each time
(rough draft, blueprint checklist, self-evaluation, final draft, teacher's
form), so only the ODD week is described here.

Printed quirks are preserved verbatim and called out in `notes`.
"""

LESSONS = [
    {
        'number': 1,
        'title': 'Write an Orange',
        'weeks': (1, 2),
        'banner': 'Descriptive essays describe something very specifically using '
            "details to spark the reader's senses. You have an opportunity to "
            'explore details that make something unique and share your '
            'discovery so your audience might experience what you describe.',
        'vocabulary': [],
        'steps': [
            {
                'heading': 'Sensory Description Exercise »',
                'kind': 'observation',
                'instruction': 'Before you begin writing your first descriptive essay work through'
                    ' this senses exercise to help warm up your observation skills.',
                'prompts': [
                    {'text': 'What do you see from where you sit? Look up close and far away.',
                     'number': '1.', 'lines': 3},
                    {'text': 'What do you hear? Listen for loud and soft noises and also for '
                      "noises you don't usually think of as noise.",
                     'number': '2.', 'lines': 3},
                    {'text': 'What can you touch from where you sit? Describe textures, shapes, '
                      'size, etc.',
                     'number': '3.', 'lines': 3},
                    {'text': 'Describe the smells around you. Smell plants, clothing, food, and '
                      'objects as well as the air.',
                     'number': '4.', 'lines': 3},
                    {'text': 'What can you taste? What do you imagine the things you smell, '
                      'hear, see, etc. taste like?',
                     'number': '5.', 'lines': 3},
                ],
            },
            {
                'heading': 'Answer the following questions to help you develop your idea:',
                'kind': 'idea_development',
                'instruction': 'Now you may begin crafting your first descriptive essay.',
                'prompts': [
                    {'text': 'What makes orange, orange?',
                     'number': '', 'lines': 2},
                    {'text': 'Where is orange?',
                     'number': '', 'lines': 2},
                    {'text': 'Describe how the color orange affects the senses.',
                     'number': '', 'lines': 2},
                    {'text': 'How does the color orange make you feel? Why?',
                     'number': '', 'lines': 3},
                    {'text': 'Painter Vincent Van Gogh reminds us that, "There is no blue '
                      'without yellow and without orange." What are complimentary colors?'
                      ' Do some research. How do these colors interact?',
                     'number': '', 'lines': 3},
                    {'text': 'What makes an orange an orange?',
                     'number': '', 'lines': 2},
                    {'text': 'Describe an orange in detail remembering to explore the fruit '
                      'through all of your senses.',
                     'number': '', 'lines': 4},
                    {'text': 'Robert Louis Stevenson once said, "And every day when I\'ve been '
                      'good, I get an orange after food." Is he implying an orange is '
                      'more than food? If so, what more might an orange be? What do you '
                      'think he means?',
                     'number': '', 'lines': 3},
                    {'text': 'Describe how eating an orange makes you feel.',
                     'number': '', 'lines': 3},
                    {'text': 'What stands out the most as you consider an orange that will help '
                      'you craft a compelling description of the fruit?',
                     'number': '', 'lines': 5},
                ],
            },
            {
                'heading': 'Begin to frame your idea:',
                'kind': 'other',
                'prompts': [
                ],
            },
            {
                'heading': 'The Thesis Statement »',
                'kind': 'idea_development',
                'instruction': 'Begin the process of writing your descriptive essay by first '
                    'developing a strong thesis statement. [arrow callout] The thesis '
                    'statement is the sentence that states the big idea of your essay. '
                    'There are three objectives of a thesis statement: 1. Your thesis '
                    'statement communicates the broad topic and the three sub-topics of'
                    ' your essay. 2. Your thesis statement tells the reader how you '
                    'will organize your thoughts in the essay. 3. Your thesis statement'
                    ' assures your reader your thoughtful idea is worth reading because'
                    ' you have a communication plan.',
                'prompts': [
                    {'text': 'What do you feel is most important to communicate to your audience'
                      ' about this topic?',
                     'number': '', 'lines': 3},
                    {'text': 'Brainstorm some potential sub-topics that will support your idea.',
                     'number': '', 'lines': 4},
                    {'text': 'Choose three sub-topics to focus on in your essay.\n\nSub-topic 1 of 3',
                     'number': '1.', 'lines': 1},
                    {'text': 'Sub-topic 2 of 3',
                     'number': '2.', 'lines': 1},
                    {'text': 'Sub-topic 3 of 3',
                     'number': '3.', 'lines': 1},
                    {'text': 'Now craft a thesis statement that introduces the reader to your '
                      'big idea by communicating these three sub-topics as the focus of '
                      'your essay. Refer back to the work you have done in Thinking In '
                      'Threes to help you.',
                     'number': '', 'lines': 4},
                ],
                'check_lead': 'Now ask yourself:',
                'checks': [
                    'Have I thought in threes?',
                    'Is my thesis statement written in parallel form (same grammatical '
                    'structure)?',
                    'Is my thesis statement interesting?',
                ],
            },
            {
                'heading': 'The Hook »',
                'kind': 'idea_development',
                'instruction': 'Now that you have your thesis statement written, develop a dynamic'
                    ' hook to start your essay. [arrow callout] The first sentence of '
                    'your essay should scream, "Fire!" Not really, but your hook should'
                    " grab your reader's attention, spark some curiosity, and draw them"
                    ' into your big idea. Your hook can: » be an exaggeration or make '
                    'an outrageous statement » be a metaphor or mystery » state a '
                    'strong fact or staggering statistic » be a famous quotation » ask '
                    'a poignant question » be a quirky one-sentence anecdote',
                'prompts': [
                    {'text': 'Write three different hooks that experiment with some of the '
                      'previous tips.',
                     'number': '', 'lines': 9},
                    {'text': 'Choose your favorite hook and refine it.',
                     'number': '', 'lines': 3},
                ],
                'check_lead': 'Now ask yourself:',
                'checks': [
                    "Will my hook grab the reader's attention and spark some curiosity?",
                ],
            },
            {
                'heading': 'Body Paragraphs »',
                'kind': 'idea_development',
                'instruction': 'Now that you have a hook, a thesis statement, and three sub-'
                    'topics, work through this body paragraph warm-up exercise. This '
                    'will help as you begin to craft each of the three body paragraphs '
                    'in your descriptive essay. [arrow callout] Remember, begin with '
                    'factual details that "tell" the reader about your topic. Then '
                    'write a sentence providing specific sensory details to "show" and '
                    'expand on the information. Example: PARAGRAPH OPENER: Light plays '
                    'an important role in developing the atmosphere of a scene. FACTUAL'
                    ' (TELL): Imagine, for example, shining a light on the front of a '
                    'pear and its shadow enlarging. SENSORY (SHOW): This makes the '
                    'scene moody, almost frightening. FACTUAL (TELL): If you shine that'
                    ' same light source on the back of the pear, its shadow will '
                    'shrink. SENSORY (SHOW): This makes the scene less intimidating, '
                    'more inviting. Now write the final pair of sentences and the '
                    'clincher.',
                'prompts': [
                    {'text': 'FACTUAL (TELL):',
                     'number': '', 'lines': 2},
                    {'text': 'SENSORY (SHOW):',
                     'number': '', 'lines': 2},
                    {'text': 'CLINCHER:',
                     'number': '', 'lines': 2},
                ],
            },
            {
                'heading': 'The Essay »',
                'kind': 'other',
                'instruction': 'Now that you have a hook, a thesis statement, and three sub-'
                    'topics, begin crafting a descriptive essay describing orange. '
                    'Review page 10 and make sure you work through all stages of the '
                    'writing process. 1. Hand write your rough draft on the following '
                    'pages incorporating all the pre-writing you have done in this '
                    'lesson. 2. Type your final draft with double line spacing and '
                    '1-inch margins. Be sure to insert your final draft into this '
                    'binder following your rough draft. [arrow callout] As you work '
                    'through the process of writing your descriptive essay, ask '
                    'yourself the following questions frequently: » Do I believe what I'
                    ' am writing about? » Am I following the blueprint? » Have I read '
                    'through each draft of my essay?',
                'prompts': [
                ],
            },
        ],
        'notes': [
            {'where': 'odd',
             'text': 'The guide asks about “complimentary colors” and tells you to go '
                      'and research it. The colour-theory word is COMPLEMENTARY — colours'
                      ' that complete each other, like blue and orange. “Complimentary” '
                      'means flattering, or free of charge. Research the one the guide '
                      'means, not the one it spells.'},
            {'where': 'even',
             'text': 'On the blueprint checklist the last paragraph is labelled “PS» '
                      'CONCLUSION”. That is a typo for “P5»” — it is paragraph 5, the '
                      'conclusion. Lessons 2 and 4 print it correctly, which is how we '
                      'know.'},
        ],
    },
    {
        'number': 2,
        'title': 'Write a Person',
        'weeks': (3, 4),
        'banner': 'Remember: The descriptive essay describes something very '
            "specifically using details to spark the reader's senses. Through "
            'this essay you have an opportunity to explore details that make '
            'something unique and share your discovery so your audience might '
            'experience what you describe.',
        'vocabulary': ['appearance', 'behavior'],
        'steps': [
            {
                'heading': 'Complete the following:',
                'kind': 'observation',
                'prompts': [
                    {'text': 'Choose a specific individual you know well to describe.',
                     'number': '', 'lines': 1},
                    {'text': 'Describe your relationship to this person.',
                     'number': '', 'lines': 2},
                    {'text': "Describe the person's appearance in detail.",
                     'number': '', 'lines': 7},
                    {'text': "Describe the person's behavior in detail:",
                     'number': '', 'lines': 4},
                    {'text': 'What makes this individual unique?',
                     'number': '', 'lines': 4},
                    {'text': 'What quirks does this person possess?',
                     'number': '', 'lines': 3},
                    {'text': 'What behaviors do you find annoying?',
                     'number': '', 'lines': 3},
                    {'text': 'What do you find endearing about this person?',
                     'number': '', 'lines': 3},
                    {'text': 'List the details you find most intriguing about this individual.',
                     'number': '', 'lines': 5},
                    {'text': 'What stands out the most as you consider this person that will '
                      'help you craft a compelling description?',
                     'number': '', 'lines': 5},
                ],
            },
            {
                'heading': 'Begin to frame your idea:',
                'kind': 'idea_development',
                'prompts': [
                ],
            },
            {
                'heading': 'The Thesis Statement »',
                'kind': 'idea_development',
                'instruction': 'Begin the process of writing your descriptive essay by first '
                    'developing a strong thesis statement. [arrow callout] The thesis '
                    'statement is the sentence that states the big idea of your essay. '
                    'There are three objectives of a thesis statement: 1. Your thesis '
                    'statement communicates the broad topic and the three sub-topics of'
                    ' your essay. 2. Your thesis statement tells the reader how you '
                    'will organize your thoughts in the essay. 3. Your thesis statement'
                    ' assures your reader your thoughtful idea is worth reading because'
                    ' you have a communication plan.',
                'prompts': [
                    {'text': 'What do you feel is most important to communicate to your audience'
                      ' about this topic?',
                     'number': '', 'lines': 3},
                    {'text': 'Brainstorm some potential sub-topics that will support your idea.',
                     'number': '', 'lines': 5},
                    {'text': 'Choose three sub-topics to focus on in your essay.\n\nSub-topic 1 of 3',
                     'number': '1.', 'lines': 1},
                    {'text': 'Sub-topic 2 of 3',
                     'number': '2.', 'lines': 1},
                    {'text': 'Sub-topic 3 of 3',
                     'number': '3.', 'lines': 1},
                    {'text': 'Now craft a thesis statement that introduces the reader to your '
                      'big idea by communicating these three sub-topics as the focus of '
                      'your essay. Refer back to the work you have done in Thinking In '
                      'Threes to help you.',
                     'number': '', 'lines': 4},
                ],
                'check_lead': 'Now ask yourself:',
                'checks': [
                    'Have I thought in threes?',
                    'Is my thesis statement written in parallel form (same grammatical '
                    'structure)?',
                    'Is my thesis statement interesting?',
                ],
            },
            {
                'heading': 'The Hook »',
                'kind': 'idea_development',
                'instruction': 'Now that you have your thesis statement written, develop a dynamic'
                    ' hook to start your essay. [arrow callout] The first sentence of '
                    'your essay should scream, "Fire!" Not really, but your hook should'
                    " grab your reader's attention, spark some curiosity, and draw them"
                    ' into your big idea. Your hook can: » be an exaggeration or make '
                    'an outrageous statement » be a metaphor or mystery » state a '
                    'strong fact or staggering statistic » be a famous quotation » ask '
                    'a poignant question » be a quirky one-sentence anecdote',
                'prompts': [
                    {'text': 'Write three different hooks that experiment with some of the '
                      'previous tips.',
                     'number': '', 'lines': 9},
                    {'text': 'Choose your favorite hook and refine it.',
                     'number': '', 'lines': 3},
                ],
                'check_lead': 'Now ask yourself:',
                'checks': [
                    "Will my hook grab the reader's attention and spark some curiosity?",
                ],
            },
            {
                'heading': 'Body Paragraphs »',
                'kind': 'idea_development',
                'instruction': 'Now that you have a hook, a thesis statement, and three sub-'
                    'topics, work through this body paragraph exercise. This will help '
                    'as you begin to craft each of the three body paragraphs in your '
                    'descriptive essay. [arrow callout] Remember, begin with factual '
                    'details that "tell" the reader about your topic. Then write a '
                    'sentence providing specific sensory details to "show" and expand '
                    'on the information. Choose one of your three sub-topics from page '
                    '32 and outline three pairs of factual and sensory details to '
                    'support it:',
                'prompts': [
                    {'text': '1a. FACTUAL (TELL):',
                     'number': '', 'lines': 2},
                    {'text': '1b. SENSORY (SHOW):',
                     'number': '', 'lines': 2},
                    {'text': '2a. FACTUAL (TELL):',
                     'number': '', 'lines': 2},
                    {'text': '2b. SENSORY (SHOW):',
                     'number': '', 'lines': 2},
                    {'text': '3a. FACTUAL (TELL):',
                     'number': '', 'lines': 2},
                    {'text': '3b. SENSORY (SHOW):',
                     'number': '', 'lines': 3},
                ],
            },
            {
                'heading': 'The Essay »',
                'kind': 'idea_development',
                'instruction': 'Now that you have a hook, a thesis statement, three sub-topics, '
                    'and one body paragraph outlined, begin crafting a descriptive '
                    'essay describing a person. Review page 10 and make sure you work '
                    'through all stages of the writing process. [arrow callout] As you '
                    'work through the process of writing your descriptive essay, ask '
                    'yourself the following questions frequently: » Do I believe what I'
                    ' am writing about? » Am I following the blueprint? » Have I read '
                    'through each draft of my essay? Hand write your rough draft on the'
                    ' following pages incorporating all the pre-writing you have done '
                    'in this lesson. Type your final draft with double line spacing and'
                    ' 1-inch margins. Be sure to insert your final draft into this '
                    'binder following your rough draft.',
                'prompts': [
                ],
            },
        ],
        'notes': [
            {'where': 'odd',
             'text': 'Two tasks this lesson send you to an exercise called “Thinking In '
                      'Threes”. There is no such section in this volume — it is in '
                      'another book in the series. What it means is the thing the thesis '
                      'statement work has been doing all along: three sub-topics, phrased'
                      ' in the same grammatical shape.'},
        ],
    },
    {
        'number': 3,
        'title': 'Write an Object',
        'weeks': (5, 6),
        'banner': 'Remember, the descriptive essay describes something very '
            "specifically using details to spark the reader's senses. Through "
            'this essay you have an opportunity to explore details that make '
            'something unique and share your discovery so your audience might '
            'experience what you describe.',
        'vocabulary': ['light', 'shadow', 'atmosphere'],
        'steps': [
            {
                'heading': 'Complete the following:',
                'kind': 'observation',
                'prompts': [
                    {'text': 'Choose an inanimate object to describe (soccer ball, shoe, remote '
                      'control, etc.).',
                     'number': '', 'lines': 1},
                    {'text': 'Describe the object.',
                     'number': '', 'lines': 5},
                    {'text': 'List the details you find most intriguing about this object.',
                     'number': '', 'lines': 5},
                    {'text': 'Impressionist painter, Claude Monet said, ”For me, a landscape '
                      'does not exist in its own right, since its appearance changes at '
                      'every moment; but the surrounding atmosphere brings it to life—the'
                      ' light and the air which vary continually. For me, it is only the '
                      'surrounding atmosphere which gives subjects their true value.” '
                      'What do you think he means?',
                     'number': '', 'lines': 5},
                    {'text': 'Place your object in bright sunshine, near a bright lamp, or shine'
                      " a flashlight directly on the object and observe how the object's "
                      'features look in direct light.',
                     'number': '', 'lines': 5},
                    {'text': 'Now change the surrounding atmosphere by placing the object in a '
                      'place where very little light exists. You might try placing it '
                      'beneath a cloth and lifting the cloth so you are observing the '
                      'object in low light or place the object in a box and lift the lid '
                      "slightly, peeking at the object in shadow. How do the object's "
                      'features change in different levels of light?',
                     'number': '', 'lines': 6},
                ],
            },
            {
                'heading': 'Begin to frame your idea:',
                'kind': 'idea_development',
                'prompts': [
                ],
            },
            {
                'heading': 'The Thesis Statement »',
                'kind': 'idea_development',
                'instruction': 'Begin the process of writing your descriptive essay by first '
                    'developing a strong thesis statement. [arrow callout] The thesis '
                    'statement is the sentence that states the big idea of your essay. '
                    'There are three objectives of a thesis statement: 1. Your thesis '
                    'statement communicates the broad topic and the three sub-topics of'
                    ' your essay. 2. Your thesis statement tells the reader how you '
                    'will organize your thoughts in the essay. 3. Your thesis statement'
                    ' assures your reader your thoughtful idea is worth reading because'
                    ' you have a communication plan.',
                'prompts': [
                    {'text': 'What do you feel is most important to communicate to your audience'
                      ' about this topic?',
                     'number': '', 'lines': 3},
                    {'text': 'Brainstorm some potential sub-topics that will support your idea.',
                     'number': '', 'lines': 5},
                    {'text': 'Choose three sub-topics to focus on in your essay.\n\nSub-topic 1 of 3',
                     'number': '1.', 'lines': 1},
                    {'text': 'Sub-topic 2 of 3',
                     'number': '2.', 'lines': 1},
                    {'text': 'Sub-topic 3 of 3',
                     'number': '3.', 'lines': 1},
                    {'text': 'Now craft a thesis statement that introduces the reader to your '
                      'big idea by communicating these three sub-topics as the focus of '
                      'your essay. Refer back to the work you have done in Thinking In '
                      'Threes to help you.',
                     'number': '', 'lines': 4},
                ],
                'check_lead': 'Now ask yourself:',
                'checks': [
                    'Have I thought in threes?',
                    'Is my thesis statement written in parallel form (same grammatical '
                    'structure)?',
                    'Is my thesis statement interesting?',
                ],
            },
            {
                'heading': 'The Hook »',
                'kind': 'idea_development',
                'instruction': 'Now that you have your thesis statement written, develop a dynamic'
                    ' hook to start your essay. [arrow callout] The first sentence of '
                    'your essay should scream, “Fire!” Not really, but your hook should'
                    " grab your reader's attention, spark some curiosity, and draw them"
                    ' into your big idea. Your hook can: » be an exaggeration or make '
                    'an outrageous statement » be a metaphor or mystery » state a '
                    'strong fact or staggering statistic » be a famous quotation » ask '
                    'a poignant question » be a quirky one-sentence anecdote',
                'prompts': [
                    {'text': 'Write three different hooks that experiment with some of the '
                      'previous tips.',
                     'number': '', 'lines': 7},
                    {'text': 'Choose your favorite hook and refine it.',
                     'number': '', 'lines': 3},
                ],
                'check_lead': 'Now ask yourself:',
                'checks': [
                    "Will my hook grab the reader's attention and spark some curiosity?",
                ],
            },
            {
                'heading': 'Body Paragraphs »',
                'kind': 'idea_development',
                'instruction': 'Now that you have a hook, a thesis statement, and three sub-'
                    'topics, work through this body paragraph warm-up exercise. This '
                    'will help as you begin to craft each of the three body paragraphs '
                    'in your descriptive essay. [arrow callout] Remember, begin with '
                    'factual details that “tell” the reader about your topic. Then '
                    'write a sentence providing specific sensory details to “show” and '
                    'expand on the information. Choose one of your three sub-topics '
                    'from page 42 and outline three pairs of factual and sensory '
                    'details to support it:',
                'prompts': [
                    {'text': 'FACTUAL (TELL):',
                     'number': '1a.', 'lines': 2},
                    {'text': 'SENSORY (SHOW):',
                     'number': '1b.', 'lines': 2},
                    {'text': 'FACTUAL (TELL):',
                     'number': '2a.', 'lines': 2},
                    {'text': 'SENSORY (SHOW):',
                     'number': '2b.', 'lines': 2},
                    {'text': 'FACTUAL (TELL):',
                     'number': '3a.', 'lines': 2},
                    {'text': 'SENSORY (SHOW):',
                     'number': '3b.', 'lines': 2},
                ],
            },
            {
                'heading': 'The Essay »',
                'kind': 'other',
                'instruction': 'Now that you have a hook, a thesis statement, three sub-topics, '
                    'and one body paragraph outlined, begin crafting a descriptive '
                    'essay describing an object. Review page 10 and make sure you work '
                    'through all stages of the writing process. [arrow callout] As you '
                    'work through the process of writing your descriptive essay, ask '
                    'yourself the following questions frequently: » Do I believe what I'
                    ' am writing about? » Am I following the blueprint? » Have I read '
                    'through each draft of my essay? Hand write your rough draft on the'
                    ' following pages incorporating all the pre-writing you have done '
                    'in this lesson. Type your final draft with double line spacing and'
                    ' 1-inch margins. Be sure to insert your final draft into this '
                    'binder following your rough draft.',
                'prompts': [
                ],
            },
        ],
        'notes': [
            {'where': 'odd',
             'text': 'A task this lesson refers back to “Thinking In Threes”, which is '
                      'not a section in this volume. It means your three sub-topics, '
                      'phrased in matching form.'},
            {'where': 'odd',
             'text': 'The Monet quotation opens with the wrong curly quote — the mark '
                      'that should close a quotation is used to open it. Copy the words, '
                      'not the typo.'},
            {'where': 'even',
             'text': 'On the blueprint checklist the last paragraph is labelled “PS» '
                      'CONCLUSION”. That is a typo for “P5»” — it is paragraph 5, the '
                      'conclusion. Lessons 2 and 4 print it correctly, which is how we '
                      'know.'},
        ],
    },
    {
        'number': 4,
        'title': 'Write a Photograph',
        'weeks': (7, 8),
        'banner': 'Remember, the descriptive essay describes something very '
            'specifically using details to spark the reader’s senses. Through '
            'this essay you have an opportunity to explore details that make '
            'something unique and share your discovery so your audience might '
            'experience what you describe.',
        'vocabulary': ['photograph', 'province', 'mood'],
        'steps': [
            {
                'heading': 'Complete the following:',
                'kind': 'observation',
                'prompts': [
                    {'text': 'Choose a photograph to write about. Is the event a landscape, a '
                      'celebration, a vacation? Name the event three different ways.',
                     'number': '', 'lines': 3},
                    {'text': 'Describe the event being photographed. Be sure to describe the '
                      'details of the event through vivid sensory language.',
                     'number': '', 'lines': 10},
                    {'text': 'Describe the mood of the photograph you chose.',
                     'number': '', 'lines': 3},
                    {'text': 'Is the photograph color or black and white? If the photograph is '
                      'printed in color, imagine it in black and white. If it is in black'
                      ' and white, imagine its details in color.',
                     'number': '', 'lines': 3},
                    {'text': 'Photographer Dorothea Lange reminds us, “While there is perhaps a '
                      'province in which the photograph can tell us nothing more than '
                      'what we see with our own eyes, there is another in which it proves'
                      ' to us how little our eyes permit us to see.” What do you think '
                      'she means?',
                     'number': '', 'lines': 3},
                    {'text': 'What stands out the most as you consider this photograph that will'
                      ' help you craft a compelling description?',
                     'number': '', 'lines': 5},
                ],
            },
            {
                'heading': 'Begin to frame your idea:',
                'kind': 'idea_development',
                'prompts': [
                ],
            },
            {
                'heading': 'The Thesis Statement »',
                'kind': 'idea_development',
                'instruction': 'Begin the process of writing your descriptive essay by first '
                    'developing a strong thesis statement. [arrow callout] The thesis '
                    'statement is the sentence that states the big idea of your essay. '
                    'There are three objectives of a thesis statement: 1. Your thesis '
                    'statement communicates the broad topic and the three sub-topics of'
                    ' your essay. 2. Your thesis statement tells the reader how you '
                    'will organize your thoughts in the essay. 3. Your thesis statement'
                    ' assures your reader that your thoughtful idea is worth reading '
                    'because you have a communication plan.',
                'prompts': [
                    {'text': 'What do you feel is most important to communicate to your audience'
                      ' about this photograph?',
                     'number': '', 'lines': 3},
                    {'text': 'Brainstorm some potential sub-topics that will support your idea.',
                     'number': '', 'lines': 5},
                    {'text': 'Choose three sub-topics to focus on in your essay.\n\nSub-topic 1 of 3',
                     'number': '1.', 'lines': 1},
                    {'text': 'Sub-topic 2 of 3',
                     'number': '2.', 'lines': 1},
                    {'text': 'Sub-topic 3 of 3',
                     'number': '3.', 'lines': 1},
                    {'text': 'Now craft a thesis statement that introduces the reader to your '
                      'big idea by communicating these three sub-topics as the focus of '
                      'your essay. Refer back to the work you have done in Thinking In '
                      'Threes to help you.',
                     'number': '', 'lines': 4},
                ],
                'check_lead': 'Now ask yourself:',
                'checks': [
                    'Have I thought in threes?',
                    'Is my thesis statement written in parallel form (same grammatical '
                    'structure)?',
                    'Is my thesis statement interesting?',
                ],
            },
            {
                'heading': 'The Hook »',
                'kind': 'idea_development',
                'instruction': 'Now that you have your thesis statement written, develop a dynamic'
                    ' hook to start your essay. [arrow callout] The first sentence of '
                    'your essay should scream, “Fire!” Not really, but your hook should'
                    ' grab your reader’s attention, spark some curiosity, and draw them'
                    ' into your big idea. Your hook can: » be an exaggeration or make '
                    'an outrageous statement » be a metaphor or mystery » state a '
                    'strong fact or staggering statistic » be a famous quotation » ask '
                    'a poignant question » be a quirky one-sentence anecdote',
                'prompts': [
                    {'text': 'Write three different hooks that experiment with some of the '
                      'previous tips.',
                     'number': '', 'lines': 7},
                    {'text': 'Choose your favorite hook and refine it.',
                     'number': '', 'lines': 3},
                ],
                'check_lead': 'Now ask yourself:',
                'checks': [
                    'Will my hook grab the reader’s attention and spark some curiosity?',
                ],
            },
            {
                'heading': 'Body Paragraphs »',
                'kind': 'idea_development',
                'instruction': 'Now that you have a hook, a thesis statement, and three sub-'
                    'topics, work through this body paragraph warm-up exercise. This '
                    'will help as you begin to craft each of the three body paragraphs '
                    'in your descriptive essay. [arrow callout] Remember, begin with '
                    'factual details that “tell” the reader about your topic. Then '
                    'write a sentence providing specific sensory details to “show” and '
                    'expand on the information. Choose one of your three sub-topics '
                    'from page 53 and outline three pairs of factual and sensory '
                    'details to support it:',
                'prompts': [
                    {'text': 'FACTUAL (TELL):',
                     'number': '1a.', 'lines': 2},
                    {'text': 'SENSORY (SHOW):',
                     'number': '1b.', 'lines': 2},
                    {'text': 'FACTUAL (TELL):',
                     'number': '2a.', 'lines': 2},
                    {'text': 'SENSORY (SHOW):',
                     'number': '2b.', 'lines': 2},
                    {'text': 'FACTUAL (TELL):',
                     'number': '3a.', 'lines': 2},
                    {'text': 'SENSORY (SHOW):',
                     'number': '3b.', 'lines': 2},
                ],
            },
            {
                'heading': 'The Essay »',
                'kind': 'other',
                'instruction': 'Now that you have a hook, a thesis statement, three sub-topics, '
                    'and one body paragraph outlined, begin crafting a descriptive '
                    'essay describing a photograph. Review page 10 and make sure you '
                    'work through all stages of the writing process. 1. Hand write your'
                    ' rough draft on the following pages incorporating all the pre-'
                    'writing you have done in this lesson. 2. Type your final draft '
                    'with double line spacing and 1-inch margins. Be sure to insert '
                    'your final draft into this binder following your rough draft. '
                    '[arrow callout] As you work through the process of writing your '
                    'descriptive essay, ask yourself the following questions '
                    'frequently: » Do I believe what I am writing about? » Am I '
                    'following the blueprint? » Have I read through each draft of my '
                    'essay?',
                'prompts': [
                ],
            },
        ],
    },
    {
        'number': 5,
        'title': 'Write a Room',
        'weeks': (9, 10),
        'banner': 'Remember, the descriptive essay describes something very '
            'specifically using details to spark the reader’s senses. Through '
            'this essay you have an opportunity to explore details that make '
            'something unique and share your discovery so your audience might '
            'experience what you describe.',
        'vocabulary': ['place', 'pride', 'order', 'chaos'],
        'steps': [
            {
                'heading': 'Complete the following:',
                'kind': 'observation',
                'prompts': [
                    {'text': 'Describe a room in your house. What is the function of this room?',
                     'number': '', 'lines': 4},
                    {'text': 'Describe the room in detail. Be sure to describe the details using'
                      ' vivid sensory language.',
                     'number': '', 'lines': 7},
                    {'text': 'On a spectrum where order is at one end and chaos at the other, '
                      'where would this room fall? Support your answer with details.',
                     'number': '', 'lines': 4},
                    {'text': 'Is an ordered room pleasant or disturbing? Explain your answer in '
                      'detail.',
                     'number': '', 'lines': 3},
                    {'text': 'Is a chaotic room pleasant or disturbing? Explain your answer in '
                      'detail.',
                     'number': '', 'lines': 3},
                    {'text': 'Abraham Lincoln said, "I like to see a man proud of the place in '
                      'which he lives. I like to see a man live so that his place will be'
                      ' proud of him." Are you proud of your room? Do you think your room'
                      ' is proud of you? Why or why not? What would Abraham Lincoln think'
                      ' of your room?',
                     'number': '', 'lines': 5},
                    {'text': 'List the details you find most intriguing about this room:',
                     'number': '', 'lines': 6},
                ],
            },
            {
                'heading': 'Begin to frame your idea:',
                'kind': 'idea_development',
                'prompts': [
                ],
            },
            {
                'heading': 'The Thesis Statement »',
                'kind': 'idea_development',
                'instruction': 'Begin the process of writing your descriptive essay by first '
                    'developing a strong thesis statement. [arrow callout] The thesis '
                    'statement is the sentence that states the big idea of your essay. '
                    'There are three objectives of a thesis statement: 1. Your thesis '
                    'statement communicates the broad topic and the three sub-topics of'
                    ' your essay. 2. Your thesis statement tells the reader how you '
                    'will organize your thoughts in the essay. 3. Your thesis statement'
                    ' assures your reader your thoughtful idea is worth reading because'
                    ' you have a communication plan.',
                'prompts': [
                    {'text': 'What do you feel is most important to communicate to your audience'
                      ' about this topic?',
                     'number': '', 'lines': 3},
                    {'text': 'Brainstorm some potential sub-topics that will support your idea.',
                     'number': '', 'lines': 5},
                    {'text': 'Choose three sub-topics to focus on in your essay.\n\nSub-topic 1 of 3',
                     'number': '1.', 'lines': 1},
                    {'text': 'Sub-topic 2 of 3',
                     'number': '2.', 'lines': 1},
                    {'text': 'Sub-topic 3 of 3',
                     'number': '3.', 'lines': 1},
                    {'text': 'Now craft a thesis statement that introduces the reader to your '
                      'big idea by communicating these three sub-topics as the focus of '
                      'your essay. Refer back to the work you have done in Thinking In '
                      'Threes to help you.',
                     'number': '', 'lines': 4},
                ],
                'check_lead': 'Now ask yourself:',
                'checks': [
                    'Have I thought in threes?',
                    'Is my thesis statement written in parallel form (same grammatical '
                    'structure)?',
                    'Is my thesis statement interesting?',
                ],
            },
            {
                'heading': 'The Hook »',
                'kind': 'idea_development',
                'instruction': 'Now that you have your thesis statement written, develop a dynamic'
                    ' hook to start your essay. [arrow callout] The first sentence of '
                    'your essay should scream, “Fire!” Not really, but your hook should'
                    ' grab your reader’s attention, spark some curiosity, and draw them'
                    ' into your big idea. Your hook can: » be an exaggeration or make '
                    'an outrageous statement » be a metaphor or mystery » state a '
                    'strong fact or staggering statistic » be a famous quotation » ask '
                    'a poignant question » be a quirky one-sentence anecdote',
                'prompts': [
                    {'text': 'Write three different hooks that experiment with some of the '
                      'previous tips.',
                     'number': '', 'lines': 9},
                    {'text': 'Choose your favorite hook and refine it.',
                     'number': '', 'lines': 3},
                ],
                'check_lead': 'Now ask yourself:',
                'checks': [
                    'Will my hook grab the reader’s attention and spark some curiosity?',
                ],
            },
            {
                'heading': 'Body Paragraphs »',
                'kind': 'idea_development',
                'instruction': 'Now that you have a hook, a thesis statement, and three sub-'
                    'topics, work through this body paragraph warm-up exercise. This '
                    'will help as you begin to craft each of the three body paragraphs '
                    'in your descriptive essay. [arrow callout] Remember, begin with '
                    'factual details that “tell” the reader about your topic. Then '
                    'write a sentence providing specific sensory details to “show” and '
                    'expand on the information. Choose one of your three sub-topics '
                    'from page 65 and outline three pairs of factual and sensory '
                    'details to support it:',
                'prompts': [
                    {'text': 'FACTUAL (TELL):',
                     'number': '1a.', 'lines': 2},
                    {'text': 'SENSORY (SHOW):',
                     'number': '1b.', 'lines': 2},
                    {'text': 'FACTUAL (TELL):',
                     'number': '2a.', 'lines': 2},
                    {'text': 'SENSORY (SHOW):',
                     'number': '2b.', 'lines': 2},
                    {'text': 'FACTUAL (TELL):',
                     'number': '3a.', 'lines': 2},
                    {'text': 'SENSORY (SHOW):',
                     'number': '3b.', 'lines': 2},
                ],
            },
            {
                'heading': 'The Essay »',
                'kind': 'rough_draft',
                'instruction': 'Now that you have a hook, a thesis statement, three sub-topics, '
                    'and one body paragraph outlined, begin crafting a descriptive '
                    'essay describing a room. Review page 10 and make sure you work '
                    'through all stages of the writing process. [arrow callout] As you '
                    'work through the process of writing your descriptive essay, ask '
                    'yourself the following questions frequently: » Do I believe what I'
                    ' am writing about? » Am I following the blueprint? » Have I read '
                    'through each draft of my essay? Hand write your rough draft on the'
                    ' following pages incorporating all the pre-writing you have done '
                    'in this lesson. Type your final draft with double line spacing and'
                    ' 1-inch margins. Be sure to insert your final draft into this '
                    'binder following your rough draft.',
                'prompts': [
                ],
            },
        ],
        'notes': [
            {'where': 'even',
             'text': 'On the blueprint checklist the last paragraph is labelled “PS» '
                      'CONCLUSION”. That is a typo for “P5»” — it is paragraph 5, the '
                      'conclusion. Lessons 2 and 4 print it correctly, which is how we '
                      'know.'},
        ],
    },
]
