# Generated by Django 6.0.1 on 2026-07-07 23:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assignments', '0006_assignmentresourcelink_link_type_and_more'),
        ('core', '0004_invitation_resent_at'),
        ('curricula', '0003_curriculum_website_url'),
        ('students', '0002_student_family'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate, help_text='The day this work was done.')),
                ('subject', models.CharField(help_text="e.g., 'Math', 'Reading', 'Nature walk'.", max_length=100)),
                ('description', models.TextField(blank=True, help_text='What did they do? What did you observe?')),
                ('attachment', models.FileField(blank=True, help_text='Optional photo or file of the work.', upload_to='work_log/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_log_entries', to='assignments.assignment')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_log_entries', to='students.student')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_work_log_entries', to=settings.AUTH_USER_MODEL)),
                ('curriculum', models.ForeignKey(blank=True, help_text='Optional: link this work to a curriculum.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_log_entries', to='curricula.curriculum')),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_log_entries', to='core.family')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_log_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'work log entry',
                'verbose_name_plural': 'work log entries',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
