# Generated by Django 6.0.1 on 2026-08-06 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worklog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worklogentry',
            name='minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Optional: minutes spent, for your hours / attendance report. Parent-only — never shown to the child.', null=True),
        ),
    ]
