# Generated by Django 5.0.14 on 2026-01-28 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("in_progress", "In Progress"),
                    ("submitted", "Submitted"),
                    ("complete", "Complete"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
