# Generated by Django 6.0.1 on 2026-01-28 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0002_alter_assignment_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssignmentResourceLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("url", models.URLField()),
                ("label", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resource_links",
                        to="assignments.assignment",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
