# Generated by Django 6.0.1 on 2026-01-31 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0005_assignment_created_by_assignment_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentresourcelink',
            name='link_type',
            field=models.CharField(choices=[('resource', 'Resource'), ('assessment', 'Assessment')], default='resource', max_length=20),
        ),
        migrations.AddField(
            model_name='assignmentresourcelink',
            name='window_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignmentresourcelink',
            name='window_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assignmentresourcelink',
            name='label',
            field=models.CharField(max_length=200),
        ),
    ]
