"""Seed the adult travel phrasebook (LGA-103).

Idempotent: get_or_create keyed on ``(text, category)`` — the same sentence can
legitimately belong to two situations, and a person reaches for it in whichever one
they are standing in.

PROVENANCE. Every phrase here was written for this app and then checked by a second
pass for Mexican usage, register and correctness. NOTHING is transcribed from a
published phrasebook — not TalkBox, not Lonely Planet, not any commercial product.
That is a hard line (the same one D-47 draws for story text), and it is enforced by
this file being a literal list reviewed in the diff rather than an import.

es-MX throughout, USTED by default: an adult is speaking to strangers and service
staff. Phrases are short enough to say under pressure — anything needing a
subordinate clause was cut.

    python manage.py seed_travel_phrases
"""
from django.core.management.base import BaseCommand

from lingua.models import TravelPhrase

# (text, english, note)
PHRASES = {
    # --- Conversar — greetings, and buying goodwill ---
    TravelPhrase.SMALLTALK: [
        ("Buenos días.",
         "Good morning.",
         "After about 1pm switch to \"Buenas tardes\", after dark \"Buenas noches\". A plain \"Buenas\" works at any hour if you blank on which one."),
        ("¿Cómo está?",
         "How are you?",
         "You'll hear \"Bien, gracias, ¿y usted?\" Answer \"Bien, gracias.\" That whole exchange is the price of admission almost everywhere."),
        ("Disculpe, ¿me puede ayudar?",
         "Excuse me, can you help me?",
         "\"Disculpe\" is how you flag down a stranger or a clerk. Use \"Con permiso\" instead when you only need to get past someone."),
        ("Estoy aprendiendo español.",
         "I'm learning Spanish.",
         "Say it in the first ten seconds. People slow down and get patient once they know. \"Hablo un poquito de español\" lands the same way."),
        ("¿Puede hablar más despacio, por favor?",
         "Could you speak more slowly, please?",
         "des-PAH-see-oh. Don't reach for \"lento\" — despacio is the word here."),
        ("¿Me lo repite, por favor?",
         "Could you say that again?",
         "For when you missed the whole sentence. If you only missed a word, \"¿Mande?\" is the classic Mexican one — \"¿Cómo?\" works too."),
        ("Mucho gusto, me llamo ______.",
         "Nice to meet you, my name is ______.",
         "Expect \"Igualmente\" or \"El gusto es mío\" back — both just mean likewise."),
        ("Ellas son mis hijas.",
         "These are my daughters.",
         "hijas = EE-has. The h is silent and the j is a soft throat-h."),
        ("Tienen nueve y doce años.",
         "They're nine and twelve.",
         "Press the ñ — AH-nyos. \"Anos\" without it means something you do not want to say about your kids."),
        ("Con permiso.",
         "Excuse me — coming through.",
         "Squeezing past someone, leaving a table, stepping into an elevator. The polite reply is \"Propio\" or \"Pásele\"."),
        ("Muchas gracias, muy amable.",
         "Thank you very much, that's kind of you.",
         "\"Muy amable\" is what turns a plain thanks into warmth. You may hear \"Para servirle\" back — it just means you're welcome."),
        ("Que tenga buen día.",
         "Have a good day.",
         "Your exit line. In the evening: \"Que tenga buena noche.\" Mexicans just as often say \"Que le vaya bien.\""),
    ],
    # --- Llegada — immigration, bags, the taxi ---
    TravelPhrase.AIRPORT: [
        ("Aquí están nuestros pasaportes.",
         "Here are our passports.",
         "Hand over all three at once. The officer will then ask \"¿Motivo de su viaje?\" — the reason for your trip."),
        ("Vengo de vacaciones con mis hijas.",
         "I'm here on vacation with my daughters.",
         "The answer to \"¿Motivo de su viaje?\" Say \"hijas\" (EE-hahs), not \"niñas\" — it makes the relationship clear."),
        ("¿Me lo repite más despacio, por favor?",
         "Could you say that again, slower?",
         "Use this the moment you lose the thread. Officers repeat without any fuss; guessing at an answer causes more delay."),
        ("Nos quedamos diez días.",
         "We're staying ten days.",
         "For \"¿Cuánto tiempo va a estar en el país?\" Swap the number: cinco, siete, quince."),
        ("Nos vamos a quedar en el Hotel Marina.",
         "We're staying at the Hotel Marina.",
         "The question may come as \"¿Dónde se van a hospedar?\" (os-peh-DAR, silent h) — this answers it either way. Have the booking on your phone in case they want the address."),
        ("No traigo nada que declarar.",
         "I have nothing to declare.",
         "For customs. You may still press the button and get the red light — that's random, not suspicion. Just follow them to the table."),
        ("Solo ropa y cosas personales.",
         "Just clothes and personal things.",
         "Use this when they open a bag and ask what's inside."),
        ("¿Por dónde salen las maletas?",
         "Where do the bags come out?",
         "Signs read \"Equipaje\" or \"Reclamo de equipaje\". The carousel itself is \"la banda\" — that's the word someone will use when they point."),
        ("Falta una maleta. ¿Con quién la reporto?",
         "One bag is missing. Who do I report it to?",
         "They will ask for \"su talón\" — the little baggage tag stuck to your boarding pass. Don't throw it away."),
        ("¿Dónde están los taxis autorizados?",
         "Where are the official taxis?",
         "At Mexican airports you buy the taxi at a counter inside before going out. Ignore anyone who approaches you first."),
        ("¿Cuánto me cobra al centro?",
         "How much to downtown?",
         "Ask this at the taxi counter — fares are fixed by zone and you pay before you walk out. If a driver quotes you directly outside instead, settle the number before the bags go in the trunk."),
        ("Al Hotel Marina, por favor.",
         "To the Hotel Marina, please.",
         "If he asks \"¿Por dónde queda?\", show the address on your phone and say \"Aquí está la dirección.\""),
    ],
    # --- El hotel — checking in and asking for things ---
    TravelPhrase.HOTEL: [
        ("Buenas tardes, vengo a registrarme.",
         "Good afternoon — I'm here to check in.",
         "Say buenos días before about 1pm, buenas tardes after, buenas noches once it's dark. Greeting first is not optional in Mexico; skipping it reads as cold."),
        ("Tengo una reservación a nombre de López.",
         "I have a reservation under López.",
         "In Mexico it's reservación, not reserva. Expect: «¿Me permite una identificación?» — they want your passport."),
        ("Somos tres: mis dos hijas y yo.",
         "There are three of us — my two daughters and me.",
         "Answers «¿Cuántas personas?» Ages often affect the rate: «tienen nueve y doce años»."),
        ("¿Tiene un cuarto con dos camas?",
         "Do you have a room with two beds?",
         "Cuarto is the everyday word; the desk will say habitación. Two separate beds = dos camas. One big bed = cama matrimonial — don't ask for that by mistake."),
        ("¿Cuál es la contraseña del wifi?",
         "What's the wifi password?",
         "Wifi is said WEE-fee. They may answer with la red (the network name) and la clave — another word for password."),
        ("¿A qué hora es el desayuno?",
         "What time is breakfast?",
         "You'll hear something like «de siete a diez». If the numbers go by too fast: «¿Me lo escribe, por favor?»"),
        ("¿El desayuno está incluido?",
         "Is breakfast included in the price?",
         "Worth asking separately — many hotels serve breakfast but charge for it."),
        ("La llave no sirve.",
         "The key isn't working.",
         "No sirve is how Mexicans say something doesn't work — plain, not rude. For a keycard: «la tarjeta no sirve»."),
        ("¿Me da otra llave, por favor?",
         "Could I have another key, please?",
         "«¿Me da...?» is the normal Mexican way to ask for something — textbook «¿Podría darme...?» isn't wrong, just stiff. Careful: right after «la llave no sirve» they'll hear this as replace it. For a spare, say «¿Me da una llave extra?»"),
        ("¿Podemos entregar el cuarto más tarde?",
         "Can we check out later than the normal time?",
         "Entregar el cuarto is how checkout is phrased in Mexico; «hacer el check out más tarde» also works. Follow with «¿Hasta qué hora?» You may hear «hay un cargo» (there's a fee) or «depende de la ocupación» (depends how full we are)."),
        ("¿Podemos dejar las maletas aquí hasta la tarde?",
         "Can we leave our bags here until the afternoon?",
         "Normal at any hotel. They'll hand you a claim ticket — la ficha or el talón. Don't lose it."),
        ("Muchas gracias, muy amable.",
         "Thank you very much, that's kind of you.",
         "Muy amable is the everyday Mexican sign-off with service staff. Warmer than gracias on its own and it costs you nothing."),
    ],
    # --- Comer — ordering, allergies, paying ---
    TravelPhrase.RESTAURANT: [
        ("Mesa para cuatro, por favor.",
         "A table for four, please.",
         "You'll likely hear «¿Adentro o afuera?» — inside or outside. «Pásele» just means come on in."),
        ("¿Nos trae la carta, por favor?",
         "Could we get the menu?",
         "«La carta» is what you ask for. «Menú» is understood too, but «el menú del día» or «comida corrida» means the fixed-price lunch."),
        ("Mi hija es alérgica al cacahuate. Es grave.",
         "My daughter is allergic to peanuts. It's serious.",
         "Swap the allergen — the little word changes with it: a las nueces (tree nuts), a los mariscos (shellfish), al huevo, a la leche, al gluten. Say «es grave» — that's what makes them take it seriously."),
        ("¿Este platillo lleva cacahuate?",
         "Does this dish have peanut in it?",
         "«Lleva» is the word Mexicans use for what's in a dish. Reuse it: ¿lleva crema? ¿lleva cebolla?"),
        ("¿Qué me recomienda?",
         "What do you recommend?",
         "Ask it while pointing at the menu and you'll get a real answer, not a guess at a dish you can't picture."),
        ("¿Es muy picante?",
         "Is this spicy?",
         "«No pica» from a Mexican can still be hot for you. Follow up with «¿Me da la salsa aparte?» — salsa on the side."),
        ("Ella no come carne.",
         "She doesn't eat meat.",
         "Swap: pescado, puerco (pork), queso. Then add «¿Qué me recomienda para ella?»"),
        ("Para mí, esto, por favor.",
         "I'll have this one, please.",
         "Pointing at the menu is completely normal here. Say «para ella, esto» for each daughter."),
        ("¿Nos trae agua natural, por favor?",
         "Could we get some water?",
         "«Agua natural» = plain water. «Agua fresca» is a sweet fruit drink, «agua mineral» is sparkling. For bottled, say «agua embotellada»."),
        ("¿Nos trae la cuenta, por favor?",
         "Could we get the bill?",
         "They won't bring it until you ask — that's not rudeness, it's manners. Catching their eye and miming a signature also works."),
        ("¿Aceptan tarjeta?",
         "Do you take card?",
         "Ask before you order — small places are «solo efectivo» (cash only). The terminal comes to your table; you never hand the card over."),
        ("¿La propina ya está incluida?",
         "Is the tip already included?",
         "Usually it isn't. Ten to fifteen percent is normal. On card they'll ask «¿cuánto de propina?» — answer with a number, like «quince»."),
    ],
    # --- Encontrar el camino — where things are, getting there ---
    TravelPhrase.DIRECTIONS: [
        ("Disculpe, ¿dónde está el metro?",
         "Excuse me, where's the metro?",
         "\"Disculpe\" is the polite opener before any question to a stranger. Swap the ending: el baño, la parada del camión, el museo."),
        ("Ando perdido. Vamos al Zócalo.",
         "I'm lost. We're headed to the Zócalo.",
         "A woman says \"ando perdida.\" Naming where you're going gets you a real answer faster than asking for help in general."),
        ("¿Me lo enseña en el mapa?",
         "Can you show me on the map?",
         "In Mexico \"enseñar\" means to show. Hold out your phone — this rescues you when the spoken directions go by too fast."),
        ("Más despacio, por favor.",
         "Slower, please.",
         "Directions always come fast. Nobody minds repeating; say it before you lose the thread, not after."),
        ("¿Derecho o a la derecha?",
         "Straight ahead, or to the right?",
         "\"Derecho\" = straight; \"a la derecha\" = to the right. They sound almost identical. Always confirm this one."),
        ("¿Qué tan lejos está?",
         "How far is it?",
         "You'll hear \"aquí a dos cuadras\" (two blocks away) or \"está retirado\" (it's a ways off)."),
        ("¿Se puede ir caminando?",
         "Can we walk there?",
         "\"Sí, está cerquita\" means walk it. \"Mejor tome un taxi\" means don't — especially with the girls."),
        ("¿Qué camión me lleva al centro?",
         "Which bus goes downtown?",
         "A city bus is \"camión\" in Mexico. \"Autobús\" is the long-distance kind between cities."),
        ("Tres boletos, por favor.",
         "Three tickets, please.",
         "At the metro or bus window. Add \"¿Los niños pagan?\" to ask whether the girls need their own."),
        ("¿Este va a Coyoacán?",
         "Does this one go to Coyoacán?",
         "Say it at the door of the bus or on the platform, pointing. The fastest way to avoid riding the wrong direction."),
        ("¿Me avisa cuando lleguemos?",
         "Could you tell me when we get there?",
         "For the driver or whoever is next to you. \"Yo le aviso\" back means yes, they'll let you know."),
        ("¿Aquí nos bajamos?",
         "Is this our stop?",
         "For the moment of doubt as the doors open. You'll hear \"sí, aquí es\" or \"la que sigue\" (the next one)."),
    ],
    # --- Comprar — prices, sizes, paying ---
    TravelPhrase.SHOPPING: [
        ("Buenos días, ¿me puede ayudar?",
         "Good morning — can you help me?",
         "Opening a shop or stall. Switch to \"Buenas tardes\" after about 1 p.m."),
        ("Nada más estoy viendo, gracias.",
         "I'm just looking, thanks.",
         "The standard polite brush-off. Say it with a smile and they'll leave you alone."),
        ("¿Cuánto cuesta esto?",
         "How much is this?",
         "Point at the item. Numbers come back fast — ask them to write it if you miss it."),
        ("¿Me lo escribe, por favor?",
         "Could you write that down for me?",
         "Your safety net for any number you didn't catch. Works for prices, times, addresses."),
        ("¿Aceptan tarjeta?",
         "Do you take cards?",
         "Expect \"solo efectivo\" (cash only) at markets and small shops."),
        ("Solo traigo efectivo, ¿está bien?",
         "I've only got cash — is that OK?",
         "\"Traigo\" is how Mexicans say what they've got on them. Use it when the card didn't work or you're checking cash is fine."),
        ("¿Lo tiene en otra talla?",
         "Do you have this in another size?",
         "\"Talla\" is for clothes; use \"número\" for shoes: ¿Lo tiene en otro número?"),
        ("¿Tiene uno más grande?",
         "Do you have a bigger one?",
         "Swap \"más grande\" for \"más chico\" for smaller — Mexicans say \"chico\", not \"pequeño\". Say \"una\" if the thing is feminine (una blusa, una bolsa)."),
        ("Es para mi hija, tiene nueve años.",
         "It's for my daughter — she's nine.",
         "Saves a whole size conversation. Swap in \"mi hijo\" and the right number."),
        ("¿Me lo deja en doscientos?",
         "Would you let it go for two hundred?",
         "The polite market haggle — offer a number, don't insult theirs. Only at stalls, never in a real store."),
        ("Está muy bonito, pero se me hace caro.",
         "It's lovely, but it feels pricey to me.",
         "Your graceful exit. \"Se me hace caro\" is the real Mexican phrasing and often gets you a better price without you having to push."),
        ("¿Me da una bolsa, por favor?",
         "Could I get a bag, please?",
         "Bags often cost a few pesos. \"¿Me da...?\" is how Mexicans ask for things — natural, not blunt."),
    ],
    # --- La farmacia — often the first stop when someone feels ill ---
    TravelPhrase.PHARMACY: [
        ("Disculpe, ¿me ayuda?",
         "Excuse me, can you help me?",
         "Opener for the counter. \"Disculpe\" (usted) is the neutral, polite way to get someone's attention in Mexico."),
        ("Hablo poco español. Despacio, por favor.",
         "I don't speak much Spanish. Slowly, please.",
         "Say this early. It changes how fast they talk to you for the rest of the conversation."),
        ("Es para mi hija. Tiene nueve años.",
         "It's for my daughter. She's nine.",
         "Age matters more than anything else for dosing. Twelve = \"doce años\". Say it before naming the symptom."),
        ("Mi hija tiene fiebre.",
         "My daughter has a fever.",
         "\"Fiebre\" = FYEH-breh. If you took her temperature, they may ask \"¿cuántos grados?\" — that's Celsius (38 and up is a fever)."),
        ("Me duele la cabeza.",
         "I have a headache.",
         "Swap the body part: la garganta (throat), el estómago (stomach), la espalda (back), el oído (ear)."),
        ("A mi hija le duele la garganta.",
         "My daughter's throat hurts.",
         "Say \"a mi hija\" out loud — \"le duele\" by itself can mean him, her, or you, and the pharmacist may think you mean yourself. Same pattern for every body part above."),
        ("Mi hija tiene tos y le duele el estómago.",
         "My daughter has a cough and a stomachache.",
         "Name her again so \"tiene\" isn't heard as \"you have\". Also useful: diarrea (diarrhea), vómito (vomiting), gripa (a cold — Mexicans say \"gripa\", not \"gripe\")."),
        ("Empezó ayer.",
         "It started yesterday.",
         "Or: hoy (today), anoche (last night), hace dos días (two days ago). They will ask how long — have this ready."),
        ("¿Tiene algo para eso?",
         "Do you have something for that?",
         "The workhorse question. Point at whatever hurts and this alone gets you most of the way."),
        ("¿Es seguro para niños?",
         "Is this safe for kids?",
         "Ask it every time, even if they already know her age. Listen for \"infantil\" or \"pediátrico\" — that's the children's version."),
        ("¿Cuántas veces al día?",
         "How many times a day?",
         "Answer comes as \"cada ocho horas\" (every 8 hours) or \"tres veces al día\". Ask them to write it on the box: \"¿Me lo anota?\""),
        ("¿Necesito receta?",
         "Do I need a prescription?",
         "Antibiotics always require one in Mexico. If they say yes, ask \"¿Hay consultorio?\" — most pharmacies have a doctor's office attached, walk-in, for a small fee."),
    ],
    # --- Emergencias — the ones you hope not to need ---
    TravelPhrase.EMERGENCY: [
        ("¡Ayúdeme, por favor!",
         "Help me, please!",
         "Say this first, loud and clear, then explain. 'Ayúdeme' is ah-YOO-deh-meh — stress the YOO."),
        ("Es una emergencia.",
         "This is an emergency.",
         "Add this right after and people stop and listen. Expect '¿Qué pasó?' — What happened?"),
        ("Llame a la policía, por favor.",
         "Please call the police.",
         "In Mexico the number is 911. If you have a phone, 'Marque 911' — dial 911."),
        ("No encuentro a mi hija. Tiene nueve años.",
         "I can't find my daughter. She is nine years old.",
         "Do not say 'perdí a mi hija' — in Mexico that often lands as 'my daughter died.' 'No encuentro' is unmistakable. You will hear '¿Cómo se llama?' (her name) and '¿Hace cuánto?' (how long ago). Answer with her name and a number of minutes."),
        ("Trae una playera rosa y pantalón de mezclilla.",
         "She is wearing a pink t-shirt and jeans.",
         "Swap in the real colors. 'Playera' is a t-shirt and 'mezclilla' is denim in Mexico. Say what she is wearing before anything else about her."),
        ("Estoy perdido. ¿Dónde estamos?",
         "I am lost. Where are we?",
         "A woman says 'Estoy perdida.' Show a map or your hotel name on your phone as you say it — the street name back to you will be useless otherwise."),
        ("Me robaron la cartera.",
         "Someone took my wallet.",
         "'Cartera' is wallet in Mexico. This wording blames no one present, which keeps things calm; you do not need to name who did it."),
        ("No me siento bien.",
         "I do not feel well.",
         "Use this when you are unwell but it is not yet urgent. If it is urgent, go straight to 'Necesito un doctor.'"),
        ("Necesito un doctor.",
         "I need a doctor.",
         "'Médico' works too, but 'doctor' is understood everywhere and is easier to say under stress."),
        ("Llame a una ambulancia, por favor.",
         "Please call an ambulance.",
         "They will ask '¿Dónde están?' — where are you. Have the hotel name or a street sign ready to point at."),
        ("¿Dónde está el hospital más cercano?",
         "Where is the nearest hospital?",
         "The h is silent: os-pee-TAL. 'Cercano' is ser-KA-no. Expect them to point and say a number of blocks — 'cuadras'."),
        ("Me duele aquí.",
         "It hurts here.",
         "Point as you say it. Simpler and clearer than naming the body part. You may hear '¿Desde cuándo?' — since when."),
    ],
}


class Command(BaseCommand):
    help = "Seed the adult travel phrasebook (idempotent)."

    def handle(self, *args, **options):
        created = existing = 0
        for category in TravelPhrase.CATEGORY_ORDER:
            for order, (text, english, note) in enumerate(PHRASES.get(category, []), start=1):
                _, was_created = TravelPhrase.objects.get_or_create(
                    text=text, category=category,
                    defaults={"english": english, "note": note, "order": order},
                )
                created += was_created
                existing += not was_created
        self.stdout.write(self.style.SUCCESS(
            f"Travel phrases seeded: {created} created, {existing} already present."
        ))
        self.stdout.write(
            "Bake the audio with:  manage.py clips_build --travel\n"
            "Native audio is the pronunciation model — hear each one before you say it."
        )
