# Generated by Django 6.0.1 on 2026-08-10 23:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
        ('core', '0005_alter_familymembership_role'),
        ('students', '0004_student_portal_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="e.g. 'Jiu-jitsu', 'LRM with Mrs. Lee'", max_length=200)),
                ('event_type', models.CharField(choices=[('activity', 'Activity / sports'), ('coop', 'Co-op / class'), ('appointment', 'Appointment'), ('charter', 'Charter school (LRM, meetings)'), ('break', 'Break / no school'), ('other', 'Other')], default='other', max_length=20)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('date', models.DateField(help_text='The date — or the first occurrence, for a repeating event.')),
                ('start_time', models.TimeField(blank=True, help_text='Blank = all-day.', null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('repeats_weekly', models.BooleanField(default=False)),
                ('repeat_weekdays', models.JSONField(blank=True, default=list, help_text="Weekday numbers 0=Mon … 6=Sun. Empty = the start date's weekday.")),
                ('repeat_until', models.DateField(blank=True, null=True)),
                ('skip_dates', models.JSONField(blank=True, default=list, help_text='ISO dates of cancelled occurrences.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(blank=True, help_text='Optional: the program this event belongs to (borrows its icon).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_events', to='activities.externalactivity')),
                ('child', models.ForeignKey(blank=True, help_text='Leave blank for a whole-family event.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_events', to='students.student')),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_events', to='core.family')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date', 'start_time', 'id'],
            },
        ),
    ]
