# Generated by Django 6.0.1 on 2026-08-25 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_calendar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='reminder',
            field=models.CharField(blank=True, choices=[('', "The calendar's usual reminder"), ('none', 'No reminder'), ('0', 'At the start time'), ('10', '10 minutes before'), ('30', '30 minutes before'), ('60', '1 hour before'), ('120', '2 hours before'), ('1440', '1 day before'), ('2880', '2 days before'), ('10080', '1 week before')], default='', help_text="When Google should nudge you. Blank leaves it to the calendar's own setting.", max_length=8),
        ),
    ]
