# Generated by Django 6.0.1 on 2026-08-26 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_calendar', '0002_event_reminder'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleCalendarLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendar_id', models.CharField(max_length=255)),
                ('google_event_id', models.CharField(blank=True, max_length=1024)),
                ('content_hash', models.CharField(blank=True, max_length=64)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='google_links', to='family_calendar.calendarevent')),
            ],
            options={
                'ordering': ['calendar_id'],
                'constraints': [models.UniqueConstraint(fields=('event', 'calendar_id'), name='unique_google_link_per_event_calendar')],
            },
        ),
    ]
